// Generated by peg_gen — DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0

#include "hermes_parser.hpp"
#include <logos/hermes/access.hpp>
#include <logos/hermes/schema_codes.hpp>
#include <logos/verification/assert.hpp>
#include <charconv>
#include <cctype>

namespace logos::hermes {

using namespace hermes_ast;
using logos::hermes::AnyVal;
using TK = TK_HERMES;

// ── Lexer ─────────────────────────────────────────────────────────────────

HermesParser::HermesParser(std::string_view source) : source_(source) {}

HermesParser::Token HermesParser::next_token() {
    Token t;
    if (have_la_) { have_la_ = false; t = la_; } else { t = lex_one(); }
    // Track furthest consumed position for error reporting.
    if (t.kind != TK::Eof &&
        (t.line > furthest_.line ||
         (t.line == furthest_.line && t.text.data() >= furthest_.text.data())))
        furthest_ = t;
    return t;
}

HermesParser::Token HermesParser::peek_token() {
    if (!have_la_) { la_ = lex_one(); have_la_ = true; }
    return la_;
}

bool HermesParser::try_token(TK kind) {
    Token t = peek_token();
    if (t.kind == kind) {
        if (t.line > furthest_.line || (t.line == furthest_.line && t.text.data() >= furthest_.text.data()))
            furthest_ = t;
        next_token(); return true;
    }
    return false;
}

HermesParser::Token HermesParser::expect_token(TK kind, std::string_view what) {
    Token t = next_token();
    LOGOS_ASSERT(t.kind == kind, "HERMES-LEX-001",
        "expected {}, got '{}'", what, t.text);
    return t;
}

HermesParser::Token HermesParser::lex_one() {
    // Skip whitespace and comments.
    while (pos_ < source_.size()) {
        char c = source_[pos_];
        if (c == ' ' || c == '\t' || c == '\n' || c == '\r') { if (c == '\n') ++line_; ++pos_; continue; }
        if (c == '/' && pos_+1 < source_.size() && source_[pos_+1] == '/') {
            while (pos_ < source_.size() && source_[pos_] != '\n') ++pos_;
            continue; }
        if (c == '/' && pos_+1 < source_.size() && source_[pos_+1] == '*') {
            pos_ += 2;
            while (pos_+1 < source_.size() &&
                   !(source_[pos_] == '*' && source_[pos_+1] == '/')) ++pos_;
            if (pos_+1 < source_.size()) pos_ += 2;
            continue; }
        break;
    }
    if (pos_ >= source_.size()) return {TK::Eof, {}, line_};
    size_t   start      = pos_;
    uint32_t start_line_ = line_;
    char     c           = source_[pos_];
    (void)c;

    // Keyword / punctuation literals.
    if (source_.substr(pos_, 5).size() == 5 &&
        source_.substr(pos_, 5) == "false" &&
        (pos_ + 5 >= source_.size() || (!std::isalnum(source_[pos_ + 5]) && source_[pos_ + 5] != '_'))) {
        pos_ += 5; return {TK::FALSE_KW, source_.substr(start, 5), start_line_}; }
    if (source_.substr(pos_, 4).size() == 4 &&
        source_.substr(pos_, 4) == "true" &&
        (pos_ + 4 >= source_.size() || (!std::isalnum(source_[pos_ + 4]) && source_[pos_ + 4] != '_'))) {
        pos_ += 4; return {TK::TRUE_KW, source_.substr(start, 4), start_line_}; }
    if (source_.substr(pos_, 4).size() == 4 &&
        source_.substr(pos_, 4) == "null" &&
        (pos_ + 4 >= source_.size() || (!std::isalnum(source_[pos_ + 4]) && source_[pos_ + 4] != '_'))) {
        pos_ += 4; return {TK::NULL_KW, source_.substr(start, 4), start_line_}; }
    if (c == '{') { ++pos_; return {TK::LBRACE, source_.substr(start, 1), start_line_}; }
    if (c == '}') { ++pos_; return {TK::RBRACE, source_.substr(start, 1), start_line_}; }
    if (c == '[') { ++pos_; return {TK::LBRACKET, source_.substr(start, 1), start_line_}; }
    if (c == ']') { ++pos_; return {TK::RBRACKET, source_.substr(start, 1), start_line_}; }
    if (c == '(') { ++pos_; return {TK::LPAREN, source_.substr(start, 1), start_line_}; }
    if (c == ')') { ++pos_; return {TK::RPAREN, source_.substr(start, 1), start_line_}; }
    if (c == '<') { ++pos_; return {TK::LANGLE, source_.substr(start, 1), start_line_}; }
    if (c == '>') { ++pos_; return {TK::RANGLE, source_.substr(start, 1), start_line_}; }
    if (c == ':') { ++pos_; return {TK::COLON, source_.substr(start, 1), start_line_}; }
    if (c == ',') { ++pos_; return {TK::COMMA, source_.substr(start, 1), start_line_}; }
    if (c == '=') { ++pos_; return {TK::EQUALS, source_.substr(start, 1), start_line_}; }
    if (c == '$') { ++pos_; return {TK::DOLLAR, source_.substr(start, 1), start_line_}; }

    // STRING = /"([^"\\]|\\.)*"/
    if (c == '"') {
        ++pos_;
        while (pos_ < source_.size() && source_[pos_] != '"') {
            if (source_[pos_] == '\\') ++pos_;
            ++pos_;
        }
        if (pos_ < source_.size()) ++pos_;
        return {TK::STRING, source_.substr(start, pos_ - start), start_line_};
    }

    // INTEGER = /[-]?(0[xX][0-9a-fA-F]+|0[bB][01]+|0[oO][0-7]+|[0-9]+)(_(u|s)(8|16|32|64)|ull|ul|ll|u)?/
    if (std::isdigit(c) || (c == '-' && pos_+1 < source_.size() && std::isdigit(source_[pos_+1]))) {
        if (c == '-') ++pos_;
        int base = 10;
        if (pos_ < source_.size() && source_[pos_] == '0' && pos_+1 < source_.size()) {
            char nx = source_[pos_+1];
            if (nx == 'x' || nx == 'X') { base = 16; pos_ += 2; }
            else if (nx == 'b' || nx == 'B') { base = 2; pos_ += 2; }
            else if (nx == 'o' || nx == 'O') { base = 8; pos_ += 2; }
        }
        if (base == 16) {
            while (pos_ < source_.size() && (std::isxdigit(source_[pos_]) || source_[pos_] == '_')) ++pos_;
        } else if (base == 2) {
            while (pos_ < source_.size() && (source_[pos_] == '0' || source_[pos_] == '1' || source_[pos_] == '_')) ++pos_;
        } else if (base == 8) {
            while (pos_ < source_.size() && ((source_[pos_] >= '0' && source_[pos_] <= '7') || source_[pos_] == '_')) ++pos_;
        } else {
            while (pos_ < source_.size() && (std::isdigit(source_[pos_]) || source_[pos_] == '_')) ++pos_;
        }
        if (base == 10 && pos_ < source_.size() && source_[pos_] == '.'
            && pos_+1 < source_.size() && std::isdigit(source_[pos_+1])
            && !(start > 0 && source_[start - 1] == '.')) {
            ++pos_; // consume '.'
            while (pos_ < source_.size() && (std::isdigit(source_[pos_]) || source_[pos_] == '_')) ++pos_;
            if (pos_ < source_.size() && (source_[pos_] == 'e' || source_[pos_] == 'E')) {
                ++pos_;
                if (pos_ < source_.size() && (source_[pos_] == '+' || source_[pos_] == '-')) ++pos_;
                while (pos_ < source_.size() && (std::isdigit(source_[pos_]) || source_[pos_] == '_')) ++pos_;
            }
            if (pos_ + 3 <= source_.size() &&
                (source_.substr(pos_, 3) == "f32" || source_.substr(pos_, 3) == "f64")) {
                pos_ += 3;
            } else if (pos_ < source_.size() && (source_[pos_] == 'f' || source_[pos_] == 'd')) {
                ++pos_;
            }
            return {TK::FLOAT, source_.substr(start, pos_ - start), start_line_};
        }
        // Integer type suffix (longest match).
        auto try_suffix = [&](std::string_view sfx) -> bool {
            if (pos_ + sfx.size() <= source_.size() &&
                source_.substr(pos_, sfx.size()) == sfx) {
                pos_ += sfx.size(); return true;
            }
            return false;
        };
        if (!try_suffix("usize") && !try_suffix("isize") &&
            !try_suffix("_u64") && !try_suffix("_u32") && !try_suffix("_u16") && !try_suffix("_u8") &&
            !try_suffix("_s64") && !try_suffix("_s32") && !try_suffix("_s16") && !try_suffix("_s8") &&
            !try_suffix("i128") && !try_suffix("i64") && !try_suffix("i56") && !try_suffix("i32") && !try_suffix("i24") && !try_suffix("i16") && !try_suffix("i8") &&
            !try_suffix("u128") && !try_suffix("u64") && !try_suffix("u56") && !try_suffix("u32") && !try_suffix("u24") && !try_suffix("u16") && !try_suffix("u8") &&
            !try_suffix("ull") && !try_suffix("ul") && !try_suffix("ll")) {
            // Single-char 'u' — only if not followed by alnum/underscore.
            if (pos_ < source_.size() && source_[pos_] == 'u' &&
                (pos_+1 >= source_.size() || (!std::isalnum(source_[pos_+1]) && source_[pos_+1] != '_')))
                ++pos_;
        }
        return {TK::INTEGER, source_.substr(start, pos_ - start), start_line_};
    }

    // FLOAT = /[-]?[0-9]*\.[0-9]+([eE][+-]?[0-9]+)?[fd]?/ — handled by INTEGER longest-match above

    // IDENT = /[a-zA-Z_][a-zA-Z0-9_]*/
    if (std::isalpha(c) || c == '_') {
        while (pos_ < source_.size() && (std::isalnum(source_[pos_]) || source_[pos_] == '_'))
            ++pos_;
        return {TK::IDENT, source_.substr(start, pos_ - start), start_line_};
    }

    ++pos_; // unknown character — surface it to the parser
    return {TK::Invalid, source_.substr(start, 1), start_line_};
}

// ── Public entry points ───────────────────────────────────────────────────

logos::hermes::Hermes HermesParser::parse_value() {
    doc_ = logos::hermes::make_doc(524288).get();
    AnyVal root = rule_value();
    LOGOS_ASSERT(!root.is_null(), "HERMES-PARSE-001", "parse_value: expected value");
    logos::hermes::HermesAccess::set_root_offset(doc_, root.to_offset());
    return std::move(doc_);
}

logos::hermes::Hermes HermesParser::parse_map() {
    doc_ = logos::hermes::make_doc(524288).get();
    AnyVal root = rule_map();
    LOGOS_ASSERT(!root.is_null(), "HERMES-PARSE-001", "parse_map: expected map");
    logos::hermes::HermesAccess::set_root_offset(doc_, root.to_offset());
    return std::move(doc_);
}

logos::hermes::Hermes HermesParser::parse_array() {
    doc_ = logos::hermes::make_doc(524288).get();
    AnyVal root = rule_array();
    LOGOS_ASSERT(!root.is_null(), "HERMES-PARSE-001", "parse_array: expected array");
    logos::hermes::HermesAccess::set_root_offset(doc_, root.to_offset());
    return std::move(doc_);
}

logos::hermes::Hermes HermesParser::parse_typed_value() {
    doc_ = logos::hermes::make_doc(524288).get();
    AnyVal root = rule_typed_value();
    LOGOS_ASSERT(!root.is_null(), "HERMES-PARSE-001", "parse_typed_value: expected typed_value");
    logos::hermes::HermesAccess::set_root_offset(doc_, root.to_offset());
    return std::move(doc_);
}

logos::hermes::Hermes HermesParser::parse_typed_collection() {
    doc_ = logos::hermes::make_doc(524288).get();
    AnyVal root = rule_typed_collection();
    LOGOS_ASSERT(!root.is_null(), "HERMES-PARSE-001", "parse_typed_collection: expected typed_collection");
    logos::hermes::HermesAccess::set_root_offset(doc_, root.to_offset());
    return std::move(doc_);
}

// ── Grammar rules ─────────────────────────────────────────────────────────

AnyVal HermesParser::rule_value() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: param_val
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_param_val();
            if (cap1.is_null()) goto bt_value_0;
            return cap1;
        }
        [[maybe_unused]] bt_value_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 2: typed_value
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_typed_value();
            if (cap1.is_null()) goto bt_value_1;
            return cap1;
        }
        [[maybe_unused]] bt_value_1:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 3: typed_collection
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_typed_collection();
            if (cap1.is_null()) goto bt_value_2;
            return cap1;
        }
        [[maybe_unused]] bt_value_2:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 4: map
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_map();
            if (cap1.is_null()) goto bt_value_3;
            return cap1;
        }
        [[maybe_unused]] bt_value_3:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 5: array
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_array();
            if (cap1.is_null()) goto bt_value_4;
            return cap1;
        }
        [[maybe_unused]] bt_value_4:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 6: STRING => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::STRING) goto bt_value_5;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::STRING), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::STRING)));
            node->put(hermes_ast::VALUE, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_5:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 7: FLOAT => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::FLOAT) goto bt_value_6;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::FLOAT), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::FLOAT)));
            node->put(hermes_ast::VALUE, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_6:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 8: INTEGER => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::INTEGER) goto bt_value_7;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::INTEGER), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::INTEGER)));
            node->put(hermes_ast::VALUE, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_7:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 9: TRUE => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::TRUE_KW) goto bt_value_8;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::BOOLEAN), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::BOOLEAN)));
            node->put(hermes_ast::VALUE, AnyVal::from_value(uint8_t(1)), logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_8:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 10: FALSE => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::FALSE_KW) goto bt_value_9;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::BOOLEAN), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::BOOLEAN)));
            node->put(hermes_ast::VALUE, AnyVal::from_value(uint8_t(0)), logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_9:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 11: NULL => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::NULL_KW) goto bt_value_10;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 3).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::NULL_VAL), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::NULL_VAL)));
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_value_10:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_map() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: LBRACE (...)? COMMA? RBRACE => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            auto rcap_0 = doc_.make_array(4).get();
            if (peek_token().kind != TK::LBRACE) goto bt_map_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = AnyVal{};
            {
                [[maybe_unused]] size_t opt_pos_ = pos_; [[maybe_unused]] bool opt_la_ = have_la_; [[maybe_unused]] Token opt_tok_ = la_; [[maybe_unused]] uint32_t opt_line_ = line_;
                [[maybe_unused]] size_t opt_doc_ = doc_.arena_checkpoint();
                {
                    [[maybe_unused]] AnyVal cap2_s = AnyVal{};
                    {
                        [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                        // Group alt 1
                        {
                            grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                            {
                                [[maybe_unused]] AnyVal cap2_s_gi0_s0 = rule_map_entry();
                                if (cap2_s_gi0_s0.is_null()) goto grp_fail_2_0;
                                rcap_0.push_back(cap2_s_gi0_s0).get();
                                auto arr_3 = doc_.make_array(4).get();
                                {
                                    while (true) {
                                        [[maybe_unused]] size_t rep_pos_ = pos_; [[maybe_unused]] bool rep_la_ = have_la_; [[maybe_unused]] Token rep_tok_ = la_; [[maybe_unused]] uint32_t rep_line_ = line_;
                                        [[maybe_unused]] size_t rep_doc_ = doc_.arena_checkpoint();
                                        {
                                            [[maybe_unused]] AnyVal rep_item_3 = AnyVal{};
                                            {
                                                [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                                                // Group alt 1
                                                {
                                                    grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                                                    {
                                                        if (peek_token().kind != TK::COMMA) goto grp_fail_4_0;
                                                        Token tok_rep_item_3_gi0_s0_ = next_token();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s0 = doc_.make_string(tok_rep_item_3_gi0_s0_.text).get().to_anyval();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s1 = rule_map_entry();
                                                        if (rep_item_3_gi0_s1.is_null()) goto grp_fail_4_0;
                                                        rcap_0.push_back(rep_item_3_gi0_s1).get();
                                                        rep_item_3 = AnyVal{};  // multi-item group alt (no action)
                                                        goto grp_done_4;
                                                    }
                                                    grp_fail_4_0: ;
                                                    pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                                                }
                                                goto rep_fail_3;  // no group alternative matched
                                                grp_done_4: ;
                                            }
                                            if (!rep_item_3.is_null()) arr_3.push_back(rep_item_3).get();
                                            continue;
                                        }
                                        rep_fail_3: ;
                                        pos_ = rep_pos_; have_la_ = rep_la_; la_ = rep_tok_; line_ = rep_line_;
                                        // arena_rollback suppressed — AST lives until Hermes destruction
                                        break;
                                    }
                                }
                                [[maybe_unused]] AnyVal cap2_s_gi0_s1 = arr_3.to_anyval();
                                cap2_s = AnyVal{};  // multi-item group alt (no action)
                                goto grp_done_2;
                            }
                            grp_fail_2_0: ;
                            pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                        }
                        goto opt_fail_1;  // no group alternative matched
                        grp_done_2: ;
                    }
                    cap2 = cap2_s;
                    goto opt_done_1;
                }
                opt_fail_1: ;
                pos_ = opt_pos_; have_la_ = opt_la_; la_ = opt_tok_; line_ = opt_line_;
                // arena_rollback suppressed — AST lives until Hermes destruction
                opt_done_1: ;
            }
            [[maybe_unused]] AnyVal cap3 = AnyVal{};
            {
                [[maybe_unused]] size_t opt_pos_ = pos_; [[maybe_unused]] bool opt_la_ = have_la_; [[maybe_unused]] Token opt_tok_ = la_; [[maybe_unused]] uint32_t opt_line_ = line_;
                [[maybe_unused]] size_t opt_doc_ = doc_.arena_checkpoint();
                {
                    if (peek_token().kind != TK::COMMA) goto opt_fail_5;
                    Token tok_cap3_s_ = next_token();
                    [[maybe_unused]] AnyVal cap3_s = doc_.make_string(tok_cap3_s_.text).get().to_anyval();
                    cap3 = cap3_s;
                    goto opt_done_5;
                }
                opt_fail_5: ;
                pos_ = opt_pos_; have_la_ = opt_la_; la_ = opt_tok_; line_ = opt_line_;
                // arena_rollback suppressed — AST lives until Hermes destruction
                opt_done_5: ;
            }
            if (peek_token().kind != TK::RBRACE) goto bt_map_0;
            Token tok_cap4_ = next_token();
            [[maybe_unused]] AnyVal cap4 = doc_.make_string(tok_cap4_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::MAP), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::MAP)));
            node->put(hermes_ast::ITEMS, rcap_0.to_anyval(), logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_map_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_map_entry() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: (...) COLON value => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = AnyVal{};
            {
                [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                // Group alt 1
                {
                    grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                    {
                        if (peek_token().kind != TK::STRING) goto grp_fail_0_0;
                        Token tok_cap1_gi0_s0_ = next_token();
                        [[maybe_unused]] AnyVal cap1_gi0_s0 = doc_.make_string(tok_cap1_gi0_s0_.text).get().to_anyval();
                        cap1 = cap1_gi0_s0;
                        goto grp_done_0;
                    }
                    grp_fail_0_0: ;
                    pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                }
                // Group alt 2
                {
                    grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                    {
                        if (peek_token().kind != TK::IDENT) goto grp_fail_0_1;
                        Token tok_cap1_gi1_s0_ = next_token();
                        [[maybe_unused]] AnyVal cap1_gi1_s0 = doc_.make_string(tok_cap1_gi1_s0_.text).get().to_anyval();
                        cap1 = cap1_gi1_s0;
                        goto grp_done_0;
                    }
                    grp_fail_0_1: ;
                    pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                }
                goto bt_map_entry_0;  // no group alternative matched
                grp_done_0: ;
            }
            if (peek_token().kind != TK::COLON) goto bt_map_entry_0;
            Token tok_cap2_ = next_token();
            [[maybe_unused]] AnyVal cap2 = doc_.make_string(tok_cap2_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap3 = rule_value();
            if (cap3.is_null()) goto bt_map_entry_0;
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 5).get();
            node->put(hermes_ast::VALUE, cap3, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::MAP_ENTRY), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::MAP_ENTRY)));
            node->put(hermes_ast::KEY, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_map_entry_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_array() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: LBRACKET (...)? COMMA? RBRACKET => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            auto rcap_0 = doc_.make_array(4).get();
            if (peek_token().kind != TK::LBRACKET) goto bt_array_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = AnyVal{};
            {
                [[maybe_unused]] size_t opt_pos_ = pos_; [[maybe_unused]] bool opt_la_ = have_la_; [[maybe_unused]] Token opt_tok_ = la_; [[maybe_unused]] uint32_t opt_line_ = line_;
                [[maybe_unused]] size_t opt_doc_ = doc_.arena_checkpoint();
                {
                    [[maybe_unused]] AnyVal cap2_s = AnyVal{};
                    {
                        [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                        // Group alt 1
                        {
                            grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                            {
                                [[maybe_unused]] AnyVal cap2_s_gi0_s0 = rule_value();
                                if (cap2_s_gi0_s0.is_null()) goto grp_fail_2_0;
                                rcap_0.push_back(cap2_s_gi0_s0).get();
                                auto arr_3 = doc_.make_array(4).get();
                                {
                                    while (true) {
                                        [[maybe_unused]] size_t rep_pos_ = pos_; [[maybe_unused]] bool rep_la_ = have_la_; [[maybe_unused]] Token rep_tok_ = la_; [[maybe_unused]] uint32_t rep_line_ = line_;
                                        [[maybe_unused]] size_t rep_doc_ = doc_.arena_checkpoint();
                                        {
                                            [[maybe_unused]] AnyVal rep_item_3 = AnyVal{};
                                            {
                                                [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                                                // Group alt 1
                                                {
                                                    grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                                                    {
                                                        if (peek_token().kind != TK::COMMA) goto grp_fail_4_0;
                                                        Token tok_rep_item_3_gi0_s0_ = next_token();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s0 = doc_.make_string(tok_rep_item_3_gi0_s0_.text).get().to_anyval();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s1 = rule_value();
                                                        if (rep_item_3_gi0_s1.is_null()) goto grp_fail_4_0;
                                                        rcap_0.push_back(rep_item_3_gi0_s1).get();
                                                        rep_item_3 = AnyVal{};  // multi-item group alt (no action)
                                                        goto grp_done_4;
                                                    }
                                                    grp_fail_4_0: ;
                                                    pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                                                }
                                                goto rep_fail_3;  // no group alternative matched
                                                grp_done_4: ;
                                            }
                                            if (!rep_item_3.is_null()) arr_3.push_back(rep_item_3).get();
                                            continue;
                                        }
                                        rep_fail_3: ;
                                        pos_ = rep_pos_; have_la_ = rep_la_; la_ = rep_tok_; line_ = rep_line_;
                                        // arena_rollback suppressed — AST lives until Hermes destruction
                                        break;
                                    }
                                }
                                [[maybe_unused]] AnyVal cap2_s_gi0_s1 = arr_3.to_anyval();
                                cap2_s = AnyVal{};  // multi-item group alt (no action)
                                goto grp_done_2;
                            }
                            grp_fail_2_0: ;
                            pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                        }
                        goto opt_fail_1;  // no group alternative matched
                        grp_done_2: ;
                    }
                    cap2 = cap2_s;
                    goto opt_done_1;
                }
                opt_fail_1: ;
                pos_ = opt_pos_; have_la_ = opt_la_; la_ = opt_tok_; line_ = opt_line_;
                // arena_rollback suppressed — AST lives until Hermes destruction
                opt_done_1: ;
            }
            [[maybe_unused]] AnyVal cap3 = AnyVal{};
            {
                [[maybe_unused]] size_t opt_pos_ = pos_; [[maybe_unused]] bool opt_la_ = have_la_; [[maybe_unused]] Token opt_tok_ = la_; [[maybe_unused]] uint32_t opt_line_ = line_;
                [[maybe_unused]] size_t opt_doc_ = doc_.arena_checkpoint();
                {
                    if (peek_token().kind != TK::COMMA) goto opt_fail_5;
                    Token tok_cap3_s_ = next_token();
                    [[maybe_unused]] AnyVal cap3_s = doc_.make_string(tok_cap3_s_.text).get().to_anyval();
                    cap3 = cap3_s;
                    goto opt_done_5;
                }
                opt_fail_5: ;
                pos_ = opt_pos_; have_la_ = opt_la_; la_ = opt_tok_; line_ = opt_line_;
                // arena_rollback suppressed — AST lives until Hermes destruction
                opt_done_5: ;
            }
            if (peek_token().kind != TK::RBRACKET) goto bt_array_0;
            Token tok_cap4_ = next_token();
            [[maybe_unused]] AnyVal cap4 = doc_.make_string(tok_cap4_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::ARRAY), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::ARRAY)));
            node->put(hermes_ast::ITEMS, rcap_0.to_anyval(), logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_array_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_typed_value() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: datatype LPAREN value RPAREN => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_datatype();
            if (cap1.is_null()) goto bt_typed_value_0;
            if (peek_token().kind != TK::LPAREN) goto bt_typed_value_0;
            Token tok_cap2_ = next_token();
            [[maybe_unused]] AnyVal cap2 = doc_.make_string(tok_cap2_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap3 = rule_value();
            if (cap3.is_null()) goto bt_typed_value_0;
            if (peek_token().kind != TK::RPAREN) goto bt_typed_value_0;
            Token tok_cap4_ = next_token();
            [[maybe_unused]] AnyVal cap4 = doc_.make_string(tok_cap4_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 5).get();
            node->put(hermes_ast::VALUE, cap3, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::TYPED_VALUE), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::TYPED_VALUE)));
            node->put(hermes_ast::NAME, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_typed_value_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_typed_collection() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: typed_array
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_typed_array();
            if (cap1.is_null()) goto bt_typed_collection_0;
            return cap1;
        }
        [[maybe_unused]] bt_typed_collection_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 2: typed_map
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_typed_map();
            if (cap1.is_null()) goto bt_typed_collection_1;
            return cap1;
        }
        [[maybe_unused]] bt_typed_collection_1:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_typed_array() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: LANGLE datatype RANGLE array
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::LANGLE) goto bt_typed_array_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = rule_datatype();
            if (cap2.is_null()) goto bt_typed_array_0;
            if (peek_token().kind != TK::RANGLE) goto bt_typed_array_0;
            Token tok_cap3_ = next_token();
            [[maybe_unused]] AnyVal cap3 = doc_.make_string(tok_cap3_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap4 = rule_array();
            if (cap4.is_null()) goto bt_typed_array_0;
            return cap4;
        }
        [[maybe_unused]] bt_typed_array_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_typed_map() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: LANGLE datatype RANGLE map
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::LANGLE) goto bt_typed_map_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = rule_datatype();
            if (cap2.is_null()) goto bt_typed_map_0;
            if (peek_token().kind != TK::RANGLE) goto bt_typed_map_0;
            Token tok_cap3_ = next_token();
            [[maybe_unused]] AnyVal cap3 = doc_.make_string(tok_cap3_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap4 = rule_map();
            if (cap4.is_null()) goto bt_typed_map_0;
            return cap4;
        }
        [[maybe_unused]] bt_typed_map_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 2: LANGLE datatype COMMA datatype RANGLE map
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::LANGLE) goto bt_typed_map_1;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = rule_datatype();
            if (cap2.is_null()) goto bt_typed_map_1;
            if (peek_token().kind != TK::COMMA) goto bt_typed_map_1;
            Token tok_cap3_ = next_token();
            [[maybe_unused]] AnyVal cap3 = doc_.make_string(tok_cap3_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap4 = rule_datatype();
            if (cap4.is_null()) goto bt_typed_map_1;
            if (peek_token().kind != TK::RANGLE) goto bt_typed_map_1;
            Token tok_cap5_ = next_token();
            [[maybe_unused]] AnyVal cap5 = doc_.make_string(tok_cap5_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap6 = rule_map();
            if (cap6.is_null()) goto bt_typed_map_1;
            return cap6;
        }
        [[maybe_unused]] bt_typed_map_1:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_datatype() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: IDENT (...)? => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            auto rcap_0 = doc_.make_array(4).get();
            if (peek_token().kind != TK::IDENT) goto bt_datatype_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            [[maybe_unused]] AnyVal cap2 = AnyVal{};
            {
                [[maybe_unused]] size_t opt_pos_ = pos_; [[maybe_unused]] bool opt_la_ = have_la_; [[maybe_unused]] Token opt_tok_ = la_; [[maybe_unused]] uint32_t opt_line_ = line_;
                [[maybe_unused]] size_t opt_doc_ = doc_.arena_checkpoint();
                {
                    [[maybe_unused]] AnyVal cap2_s = AnyVal{};
                    {
                        [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                        // Group alt 1
                        {
                            grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                            {
                                if (peek_token().kind != TK::LANGLE) goto grp_fail_2_0;
                                Token tok_cap2_s_gi0_s0_ = next_token();
                                [[maybe_unused]] AnyVal cap2_s_gi0_s0 = doc_.make_string(tok_cap2_s_gi0_s0_.text).get().to_anyval();
                                [[maybe_unused]] AnyVal cap2_s_gi0_s1 = rule_type_arg();
                                if (cap2_s_gi0_s1.is_null()) goto grp_fail_2_0;
                                rcap_0.push_back(cap2_s_gi0_s1).get();
                                auto arr_3 = doc_.make_array(4).get();
                                {
                                    while (true) {
                                        [[maybe_unused]] size_t rep_pos_ = pos_; [[maybe_unused]] bool rep_la_ = have_la_; [[maybe_unused]] Token rep_tok_ = la_; [[maybe_unused]] uint32_t rep_line_ = line_;
                                        [[maybe_unused]] size_t rep_doc_ = doc_.arena_checkpoint();
                                        {
                                            [[maybe_unused]] AnyVal rep_item_3 = AnyVal{};
                                            {
                                                [[maybe_unused]] size_t grp_pos_ = 0; [[maybe_unused]] bool grp_la_ = false; [[maybe_unused]] Token grp_tok_; [[maybe_unused]] size_t grp_doc_ = 0; [[maybe_unused]] uint32_t grp_line_ = 0;
                                                // Group alt 1
                                                {
                                                    grp_pos_ = pos_; grp_la_ = have_la_; grp_tok_ = la_; grp_doc_ = doc_.arena_checkpoint(); grp_line_ = line_;
                                                    {
                                                        if (peek_token().kind != TK::COMMA) goto grp_fail_4_0;
                                                        Token tok_rep_item_3_gi0_s0_ = next_token();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s0 = doc_.make_string(tok_rep_item_3_gi0_s0_.text).get().to_anyval();
                                                        [[maybe_unused]] AnyVal rep_item_3_gi0_s1 = rule_type_arg();
                                                        if (rep_item_3_gi0_s1.is_null()) goto grp_fail_4_0;
                                                        rcap_0.push_back(rep_item_3_gi0_s1).get();
                                                        rep_item_3 = AnyVal{};  // multi-item group alt (no action)
                                                        goto grp_done_4;
                                                    }
                                                    grp_fail_4_0: ;
                                                    pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                                                }
                                                goto rep_fail_3;  // no group alternative matched
                                                grp_done_4: ;
                                            }
                                            if (!rep_item_3.is_null()) arr_3.push_back(rep_item_3).get();
                                            continue;
                                        }
                                        rep_fail_3: ;
                                        pos_ = rep_pos_; have_la_ = rep_la_; la_ = rep_tok_; line_ = rep_line_;
                                        // arena_rollback suppressed — AST lives until Hermes destruction
                                        break;
                                    }
                                }
                                [[maybe_unused]] AnyVal cap2_s_gi0_s2 = arr_3.to_anyval();
                                if (peek_token().kind != TK::RANGLE) goto grp_fail_2_0;
                                Token tok_cap2_s_gi0_s3_ = next_token();
                                [[maybe_unused]] AnyVal cap2_s_gi0_s3 = doc_.make_string(tok_cap2_s_gi0_s3_.text).get().to_anyval();
                                cap2_s = AnyVal{};  // multi-item group alt (no action)
                                goto grp_done_2;
                            }
                            grp_fail_2_0: ;
                            pos_ = grp_pos_; have_la_ = grp_la_; la_ = grp_tok_; line_ = grp_line_;
                        }
                        goto opt_fail_1;  // no group alternative matched
                        grp_done_2: ;
                    }
                    cap2 = cap2_s;
                    goto opt_done_1;
                }
                opt_fail_1: ;
                pos_ = opt_pos_; have_la_ = opt_la_; la_ = opt_tok_; line_ = opt_line_;
                // arena_rollback suppressed — AST lives until Hermes destruction
                opt_done_1: ;
            }
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 5).get();
            node->put(hermes_ast::PARAMS, rcap_0.to_anyval(), logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::DATATYPE), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::DATATYPE)));
            node->put(hermes_ast::NAME, cap1, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_datatype_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_type_arg() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: datatype
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            [[maybe_unused]] AnyVal cap1 = rule_datatype();
            if (cap1.is_null()) goto bt_type_arg_0;
            return cap1;
        }
        [[maybe_unused]] bt_type_arg_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    // Alternative 2: INTEGER
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::INTEGER) goto bt_type_arg_1;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            return cap1;
        }
        [[maybe_unused]] bt_type_arg_1:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

AnyVal HermesParser::rule_param_val() {
    [[maybe_unused]] size_t saved_pos = 0;
    [[maybe_unused]] bool   saved_la  = false;
    [[maybe_unused]] size_t saved_doc_ = 0;

    // Alternative 1: DOLLAR INTEGER => {...}
    {
        saved_pos  = pos_;
        saved_la   = have_la_;
        saved_doc_ = doc_.arena_checkpoint();
        [[maybe_unused]] Token    saved_tok_  = la_;
        [[maybe_unused]] uint32_t saved_line_ = line_;

        {
            [[maybe_unused]] uint32_t first_line_ = peek_token().line;
            if (peek_token().kind != TK::DOLLAR) goto bt_param_val_0;
            Token tok_cap1_ = next_token();
            [[maybe_unused]] AnyVal cap1 = doc_.make_string(tok_cap1_.text).get().to_anyval();
            if (peek_token().kind != TK::INTEGER) goto bt_param_val_0;
            Token tok_cap2_ = next_token();
            [[maybe_unused]] AnyVal cap2 = doc_.make_string(tok_cap2_.text).get().to_anyval();
            auto* node = logos::hermes::HermesAccess::raw_tiny_map(doc_, 4).get();
            node->put(hermes_ast::CODE, AnyVal::from_value(hermes_ast::PARAM_VAL), logos::hermes::HermesAccess::arena(doc_)).get();
            node->set_schema_type_code(logos::hermes::schema::ast(static_cast<int32_t>(hermes_ast::PARAM_VAL)));
            node->put(hermes_ast::VALUE, cap2, logos::hermes::HermesAccess::arena(doc_)).get();
            node->put(hermes_ast::SRC_LINE, AnyVal::from_value(first_line_), logos::hermes::HermesAccess::arena(doc_)).get();
            {
                AnyVal result_;
                result_.set_pointer(node, logos::hermes::HermesAccess::base(doc_));
                return result_;
            }
        }
        [[maybe_unused]] bt_param_val_0:
        pos_      = saved_pos;
        have_la_  = saved_la;
        la_       = saved_tok_;
        line_     = saved_line_;
        // arena_rollback suppressed — AST lives until Hermes destruction
    }

    return AnyVal{}; // no alternative matched
}

} // namespace logos::hermes

