// Generated by peg_gen — DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <string_view>
#include <unordered_map>
#include <utility>
#include <logos/core/named_code.hpp>
#include <logos/hermes/view.hpp>

namespace logos::hermes {

// ── AST field keys (%fields) and node codes (%nodes) ─────────────────────
namespace hermes_ast {
    using Key  = logos::NamedCode<uint8_t>;
    using Code = logos::NamedCode<int32_t>;

    // Field keys (TinyObjectMap slot indices).  Group-scoped keys
    // live in nested namespaces; the same slot number may be reused
    // across groups because distinct node types never co-exist in one map.
    inline constexpr Key  CODE                 {"CODE", 0};
    inline constexpr Key  VALUE                {"VALUE", 1};
    inline constexpr Key  KEY                  {"KEY", 2};
    inline constexpr Key  ITEMS                {"ITEMS", 3};
    inline constexpr Key  NAME                 {"NAME", 4};
    inline constexpr Key  PARAMS               {"PARAMS", 5};
    inline constexpr Key  SRC_LINE             {"SRC_LINE", 6};

    // Node type discriminants
    inline constexpr Code MAP                  {"MAP", 0};
    inline constexpr Code ARRAY                {"ARRAY", 1};
    inline constexpr Code STRING               {"STRING", 2};
    inline constexpr Code INTEGER              {"INTEGER", 3};
    inline constexpr Code FLOAT                {"FLOAT", 4};
    inline constexpr Code BOOLEAN              {"BOOLEAN", 5};
    inline constexpr Code NULL_VAL             {"NULL_VAL", 6};
    inline constexpr Code TYPED_VALUE          {"TYPED_VALUE", 7};
    inline constexpr Code DATATYPE             {"DATATYPE", 8};
    inline constexpr Code MAP_ENTRY            {"MAP_ENTRY", 9};
    inline constexpr Code PARAM_VAL            {"PARAM_VAL", 10};

} // namespace hermes_ast

// ── Token kinds (generated from %tokens) ────────────────────────────────
enum class TK_HERMES : int {
    Eof = 0,
    Invalid,
    LBRACE,   // "{"
    RBRACE,   // "}"
    LBRACKET,   // "["
    RBRACKET,   // "]"
    LPAREN,   // "("
    RPAREN,   // ")"
    LANGLE,   // "<"
    RANGLE,   // ">"
    COLON,   // ":"
    COMMA,   // ","
    EQUALS,   // "="
    DOLLAR,   // "$"
    TRUE_KW,   // "true"
    FALSE_KW,   // "false"
    NULL_KW,   // "null"
    STRING,   // /"([^"\\]|\\.)*"/
    INTEGER,   // /[-]?(0[xX][0-9a-fA-F]+|0[bB][01]+|0[oO][0-7]+|[0-9]+)(_(u|s)(8|16|32|64)|ull|ul|ll|u)?/
    FLOAT,   // /[-]?[0-9]*\.[0-9]+([eE][+-]?[0-9]+)?[fd]?/
    IDENT,   // /[a-zA-Z_][a-zA-Z0-9_]*/
};

// ── Parser ───────────────────────────────────────────────────────────────
class HermesParser {
public:
    explicit HermesParser(std::string_view source);

    // Entry points for exported rules.
    logos::hermes::Hermes parse_value();
    logos::hermes::Hermes parse_map();
    logos::hermes::Hermes parse_array();
    logos::hermes::Hermes parse_typed_value();
    logos::hermes::Hermes parse_typed_collection();

    // Returns true when all input tokens have been consumed.
    bool at_eof() { return peek_token().kind == TK::Eof; }
    // Line number of the next unconsumed token (1-based).
    uint32_t next_line() { return peek_token().line; }
    // Text of the next unconsumed token.
    std::string_view next_text() { return peek_token().text; }
    // Furthest token the parser ever successfully consumed.
    // Points to the deepest parse position before backtracking —
    // use this for error reporting instead of next_text()/next_line().
    uint32_t         furthest_line() const { return furthest_.line ? furthest_.line : 1; }
    std::string_view furthest_text() const { return furthest_.text; }

private:
    logos::hermes::AnyVal rule_value();
    logos::hermes::AnyVal rule_map();
    logos::hermes::AnyVal rule_map_entry();
    logos::hermes::AnyVal rule_array();
    logos::hermes::AnyVal rule_typed_value();
    logos::hermes::AnyVal rule_typed_collection();
    logos::hermes::AnyVal rule_typed_array();
    logos::hermes::AnyVal rule_typed_map();
    logos::hermes::AnyVal rule_datatype();
    logos::hermes::AnyVal rule_type_arg();
    logos::hermes::AnyVal rule_param_val();

    // Lexer state.
    using TK = TK_HERMES;
    struct Token { TK kind; std::string_view text; uint32_t line = 0; };
    Token lex_one();
    Token next_token();
    Token peek_token();
    bool  try_token(TK kind);
    Token expect_token(TK kind, std::string_view what);

    logos::hermes::Hermes doc_;
    std::string_view         source_;
    size_t                   pos_ = 0;
    uint32_t                 line_ = 1;  // current source line (1-based)
    Token                    la_{};
    bool                     have_la_ = false;
    Token                    furthest_{}; // furthest successfully consumed token
}; // class HermesParser

} // namespace logos::hermes

