#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from aggregate_extended_borrow_temp_never_dropped.logos
// SOUNDNESS QUEUE row aggregate_extended_borrow_temp_never_dropped (tier 1). A TEMPORARY WHOSE LIFETIME IS EXTENDED THROUGH AN
// AGGREGATE `let` INITIALISER IS NEVER DROPPED.
//
// `let t: (&C, i64) = (&C { v: 1000 }, 1);` extends the temporary to the end of the block (Rust
// r[destructors.scope.lifetime-extension.exprs]); it must drop there: 1000, exit 0. TODAY 0, exit 1. mark_extending_borrows
// marks the `&` as extending, so lower_unary keeps the anonymous addr_of_temp spill, and only a DIRECT `let p = &<rvalue>`
// gets lower_let's named __lit_temp_N owner. Not the autoref class (an explicit `&`, owned by the block, not the statement);
// unmoved by the 2026-09-14o landing (0 -> 0), which closed the direct `let r = &&<rvalue>` form only.
// Found 2026-09-14o-autoreffund by hand program x05. Legality by reading; no rustc binary on this box.
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct C { v: i64, c: *mut i64 }
impl Drop for C { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let mut inside: i64 = 0i64;
    {
        let t: (&C, i64) = (&C { v: 1000i64, c: p }, 1i64);
        if t.0.v != 1000i64 { return 3i32; }
        inside = unsafe { n };
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"inside=%ld n=%ld\n".as_ptr(), inside, got); }
    if inside != 0i64 { return 2i32; }
    if got != 1000i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
