#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from array_nonprim_elem_eq_compares_addresses_run.logos
// SOUNDNESS QUEUE row array_nonprim_elem_eq_compares_addresses_run (tier 1). WRONG ANSWER AT RUN TIME.
// `==` over two ARRAYS whose element is not a primitive compares the two slot ADDRESSES: PART 1 `[S; 2] == [S; 2]`
// (S: Eq + Drop, by value) -> exit 1; PART 2 `&[S; 2] == &[S; 2]` -> exit 2; PART 3 `[[i64; 2]; 2] !=` (nested array)
// -> exit 3. Rust compares element-wise (`impl PartialEq<[B; N]> for [A; N]`): exit 0, destructor count 8. The by-value
// block is LAST and its operands are not used after it: on base a by-value array `==` MOVES its operands (a later use is
// refused 'cannot borrow moved value'), a separate defect this program does not pin. Exit reads the LAST wrong part (1 wins).
// DECISION SITE: mlir-gen gen_expr_kind(EBinOpView)'s array fast path compares element-wise only for a PRIMITIVE element
// and falls through to the pointer compare otherwise; sema lower_binop has no array arm. NOT the reference layer: the
// by-value spelling is wrong too. Found by 2026-09-15b-refeqland's hand battery (f01 f01v f02 f38 f38v): its first
// candidate dereferenced ANY array reference pair to the by-value compare and REFUSED f01 / f02 ("cannot move out of a
// value behind a shared reference (E0507)"); the landed arm dereferences only a primitive-element array.
// Measured on build/ 854d99ae9a2e2fbd 43 (base). Legality by reading; no rustc binary.
struct S { v: i64, c: *mut i64 }
impl Drop for S {
    fn drop(&mut self) {
        unsafe { *self.c = *self.c + 1i64; }
    }
}
impl PartialEq for S {
    fn eq(&self, other: &S) -> bool { return false; /* CONTROL */
        return self.v == other.v;
    }
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let mut part: i32 = 0i32;
    {
        let a: [S; 2] = [S { v: 1i64, c: p }, S { v: 2i64, c: p }];
        let b: [S; 2] = [S { v: 1i64, c: p }, S { v: 2i64, c: p }];
        let ra: &[S; 2] = &a;
        let rb: &[S; 2] = &b;
        if !(ra == rb) { part = 2i32; }
    }
    {
        let a: [S; 2] = [S { v: 1i64, c: p }, S { v: 2i64, c: p }];
        let b: [S; 2] = [S { v: 1i64, c: p }, S { v: 2i64, c: p }];
        if !(a == b) { part = 1i32; }
    }
    let got: i64 = unsafe { n };
    if got != 8i64 { return 10i32 + got as i32; }
    if part != 0i32 { return part; }
    let x: [[i64; 2]; 2] = [[1i64, 2i64], [3i64, 4i64]];
    let y: [[i64; 2]; 2] = [[1i64, 2i64], [3i64, 4i64]];
    if x != y { return 3i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
