#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from closure_param_shadow_double_drop.logos
// SOUNDNESS QUEUE row closure_param_shadow_double_drop (tier 1). A LOCAL SHADOWING A CLOSURE PARAMETER OF THE SAME NAME
// RUNS THE LOCAL'S DESTRUCTOR TWICE AND THE ARGUMENT'S NEVER — shadow_over_param_double_drop inside a closure body.
//
// `|x: D| { let x = D{2, x.c}; return x.v; }`: Rust 21, exit 0. TODAY 22 (the local twice, the argument never), exit 1. ROWED WITH REASON 1 (the fact has no carrier
// there): the priced fix carries the binding's SLOT on SDrop and resolves it in mlir-gen, and a closure's parameters reach
// mlir-gen as CL_PARAM_NAMES / CL_PARAM_TYPES (EClosureBoxView::each_param yields name and type only) — no slot exists to
// resolve. Measured 2026-09-14p-shadowslot: exit 1 under shslot, shslotmg and shslotx alike. Found by hand program s19.
// Legality by reading; no rustc binary.
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
fn eatd(x: D) -> i64 { return x.v; }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let f = |x: D| -> i64 { let x: D = D { v: 2i64, c: x.c }; return x.v; };
    let r: i64 = f(D { v: 1i64, c: p });
    if r != 2i64 { return 9i32; }
    if rd(p) != 21i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
