#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from match_arm_nested_binder_shadow_double_drop.logos
// SOUNDNESS QUEUE row match_arm_nested_binder_shadow_double_drop (tier 1). A BINDER NESTED UNDER A TUPLE-STRUCT OR SLICE PATTERN IN
// A MATCH ARM, SHADOWING AN OUTER LOCAL, WITH A `return` IN THE ARM: THE ARM BINDING IS DESTROYED TWICE AND THE OUTER LOCAL NEVER.
//
// `let x = D{1}; match t { T(x, k) => { return x.v + k; } }`: Rust 21 (arm binding 2, then outer 1), exit 0. TODAY 22, exit 1 —
// on the base binary AND on the 2026-09-15 shadowslot landing; the renamed control `T(y, k)` reads 21 on both. The slice spelling
// `[a, b] => return` reads 32232 where its renamed control reads 32231 (that control is itself wrong: row
// slice_pattern_arm_binding_extra_drops).
// ROWED WITH REASON 1 (the fact has no carrier there): the landing resolves a drop by SLOT, registered where mlir-gen binds a name;
// this binder is built by SemaChecker::build_pattern's generic PAT_WILD arm, which emits PatWild with slot 0xFFFFFFFF, so the arm
// binding is never registered and the outer drop cannot tell it from the outer binding. Minting a slot there also changes what
// borrow_check's declare_pat_bindings declares — a second consumer, a different change.
// Found 2026-09-15 by hand programs c06 / k06 / k30. Legality by reading; no rustc binary.
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
struct T(D, i64);
fn g(p: *mut i64) -> i64 {
    let x: D = D { v: 1i64, c: p };
    let t: T = T(D { v: 2i64, c: p }, 3i64);
    match t {
        T(x, k) => { return x.v + k; }
    }
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    if g(p) != 5i64 { return 9i32; }
    if rd(p) != 21i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
