#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from operator_operand_owner_after_sibling_exit_leak.logos
// SOUNDNESS QUEUE row operator_operand_owner_after_sibling_exit_leak (tier 1). AN OPERATOR OPERAND'S TEMPORARY LEAKS WHEN A
// LATER OPERAND OF THE SAME OPERATOR LEAVES THE FUNCTION OR THE LOOP.
//
// `mk(2, s) == { if k > 0 { return 5; } mk(3, s) }`: the left temporary is built (2), then the right operand returns.
// Rust drops the left temporary on that path: 26, exit 0. TODAY 2, exit 1 — it is never destroyed.
//
// NEIGHBOUR of the 2026-09-14o-autoreffund landing, ROWED WITH REASON 1 (the fact has no carrier there): lower_binop lowers
// BOTH operands before push_operand calls SemaChecker::autoref_operand, so the owner of the left temporary is registered
// in the statement temp scope only AFTER the right operand's `return` has already collected its drops. No change at
// push_operand can reach an exit that was lowered before it ran. Members measured on build-land0913d (landing, unarmed)
// against base b54c1160ae8e4066: this program 2 -> 2; `break` in the right operand in a loop 232 -> 23762 (Rust 237626);
// `continue` 223 -> 22376 (Rust 262376) — the landing drops every temporary on the fall-through path and none of the
// left temporaries on the exit path. A method RECEIVER is not affected: its owner is registered when the receiver is
// lowered (`mk(2).get() + { return 5; }` reads 26 on base).
// Found 2026-09-14o-autoreffund by hand program c02. Legality by reading; no rustc binary on this box.
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, s: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
impl PartialEq for D { fn eq(&self, other: &D) -> bool { return self.v > 0i64 && other.v > 0i64; } }
fn mk(v: i64, s: *mut i64) -> D {
    unsafe { *s = *s * 10i64 + v; }
    return D { v: v, s: s };
}
fn side(s: *mut i64) -> i64 {
    unsafe { *s = *s * 10i64 + 1i64; }
    return 1i64;
}
fn pick<'a>(d: &'a D, s: *mut i64) -> &'a D {
    unsafe { *s = *s * 10i64 + 1i64; }
    return d;
}
fn rd(s: *mut i64) -> i64 { return unsafe { *s }; }

fn body(k: i64, s: *mut i64) -> i64 {
    let r: bool = mk(2i64, s) == {
        if k > 0i64 { return 5i64; }
        mk(3i64, s)
    };
    if r { return 0i64; }
    return 1i64;
}
fn real_main() -> i32 {
    let mut q: i64 = 0i64;
    let s: *mut i64 = &mut q;
    let r: i64 = body(1i64, s);
    let got: i64 = rd(s);
    unsafe { printf(c"r=%ld seq=%ld\n".as_ptr(), r, got); }
    if r != 5i64 { return 2i32; }
    if got != 26i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
