#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from return_array_lit_of_moved_locals_double_drop.logos
// SOUNDNESS QUEUE row return_array_lit_of_moved_locals_double_drop (tier 1). LOCALS MOVED INTO A RETURNED ARRAY LITERAL
// ARE DROPPED AGAIN AT FUNCTION EXIT.
//
// `let a = C{1}; let b = C{10}; return [a, b];` then the caller drops the array: Rust runs each destructor once, 11, exit 0.
// TODAY 22, exit 1 — both locals are also dropped when mkarr returns (a double drop of each; with a heap payload this is
// a double free). Not the autoref class: the array literal's elements are MOVES, and the return path's moved-set does not
// record them. Measured on base b54c1160ae8e4066 and on the 2026-09-14o landing: 22 both.
// Found 2026-09-14o-autoreffund by hand program x01 (while explaining c10's 12376). Legality by reading; no rustc binary.
// ROUND 2026-09-15f-consumeland (landing) DECLINED THE ARRAY-LITERAL HALF: DOORS IN SERIES. The first candidate b3b9ae03 (elements marked moved at SemaChecker::lower_arr_lit, TypeVar elements too, and lower_arr_fill_lit for N >= 1) closed this row, but LEAKED six legal programs that are right on base only by cancellation — `[a, b].len()`, `[a, b][1].v`, `for d in [a, b]`, `{ [a, b] }[0].v`, `&[a, b]`, `[a; 1][0].v` read n = 11 -> 0 (1 -> 0), rustc 11 each (pass fixtures bc_0915f_consumeland_hb_{k08,k09,k10,t11,t13,u07}_admit). The door upstream is row aggregate_literal_temp_place_base_never_dropped_run: an array / tuple literal temporary in a place position is never dropped.
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct C { v: i64, c: *mut i64 }
impl Drop for C { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
fn mkarr(p: *mut i64) -> [C; 2] {
    let a: C = C { v: 1i64, c: p };
    let b: C = C { v: 10i64, c: p };
    return [a, b];
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    {
        let arr: [C; 2] = mkarr(p);
        if arr[1].v != 10i64 { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"n=%ld\n".as_ptr(), got); }
    if got != 11i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
