#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from slice_pattern_arm_binding_extra_drops.logos
// SOUNDNESS QUEUE row slice_pattern_arm_binding_extra_drops (tier 1). A BY-VALUE ARRAY PATTERN IN A MATCH ARM WITH A `return`
// DESTROYS THE MOVED-OUT ELEMENTS AGAIN.
//
// `let arr = [D{2}, D{3}]; match arr { [z, b] => { return z.v + b.v; } }`: the arm moves both elements out; the return destroys
// b (3), z (2), and the outer local (1): Rust 321, exit 0. TODAY the sequence is 32231 (the two elements destroyed a second time
// as the array) on the base binary and on the 2026-09-15 shadowslot landing alike, exit 1. NOT the shadow fact: no name is
// shadowed (renamed control of hand program k30).
// Found 2026-09-15 by hand program k30ctl. Legality by reading; no rustc binary.
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { /* CONTROL: destructor records nothing */ } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64) -> i64 {
    let a: D = D { v: 1i64, c: p };
    let arr: [D; 2] = [D { v: 2i64, c: p }, D { v: 3i64, c: p }];
    match arr {
        [z, b] => { return z.v + b.v; }
    }
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    if g(p) != 5i64 { return 9i32; }
    if rd(p) != 321i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
