#!/usr/bin/env bash
# shared_ref_ub_lint.sh REPO_ROOT LEDGER
#
# THE RULING THAT LICENSES `noalias`+`readonly` ON A SHARED `&T` IS PROSE, AND
# PROSE THAT IS NOT MECHANIZED GETS RE-WRITTEN.
#
# Spec rule `type.shared-ref.write-through-derived-ub`: given `r: &T` with T
# Freeze, a write through a pointer DERIVED FROM `r` is undefined; a write
# through a pointer LOADED OUT OF the referent is not derived from `r` and stays
# defined (that clause is what keeps Rc/Arc sound). The emission that rule
# licenses is pinned by IR snapshots. THE ARGUMENT IS NOT.
#
# That is not a hypothetical gap. The bullet in mlir_gen_fn.cpp once read
# "DEFERRED … unsound until we can prove T has no interior mutability
# (UnsafeCell AND atomics, which are NOT UnsafeCell-wrapped in our stdlib)".
# Every clause of it was false by the next commit, and every gate stayed green
# for months while it sat there reading like a considered caveat. Re-writing it
# back to that costs nothing today unless something checks.
#
# ── WHAT THIS LINT ASSERTS: CLAIMS, NOT WORDING ──────────────────────────────
# A lint that greps for sentences is a spell-checker, and it goes red on every
# honest edit until someone deletes it. So this one checks four MECHANICAL
# facts, each of which has been false-by-drift or could silently become so:
#
#   FACT 1  THE GUARD. `llvm.readonly` is written in exactly ONE place in the
#           whole compiler, and that write sits INSIDE an `if (type_is_freeze(
#           …))` block. This is precisely the clause the DEFERRED comment got
#           wrong — it claimed there was no predicate — so it is checked
#           against the CODE, not against the comment describing the code.
#
#   FACT 2  THE RULE ID IS THE JOINT. `type.shared-ref.write-through-derived-ub`
#           must appear BOTH at the emission site and in the rule corpus. That
#           is what stops the code, the comment and the spec from drifting into
#           three different stories: rename or delete either end and this fails.
#
#   FACT 3  THE UNSAFECELL DISCIPLINE. The soundness argument rests entirely on
#           "every interior-mutability primitive in the tree is UnsafeCell-
#           wrapped, so type_is_freeze sees it". Every `pub struct Atomic*` must
#           actually contain an UnsafeCell, and the count is held against the
#           ledger in BOTH directions. THIS IS THE CLAUSE THAT SILENTLY WENT
#           FALSE LAST TIME ("atomics are NOT UnsafeCell-wrapped in our
#           stdlib"), which is why it is a census and not a sentence.
#
#   FACT 4  THE LAUNDERING CENSUS. `&x as *const T as *mut T` is the shape the
#           rule declares undefined. It is legal, it is used, and each use is
#           sound for a REASON THAT IS NOT VISIBLE IN THE TEXT (a `&mut self`
#           receiver, a by-value self, a non-Freeze pointee, a read-only use, or
#           the loaded-pointer exception). No lint can decide that. What a lint
#           CAN do is make a new site impossible to add unreviewed: the per-file
#           census is held against the ledger in both directions, so the number
#           moves only by someone editing it deliberately.
#
# ── WHAT THIS LINT DOES NOT COVER, stated so the ledger is not over-read ─────
#   * It does NOT detect the prohibited shape in USER code. Nothing does; a real
#     detector has to model the provenance chain, because the loaded-pointer
#     exception is the common and correct stdlib shape and a syntactic matcher
#     would fire on every Rc/Arc/Weak method in the tree. That is an open fork,
#     not an oversight.
#   * FACT 2 checks the code and the rule CORPUS. It deliberately does NOT check
#     docs/spec/*.md: those are generated by a model workflow, the rule has not
#     been assembled into them yet, and asserting something false would make
#     this gate a liar on its first run.
#   * Only `//` comments are stripped. A match inside a /* … */ block counts as
#     live code — the safe direction (over-count, never under-count).
#
# ── AND IT PROVES ITS OWN INSTRUMENT, in the same run ────────────────────────
# Every fact above is re-measured through the SAME readers on PLANTED inputs
# whose answer is known. Whatever blinds the real measurement blinds the canary,
# because it is the same measurement. A lint that cannot fail is the original
# defect one level up.
set -u

ROOT=${1:?usage: shared_ref_ub_lint.sh <repo root> <ledger>}
LEDGER=${2:?usage: shared_ref_ub_lint.sh <repo root> <ledger>}

RULE_ID='type.shared-ref.write-through-derived-ub'
EMIT_SRC="$ROOT/src/compiler/mlir_gen_fn.cpp"
CORPUS="$ROOT/tools/spec-extract/rules/codegen/mlir_gen_fn/logos.json"
ATOMIC_SRC="$ROOT/stdlib/lang/atomic/atomic.logos"

TMPD=$(mktemp -d)
trap 'rm -rf "$TMPD"' EXIT

fail=0
note() { echo "FAIL: $*"; fail=1; }
broken() { echo "GATE BROKEN: $*"; exit 4; }

# ── READERS ──────────────────────────────────────────────────────────────────
# Every one of these is used BOTH on the tree and on a planted canary. They are
# the only place that reads source, on purpose.

strip_comments() { sed 's://.*::' "$1"; }

# FACT 1 reader. Prints one of: OK | NO-SITE | MULTI-SITE | UNGUARDED.
#
# ⚠ WHITESPACE-NORMALISED, NOT LINE-BASED. Asserting "the guard is 2 lines
# above" would go red on a reformat, and a lint that cries wolf on innocent
# edits gets deleted — which is the failure mode this whole file exists to
# prevent. The CLAIM is containment, so that is what is measured: the readonly
# write must occur after an `if (type_is_freeze(` with no closing brace between
# them, i.e. still inside that block.
guard_state() {
    local src="$1" flat n_ro
    flat=$(strip_comments "$src" | tr '\n' ' ' | tr -s ' ')
    n_ro=$(printf '%s' "$flat" | grep -o '"llvm\.readonly"' | grep -c .)
    if [ "$n_ro" -eq 0 ]; then echo NO-SITE; return; fi
    if [ "$n_ro" -gt 1 ]; then echo MULTI-SITE; return; fi
    # Text between the LAST `if (type_is_freeze(` and the readonly write.
    local between
    between=$(printf '%s' "$flat" \
        | sed 's/.*if (type_is_freeze(/@@@/' \
        | sed 's/"llvm\.readonly".*//')
    case "$between" in
        @@@*) ;;                       # a guard was found before the write
        *) echo UNGUARDED; return ;;
    esac
    case "$between" in
        *"}"*) echo UNGUARDED; return ;;  # block closed before the write
    esac
    echo OK
}

# FACT 3 reader. Prints `<StructName> <yes|no>` per `pub struct Atomic*`,
# sorted — `yes` iff an UnsafeCell appears in that struct's declaration body.
atomic_census() {
    local src="$1"
    strip_comments "$src" | awk '
        /^pub struct Atomic/ {
            name = $3; sub(/[<{].*/, "", name);
            body = $0; depth = gsub(/{/, "{", $0) - gsub(/}/, "}", $0);
            while (depth > 0 && (getline line) > 0) {
                body = body line;
                depth += gsub(/{/, "{", line) - gsub(/}/, "}", line);
            }
            print name, (body ~ /UnsafeCell/ ? "yes" : "no");
        }' | sort
}

# FACT 4 reader. Prints `<repo-relative path>\t<count>` for every stdlib file
# holding at least one const->mut laundering, sorted. Comments stripped, so a
# site that DOCUMENTS the shape is not counted as one — otherwise the incentive
# becomes "document less", and this very rule is the most documented thing in
# the tree.
LAUNDER_RE='as \*const [^;]* as \*mut '
launder_count_file() { strip_comments "$1" | grep -cE "$LAUNDER_RE" || true; }
launder_census() {
    local dir="$1" f n
    while IFS= read -r f; do
        n=$(launder_count_file "$f")
        [ "$n" -gt 0 ] && printf '%s\t%s\n' "${f#"$ROOT"/}" "$n"
    done < <(find "$dir" -name '*.logos' -type f | sort)
}

# ── SELF-CANARIES: the instrument, on inputs whose answer is known ───────────
# These run FIRST. If the readers are dead, this file must report ITSELF broken
# rather than report the tree clean.

# C1 — the guard reader must SEE a guarded site.
cat > "$TMPD/c1_ok.cpp" <<'EOF'
void f() {
    if (type_is_freeze(pt.pointee())) {
        f.setArgAttr(arg, "llvm.noalias", unit);
        f.setArgAttr(arg, "llvm.readonly", unit);
    }
}
EOF
[ "$(guard_state "$TMPD/c1_ok.cpp")" = OK ] || \
    broken "the guard reader cannot recognise a correctly guarded emission.
  It returned '$(guard_state "$TMPD/c1_ok.cpp")' for a planted site that IS
  guarded, so its verdict on the real tree means nothing."

# C2 — and it must FLAG the same site with the guard removed. This is the exact
# regression the DEFERRED comment described: an emission with no predicate.
cat > "$TMPD/c2_unguarded.cpp" <<'EOF'
void f() {
    {
        f.setArgAttr(arg, "llvm.noalias", unit);
        f.setArgAttr(arg, "llvm.readonly", unit);
    }
}
EOF
[ "$(guard_state "$TMPD/c2_unguarded.cpp")" = UNGUARDED ] || \
    broken "the guard reader did NOT flag an UNGUARDED readonly emission
  (got '$(guard_state "$TMPD/c2_unguarded.cpp")'). It would pass a compiler that
  puts noalias+readonly on every shared &T, which is the unsoundness this
  whole rule exists to exclude."

# C3 — a readonly write that escapes the block must be flagged too, or
# "containment" is not what is being measured.
cat > "$TMPD/c3_escaped.cpp" <<'EOF'
void f() {
    if (type_is_freeze(pt.pointee())) {
        f.setArgAttr(arg, "llvm.noalias", unit);
    }
    f.setArgAttr(arg, "llvm.readonly", unit);
}
EOF
[ "$(guard_state "$TMPD/c3_escaped.cpp")" = UNGUARDED ] || \
    broken "the guard reader accepted a readonly write that sits AFTER the
  guard block closed (got '$(guard_state "$TMPD/c3_escaped.cpp")'). It is
  matching proximity, not containment."

# C4 — COMMENTS ARE NOT CODE, and this tree is the reason. mlir_gen_fn.cpp
# quotes the old DEFERRED wording verbatim in its anti-regression note, so a
# naive reader fires on the documentation of the defect as though it were the
# defect. The lint must survive its own subject matter.
cat > "$TMPD/c4_comment.cpp" <<'EOF'
void f() {
    // once we wrote f.setArgAttr(arg, "llvm.readonly", unit); with no guard
    // at all, and nothing noticed.
    if (type_is_freeze(pt.pointee())) {
        f.setArgAttr(arg, "llvm.readonly", unit);
    }
}
EOF
[ "$(guard_state "$TMPD/c4_comment.cpp")" = OK ] || \
    broken "the guard reader counts COMMENTED-OUT emissions as real ones
  (got '$(guard_state "$TMPD/c4_comment.cpp")'). Every site that explains this
  class would read as a violation of it."

# C5 — the atomic census must FLAG a primitive that is not UnsafeCell-wrapped.
# This is the clause that went false silently last time.
cat > "$TMPD/c5_atomic.logos" <<'EOF'
pub struct AtomicGood {
    val: UnsafeCell<i64>,
}

pub struct AtomicBad {
    val: i64,
}
EOF
c5=$(atomic_census "$TMPD/c5_atomic.logos")
[ "$c5" = "$(printf 'AtomicBad no\nAtomicGood yes')" ] || \
    broken "the UnsafeCell census misread a planted pair. Expected
  'AtomicBad no' + 'AtomicGood yes', got:
$c5
  It cannot tell a wrapped primitive from an unwrapped one, so its verdict on
  stdlib/lang/atomic/atomic.logos is not a measurement."

# C6 — the laundering counter must see a real site and must NOT see a commented
# one, through the same counter used on the tree.
printf 'fn f() { let p = &x as *const T as *mut T; }\n' > "$TMPD/c6_live.logos"
[ "$(launder_count_file "$TMPD/c6_live.logos")" = 1 ] || \
    broken "the laundering counter does not see a planted \`as *const T as
  *mut T\`. The census below would read as a pass for any tree."
printf '// let p = &x as *const T as *mut T;\nfn f() { }\n' > "$TMPD/c6_cmt.logos"
[ "$(launder_count_file "$TMPD/c6_cmt.logos")" = 0 ] || \
    broken "the laundering counter counts COMMENTS as code."

# ── FACT 1: the guard ────────────────────────────────────────────────────────
[ -f "$EMIT_SRC" ] || broken "$EMIT_SRC does not exist."
gs=$(guard_state "$EMIT_SRC")
case "$gs" in
    OK) ;;
    NO-SITE)
        note "no \`llvm.readonly\` parameter attribute is written anywhere in
      $(basename "$EMIT_SRC"). Either the emission was removed — in which case
      rule $RULE_ID and its IR snapshots must go with it, deliberately — or this
      lint is now pointed at the wrong file." ;;
    MULTI-SITE)
        note "\`llvm.readonly\` is written in MORE THAN ONE place in
      $(basename "$EMIT_SRC"). The soundness argument covers exactly one site,
      the Freeze-gated one; a second site is unreviewed by construction." ;;
    UNGUARDED)
        note "the \`llvm.readonly\` parameter attribute is NOT inside an
      \`if (type_is_freeze(...))\` block.
      This is the original defect verbatim: a shared \`&T\` would be told to
      LLVM as never-written even when its pointee has interior mutability, so
      \`&Cell\`, \`&Mutex\`, \`&RwLock\` and every atomic become miscompilable.
      Rule $RULE_ID licenses the attribute ONLY for a Freeze pointee." ;;
    *) broken "guard_state returned an unknown verdict '$gs'." ;;
esac

# ── FACT 2: the rule id joins code and corpus ────────────────────────────────
grep -qF "$RULE_ID" "$EMIT_SRC" || note \
"the emission site does not name its rule.
      $(basename "$EMIT_SRC") must mention \`$RULE_ID\`, so that whoever edits
      these two setArgAttr lines is standing next to the rule that licenses
      them. Without the id the code and the spec are two unrelated documents."
if [ -f "$CORPUS" ]; then
    grep -qF "$RULE_ID" "$CORPUS" || note \
"the rule corpus does not contain \`$RULE_ID\`.
      The code cites a rule the specification does not define. Either the rule
      was renamed (update both ends) or it was dropped (then the attribute has
      no stated licence and must come out too)."
else
    note "the rule corpus $CORPUS is missing."
fi

# ── FACT 3 + FACT 4: the censuses, against the ledger, in BOTH directions ────
[ -f "$LEDGER" ] || broken "ledger $LEDGER does not exist."

got_atomic=$(atomic_census "$ATOMIC_SRC")
got_launder=$(launder_census "$ROOT/stdlib")
got=$(printf 'ATOMIC\n%s\nLAUNDER\n%s\n' "$got_atomic" "$got_launder")
want=$(grep -vE '^\s*(#|$)' "$LEDGER")

# An interior-mutability primitive that is NOT wrapped is a soundness fact, not
# a bookkeeping one — it is reported on its own terms even if the ledger were
# somehow edited to expect it.
unwrapped=$(printf '%s\n' "$got_atomic" | awk '$2 == "no" { print $1 }')
if [ -n "$unwrapped" ]; then
    note "these interior-mutability primitives are NOT UnsafeCell-wrapped:
$(printf '%s\n' "$unwrapped" | sed 's/^/        /')
      \`type_is_freeze\` recognises interior mutability ONLY by finding an
      UnsafeCell in the pointee's inline bytes. A primitive that mutates through
      \`&self\` without one is classified Freeze, earns noalias+readonly, and is
      miscompiled at -O1 and above. This is the exact claim the old DEFERRED
      comment made about our atomics, and it was false then; it must stay false."
fi

if [ "$got" != "$want" ]; then
    note "the UnsafeCell / laundering census does not match $(basename "$LEDGER")."
    echo
    echo "  A NEW laundering site is not automatically wrong — the rule permits"
    echo "  the shape and every existing site is sound for a reason the text does"
    echo "  not show (a \`&mut self\` receiver, a by-value self, a non-Freeze"
    echo "  pointee, a read-only use, or the loaded-pointer exception that keeps"
    echo "  Rc/Arc sound). It is wrong UNREVIEWED. Add the line and say which."
    echo "  A REMOVED site is red too, so the number can only move deliberately."
    echo
    diff <(printf '%s\n' "$want") <(printf '%s\n' "$got") \
        | sed 's/^</  ledger only: /; s/^>/  tree only:   /' \
        | grep -E 'ledger only|tree only'
fi

[ "$fail" -ne 0 ] && exit 1

n_atomic=$(printf '%s\n' "$got_atomic" | grep -c .)
n_launder_files=$(printf '%s\n' "$got_launder" | grep -c .)
n_launder=$(printf '%s\n' "$got_launder" | awk -F'\t' '{s+=$2} END {print s+0}')
echo "shared-ref-UB lint: guard held (readonly written once, inside the"
echo "  type_is_freeze block); rule $RULE_ID present in both the emission site"
echo "  and the rule corpus; $n_atomic interior-mutability primitives, all"
echo "  UnsafeCell-wrapped; $n_launder laundering site(s) across"
echo "  $n_launder_files file(s), matching the ledger. Six self-canaries live."
exit 0
