// Generated by peg_gen from logos.peg — DO NOT EDIT.
//
// AST node codes (`Code`) and TinyObjectMap field keys (`Key`).
// Edit the grammar's %fields / %nodes blocks instead, then rerun
// the generator; the build checks this file is not stale.

#pragma once

#include <stdint.h>

#include <logos/core/named_code.hpp>

namespace logos::compiler::ast {

using Key  = NamedCode<uint8_t>;
using Code = NamedCode<int32_t>;

// ── Field keys (TinyObjectMap slots 0..51) ────────────────────────────────
inline constexpr Key CODE{"CODE", 0};
inline constexpr Key NAME{"NAME", 1};
inline constexpr Key ITEMS{"ITEMS", 2};
inline constexpr Key TYPE{"TYPE", 3};
inline constexpr Key PARAMS{"PARAMS", 4};
inline constexpr Key BODY{"BODY", 5};
inline constexpr Key RET_TYPE{"RET_TYPE", 6};
inline constexpr Key VALUE{"VALUE", 7};
inline constexpr Key COND{"COND", 8};
inline constexpr Key THEN{"THEN", 9};
inline constexpr Key ELSE{"ELSE", 10};
inline constexpr Key OP{"OP", 11};
inline constexpr Key LHS{"LHS", 12};
inline constexpr Key RHS{"RHS", 13};
inline constexpr Key CALLEE{"CALLEE", 14};
inline constexpr Key ARGS{"ARGS", 15};
inline constexpr Key USES{"USES", 17};
inline constexpr Key QUAL_PARTS{"QUAL_PARTS", 17};  // T2-28: package-path segments (after RECEIVER) on a qualified CALL/GENERIC_CALL. Reuses USES slot — call nodes never carry module USES.
inline constexpr Key POINTEE{"POINTEE", 18};
inline constexpr Key MUTPTR{"MUTPTR", 19};
inline constexpr Key RECEIVER{"RECEIVER", 20};
inline constexpr Key FIELD{"FIELD", 21};
inline constexpr Key FIELDS{"FIELDS", 22};
inline constexpr Key SIZE{"SIZE", 23};
inline constexpr Key SRC_LINE{"SRC_LINE", 24};
inline constexpr Key IS_MUT{"IS_MUT", 25};
inline constexpr Key INCLUSIVE{"INCLUSIVE", 26};
inline constexpr Key TYPE_PARAMS{"TYPE_PARAMS", 27};
inline constexpr Key PARENT{"PARENT", 28};
inline constexpr Key IS_AUTO{"IS_AUTO", 29};
inline constexpr Key IS_VARARG{"IS_VARARG", 30};
inline constexpr Key ITER{"ITER", 31};
inline constexpr Key IS_VARIADIC{"IS_VARIADIC", 32};
inline constexpr Key IS_PUB{"IS_PUB", 33};
inline constexpr Key PAT{"PAT", 34};
inline constexpr Key GUARD{"GUARD", 35};
inline constexpr Key EXPR{"EXPR", 36};
inline constexpr Key NAMES{"NAMES", 37};
inline constexpr Key WHERE{"WHERE", 38};
inline constexpr Key IS_CONST{"IS_CONST", 39};
inline constexpr Key LIFETIME{"LIFETIME", 40};
inline constexpr Key IMPL_TYPE_PARAMS{"IMPL_TYPE_PARAMS", 41};
inline constexpr Key IS_UNSAFE{"IS_UNSAFE", 42};
inline constexpr Key INDEX{"INDEX", 43};
inline constexpr Key IS_MOVE{"IS_MOVE", 44};
inline constexpr Key IS_REF{"IS_REF", 45};
inline constexpr Key BASE{"BASE", 46};
inline constexpr Key LABEL{"LABEL", 47};
inline constexpr Key SUPERS{"SUPERS", 48};
inline constexpr Key LO_NEG{"LO_NEG", 49};
inline constexpr Key HI_NEG{"HI_NEG", 50};
inline constexpr Key KEY{"KEY", 51};  // map key in WRIT_ENTRY
inline constexpr Key CODE_EXPR{"CODE_EXPR", 6};  // ADR 0011: `code(expr)` clause sub-node on SCHEMA_DEF/SCHEMA_ENUM_DEF (NAME="code", VALUE=expr). Reuses RET_TYPE slot — schemas have no return type. (AST TinyObjectMap keys are 0..51; 52 is out of range.)
inline constexpr Key IS_NEGATIVE{"IS_NEGATIVE", 43};  // negative impl marker (impl !Trait for X {}); reuses INDEX slot — IMPL_BLOCK never has INDEX
inline constexpr Key HRTB_BINDERS{"HRTB_BINDERS", 41};  // `for<'a, 'b>` binder list on a TRAIT_BOUND (reuses IMPL_TYPE_PARAMS slot — trait bounds never carry impl-type-params). Value is a sub-node with ITEMS=[LIFETIME_PARAM...].
inline constexpr Key RELAXED{"RELAXED", 39};  // `?Trait` relaxed-bound marker on TRAIT_BOUND (Phase 1: only `?Sized` valid). Reuses IS_CONST slot — trait_bound never carries IS_CONST.
inline constexpr Key PATH{"PATH", 22};  // sub-node carrying ITEMS=[str,...] for N-deep chain field write (reuses FIELDS slot — chain stmts never carry struct field defs)
inline constexpr Key NAME_VAR{"NAME_VAR", 38};  // antiquot var name for `#ident` placeholder inside quote_*! body (reuses WHERE slot — STRUCT/ENUM/FN never have a where_clause AND a NAME_VAR simultaneously: NAME_VAR exists only inside quote_*! bodies, where where_clause is parsed separately)
inline constexpr Key IS_OPTIONAL{"IS_OPTIONAL", 25};  // `use #pkg?;` optional-import marker inside quote_*! body: if the substituted package ident is EMPTY at splice time the whole use is DROPPED (else resolved normally). Reuses IS_MUT slot — a USE never carries IS_MUT.
inline constexpr Key META{"META", 16};  // meta @{...} block on struct/datatype/trait declarations (slot 16; reuses PATH_PARTS slot, mutually exclusive node types)
inline constexpr Key REL_KW{"REL_KW", 20};  // ADR 0016: contextual lead IDENT of a rel_def inside a mapping item (sema validates text == "rel"; reuses RECEIVER slot — REL_DEF never has a receiver)
inline constexpr Key RAW_TEXT{"RAW_TEXT", 7};  // raw source text captured from a balanced delim group on FN_MACRO_CALL (reuses VALUE slot — fn-macro nodes never carry a literal payload). Balanced-brace capture (RAW_GROUP_*) additionally honours two escapes in the raw body so LITERAL braces don't break balance: (a) a BACKSLASH before `{`/`}`/`` ` ``/`\` passes that char through WITHOUT counting it (the backslash SURVIVES into the captured text — the handler de-escapes); (b) a BACKTICK-delimited region is skipped whole (no brace counting inside). Both additive: well-formed bodies are unaffected + captured byte-identically.
inline constexpr Key DOC{"DOC", 50};  // doc-comment text on item-level decls (reuses HI_NEG slot — PAT_RANGE never appears at item level)
inline constexpr Key TYPE_NAME{"TYPE_NAME", 3};  // CP-cm-02: enum-type name in USE_VARIANTS (`use pkg.Path.Type.{V1,…}`). Reuses TYPE slot — USE never carries a type AST node.
inline constexpr Key VARIANTS{"VARIANTS", 22};  // CP-cm-02: array of variant-name sub-nodes (each with NAME field) in USE_VARIANTS. Reuses FIELDS slot — USE never carries struct fields.
inline constexpr Key VIS{"VIS", 10};  // §4 module system: visibility sub-node on item decls (FN/STRUCT/ENUM/TRAIT/CONST/…) from the `pub_vis` rule. NAME="module" → `pub(module)` (module-linkage); absent NAME → plain `pub`. Reuses ELSE slot — item decls never carry an else-branch.

// ── Node type discriminants (the CODE field's value) ──────────────────────
inline constexpr Code MODULE{"MODULE", 1};
inline constexpr Code PACKAGE{"PACKAGE", 2};
inline constexpr Code USE{"USE", 3};
inline constexpr Code FN{"FN", 10};
inline constexpr Code EXTERN_FN{"EXTERN_FN", 11};
inline constexpr Code PARAM{"PARAM", 12};
inline constexpr Code BLOCK{"BLOCK", 20};
inline constexpr Code LET{"LET", 21};
inline constexpr Code RETURN{"RETURN", 22};
inline constexpr Code IF{"IF", 23};
inline constexpr Code EXPR_STMT{"EXPR_STMT", 24};
inline constexpr Code CALL{"CALL", 30};
inline constexpr Code BINOP{"BINOP", 31};
inline constexpr Code VAR_REF{"VAR_REF", 32};
inline constexpr Code LIT_INT{"LIT_INT", 33};
inline constexpr Code LIT_BOOL{"LIT_BOOL", 34};
inline constexpr Code LIT_STR{"LIT_STR", 35};
inline constexpr Code TYPE_REF{"TYPE_REF", 40};
inline constexpr Code PTR_TYPE{"PTR_TYPE", 41};
inline constexpr Code STRUCT{"STRUCT", 50};
inline constexpr Code FIELD_DEF{"FIELD_DEF", 51};
inline constexpr Code FIELD_INIT{"FIELD_INIT", 52};
inline constexpr Code STRUCT_LIT{"STRUCT_LIT", 53};
inline constexpr Code FIELD_READ{"FIELD_READ", 54};
inline constexpr Code FIELD_WRITE{"FIELD_WRITE", 55};
inline constexpr Code METHOD_CALL{"METHOD_CALL", 56};
inline constexpr Code ASSIGN{"ASSIGN", 57};
inline constexpr Code WHILE{"WHILE", 58};
inline constexpr Code DEREF{"DEREF", 59};
inline constexpr Code PAREN_EXPR{"PAREN_EXPR", 60};
inline constexpr Code UNARY{"UNARY", 61};
inline constexpr Code INDEX_READ{"INDEX_READ", 62};
inline constexpr Code INDEX_WRITE{"INDEX_WRITE", 63};
inline constexpr Code ARR_TYPE{"ARR_TYPE", 64};
inline constexpr Code ARR_LIT{"ARR_LIT", 65};
inline constexpr Code BREAK{"BREAK", 66};
inline constexpr Code CONTINUE{"CONTINUE", 67};
inline constexpr Code LOOP{"LOOP", 68};
inline constexpr Code CAST{"CAST", 69};
inline constexpr Code FOR{"FOR", 70};
inline constexpr Code CONST_DEF{"CONST_DEF", 71};
inline constexpr Code TYPE_ALIAS{"TYPE_ALIAS", 72};
inline constexpr Code ENUM{"ENUM", 80};
inline constexpr Code VARIANT_DEF{"VARIANT_DEF", 81};
inline constexpr Code MATCH{"MATCH", 82};
inline constexpr Code MATCH_ARM{"MATCH_ARM", 83};
inline constexpr Code PAT_VARIANT{"PAT_VARIANT", 84};
inline constexpr Code PAT_WILD{"PAT_WILD", 85};
inline constexpr Code ENUM_LIT{"ENUM_LIT", 86};
inline constexpr Code PAT_INT{"PAT_INT", 87};
inline constexpr Code PAT_BOOL{"PAT_BOOL", 88};
inline constexpr Code TRAIT_BOUND{"TRAIT_BOUND", 89};
inline constexpr Code TYPE_PARAM{"TYPE_PARAM", 90};
inline constexpr Code GENERIC_CALL{"GENERIC_CALL", 91};
inline constexpr Code GENERIC_INST{"GENERIC_INST", 92};
inline constexpr Code ABSTRACT_FN{"ABSTRACT_FN", 96};
inline constexpr Code STATIC_FN{"STATIC_FN", 97};
inline constexpr Code STATIC_CALL{"STATIC_CALL", 98};
inline constexpr Code FOR_EACH{"FOR_EACH", 99};
inline constexpr Code TUPLE_TYPE{"TUPLE_TYPE", 100};
inline constexpr Code TUPLE_LIT{"TUPLE_LIT", 101};
inline constexpr Code TUPLE_INDEX{"TUPLE_INDEX", 102};
inline constexpr Code ENUM_LIT_DATA{"ENUM_LIT_DATA", 104};
inline constexpr Code PAT_VARIANT_DATA{"PAT_VARIANT_DATA", 105};
inline constexpr Code TRAIT_DEF{"TRAIT_DEF", 106};
inline constexpr Code IMPL_BLOCK{"IMPL_BLOCK", 107};
inline constexpr Code CLOSURE_EXPR{"CLOSURE_EXPR", 109};
inline constexpr Code SLICE_TYPE{"SLICE_TYPE", 111};
inline constexpr Code RANGE_EXPR{"RANGE_EXPR", 112};
inline constexpr Code FIELD_INDEX_WRITE{"FIELD_INDEX_WRITE", 113};
inline constexpr Code ADDR_OF_MUT{"ADDR_OF_MUT", 114};
inline constexpr Code DEREF_WRITE{"DEREF_WRITE", 115};
inline constexpr Code IMPL_TYPE{"IMPL_TYPE", 116};
inline constexpr Code PACK_EXPAND{"PACK_EXPAND", 117};
inline constexpr Code DYN_TYPE{"DYN_TYPE", 118};
inline constexpr Code ASSOC_TYPE_DEF{"ASSOC_TYPE_DEF", 119};
inline constexpr Code ASSOC_TYPE_IMPL{"ASSOC_TYPE_IMPL", 120};
inline constexpr Code ASSOC_TYPE_REF{"ASSOC_TYPE_REF", 121};
inline constexpr Code TRY_EXPR{"TRY_EXPR", 122};
inline constexpr Code LET_DESTRUCT{"LET_DESTRUCT", 123};
inline constexpr Code WHERE_CLAUSE{"WHERE_CLAUSE", 124};
inline constexpr Code CLOSURE_TYPE{"CLOSURE_TYPE", 125};
inline constexpr Code COMPOUND_ASSIGN{"COMPOUND_ASSIGN", 126};
inline constexpr Code ARR_FILL_LIT{"ARR_FILL_LIT", 127};
inline constexpr Code DEREF_FIELD_WRITE{"DEREF_FIELD_WRITE", 128};
inline constexpr Code REF_TYPE{"REF_TYPE", 129};
inline constexpr Code MUT_REF_TYPE{"MUT_REF_TYPE", 130};
inline constexpr Code LIFETIME_PARAM{"LIFETIME_PARAM", 131};
inline constexpr Code UNSAFE_BLOCK{"UNSAFE_BLOCK", 132};
inline constexpr Code CONST_PARAM{"CONST_PARAM", 133};
inline constexpr Code TUPLE_FIELD_WRITE{"TUPLE_FIELD_WRITE", 134};
inline constexpr Code LIT_FLOAT{"LIT_FLOAT", 135};
inline constexpr Code FIELD_COMPOUND_ASSIGN{"FIELD_COMPOUND_ASSIGN", 136};  // s.field op= expr
inline constexpr Code INDEX_COMPOUND_ASSIGN{"INDEX_COMPOUND_ASSIGN", 137};  // arr[i] op= expr
inline constexpr Code PAT_NEG_INT{"PAT_NEG_INT", 138};  // negative integer literal in pattern: -42
inline constexpr Code PAT_OR{"PAT_OR", 139};  // OR pattern: pat | pat
inline constexpr Code FIELD_SHORTHAND{"FIELD_SHORTHAND", 140};  // struct field shorthand: Point { x, y }
inline constexpr Code LET_ELSE{"LET_ELSE", 141};  // let Pat = expr else { block };
inline constexpr Code LABELED_LOOP{"LABELED_LOOP", 142};  // 'label: loop/for/while { }
inline constexpr Code PAT_TUPLE{"PAT_TUPLE", 143};  // tuple pattern: (a, b, c) =>
inline constexpr Code FN_PTR_TYPE{"FN_PTR_TYPE", 144};  // fn(T) -> R — bare function pointer type
inline constexpr Code DEREF_FIELD_COMPOUND_ASSIGN{"DEREF_FIELD_COMPOUND_ASSIGN", 145};  // (*ptr).field op= expr
inline constexpr Code TUPLE_FIELD_COMPOUND_ASSIGN{"TUPLE_FIELD_COMPOUND_ASSIGN", 146};  // var.N op= expr
inline constexpr Code FIELD_INDEX_COMPOUND_ASSIGN{"FIELD_INDEX_COMPOUND_ASSIGN", 147};  // s.field[i] op= expr
inline constexpr Code DATATYPE{"DATATYPE", 148};  // Writ datatype definition (C POD layout)
inline constexpr Code PAT_UNIT{"PAT_UNIT", 149};  // () unit pattern in match arms
inline constexpr Code ANNOTATION{"ANNOTATION", 150};  // #[name], #[name = val], #[name(args)]
inline constexpr Code TAGGED_TYPE{"TAGGED_TYPE", 151};  // &tagged<TS> Trait — tag-dispatched thin pointer
inline constexpr Code ASSOC_CONST_DEF{"ASSOC_CONST_DEF", 152};  // const NAME: T;       in trait
inline constexpr Code ASSOC_CONST_IMPL{"ASSOC_CONST_IMPL", 153};  // const NAME: T = expr; in impl
inline constexpr Code PAT_STRUCT{"PAT_STRUCT", 154};  // Point { x, y } struct pattern
inline constexpr Code PAT_SLICE{"PAT_SLICE", 155};  // [a, b] or [first, .., last] slice pattern
inline constexpr Code PAT_RANGE{"PAT_RANGE", 156};  // 0..=9 inclusive range pattern
inline constexpr Code PAT_AT{"PAT_AT", 157};  // n @ sub_pat binding
inline constexpr Code PAT_REF{"PAT_REF", 158};  // &pat or &mut pat reference pattern
inline constexpr Code PAT_FIELD{"PAT_FIELD", 159};  // field binding in struct pattern
inline constexpr Code PAT_REST{"PAT_REST", 160};  // .. rest in struct/slice pattern
inline constexpr Code CHAIN_FIELD_WRITE{"CHAIN_FIELD_WRITE", 161};  // a.b.c = val
inline constexpr Code CHAIN_FIELD_COMPOUND_ASSIGN{"CHAIN_FIELD_COMPOUND_ASSIGN", 162};  // a.b.c op= val
inline constexpr Code WRIT_MAP{"WRIT_MAP", 163};  // @{k:v,...} or inner {k:v,...} Writ map literal
inline constexpr Code WRIT_ARRAY{"WRIT_ARRAY", 164};  // @[v,...] or inner [v,...] Writ array literal
inline constexpr Code WRIT_STR{"WRIT_STR", 165};  // string value in Writ literal
inline constexpr Code WRIT_INT{"WRIT_INT", 166};  // integer value in Writ literal
inline constexpr Code WRIT_FLOAT{"WRIT_FLOAT", 167};  // float value in Writ literal
inline constexpr Code WRIT_BOOL{"WRIT_BOOL", 168};  // bool value in Writ literal
inline constexpr Code WRIT_NULL{"WRIT_NULL", 169};  // null value in Writ literal
inline constexpr Code WRIT_ENTRY{"WRIT_ENTRY", 170};  // key:val pair in Writ map
inline constexpr Code WRIT_TYPED_ARRAY{"WRIT_TYPED_ARRAY", 171};  // @<ElemType>[v,...] — typed dense array literal
inline constexpr Code WRIT_NEG_INT{"WRIT_NEG_INT", 172};  // negative integer: @-42 or inner -42 in array/map
inline constexpr Code WRIT_TYPED_MAP{"WRIT_TYPED_MAP", 173};  // @<K,V>{...} — typed map literal
inline constexpr Code WRIT_CAP_IDENT{"WRIT_CAP_IDENT", 174};  // $x — capture identifier; NAME = var name
inline constexpr Code WRIT_CAP_EXPR{"WRIT_CAP_EXPR", 175};  // ${expr} — capture expression; VALUE = expr
inline constexpr Code WRIT_ARR_TYPE{"WRIT_ARR_TYPE", 176};  // <ElemType>[] type expression; TYPE = elem name
inline constexpr Code WRIT_MAP_TYPE{"WRIT_MAP_TYPE", 177};  // <K,V>{} type expression; TYPE = key, RET_TYPE = val
inline constexpr Code LIST_COMP{"LIST_COMP", 178};  // [elem for x in iter (if guard)?]; VALUE=elem, NAME=var, ITER=iter, GUARD?=pred
inline constexpr Code MAP_COMP{"MAP_COMP", 179};  // {k:v for x in iter (if guard)?}; KEY=k, VALUE=v, NAME=var, ITER=iter, GUARD?=pred
inline constexpr Code WRIT_LIST_COMP{"WRIT_LIST_COMP", 180};  // @[elem for x in iter (if guard)?]; VALUE=elem, NAME=var, ITER=iter, GUARD?=pred
inline constexpr Code WRIT_MAP_COMP{"WRIT_MAP_COMP", 181};  // @{k:v for x in iter (if guard)?}; KEY=k, VALUE=v, NAME=var, ITER=iter, GUARD?=pred
inline constexpr Code PAT_WRIT_NULL{"PAT_WRIT_NULL", 182};  // @null pattern
inline constexpr Code PAT_WRIT_BOOL{"PAT_WRIT_BOOL", 183};  // @true / @false pattern; VALUE
inline constexpr Code PAT_WRIT_INT{"PAT_WRIT_INT", 184};  // @<int> or @-<int> pattern; VALUE, IS_NEG
inline constexpr Code PAT_WRIT_STR{"PAT_WRIT_STR", 185};  // @"..." pattern; VALUE = string literal
inline constexpr Code PAT_WRIT_MAP{"PAT_WRIT_MAP", 186};  // @{k: pat, ...} pattern; ITEMS = entries
inline constexpr Code PAT_WRIT_ARR{"PAT_WRIT_ARR", 187};  // @[pat, ...] pattern; ITEMS = sub-patterns
inline constexpr Code PAT_WRIT_MAP_ENTRY{"PAT_WRIT_MAP_ENTRY", 188};  // entry: KEY = string key, VALUE = sub-pattern
inline constexpr Code PAT_WRIT_TYPED_ARR{"PAT_WRIT_TYPED_ARR", 189};  // @<T>[..] typed-array type check; TYPE
inline constexpr Code PAT_WRIT_TYPED_MAP{"PAT_WRIT_TYPED_MAP", 190};  // @<K,V>{..} typed-map type check; TYPE, RET_TYPE?
inline constexpr Code TYPEOF_TYPE{"TYPEOF_TYPE", 191};  // typeof(expr) type-position — compile-time type of expr; VALUE = expr AST
inline constexpr Code ANNOT_KV{"ANNOT_KV", 192};  // annotation named arg: NAME=key, VALUE=literal
inline constexpr Code ANNOT_POS{"ANNOT_POS", 193};  // annotation positional arg: VALUE=literal
inline constexpr Code ANNOT_ARR{"ANNOT_ARR", 194};  // annotation array literal: ITEMS=literals
inline constexpr Code META_BLOCK{"META_BLOCK", 195};  // meta @{...} block; VALUE=writ_lit node
inline constexpr Code GENOS_DEF{"GENOS_DEF", 196};  // genos declaration (trait with is_genos=true)
inline constexpr Code BLOCK_STMT{"BLOCK_STMT", 197};  // bare scoping block { stmts... }; BODY = block
inline constexpr Code METACALL{"METACALL", 198};  // metacall <call_expr>; VALUE = inner call AST
inline constexpr Code TEMPLATE_DECL{"TEMPLATE_DECL", 199};  // `template <decl>` — declaration-as-data; VALUE = wrapped item AST
inline constexpr Code QUOTE_ITEM{"QUOTE_ITEM", 200};  // quote_item! { item* } — typed AST literal; ITEMS = array of item nodes
inline constexpr Code QUOTE_EXPR{"QUOTE_EXPR", 201};  // quote_expr! { expr } — typed AST literal; VALUE = expr node (root carries schema_type_code)
inline constexpr Code REPEAT_GROUP{"REPEAT_GROUP", 202};  // #(body)sep* inside quote_*! body; VALUE=body expr, OP=sep code (0=none, 1=comma, 2=&&)
inline constexpr Code SIZEOF_PACK{"SIZEOF_PACK", 203};  // sizeof...(T) — value-position expression yielding pack length as u64; NAME = pack ident
inline constexpr Code QUOTE_TY{"QUOTE_TY", 204};  // quote_ty! { type } — typed Type literal; TYPE = inner type AST
inline constexpr Code ANTIQUOT_TYPE{"ANTIQUOT_TYPE", 205};  // $ident in a type position; NAME = ident of a Type-valued binding (only legal inside quote_ty!)
inline constexpr Code ANTIQUOT_PACK{"ANTIQUOT_PACK", 206};  // $ident... in a type-arg list; NAME = ident of an Array<Type> binding (only legal inside quote_ty!)
inline constexpr Code ASSOC_EQ_BIND{"ASSOC_EQ_BIND", 207};  // Name = Type clause inside trait bound `<...>`; NAME = assoc-type name; TYPE = rhs type AST
inline constexpr Code INSTANTIATE_DECL{"INSTANTIATE_DECL", 208};  // `instantiate Foo<T>;` — pre-instantiation root pin; TYPE = target type, IS_PUB? = lib-site re-export marker
inline constexpr Code METACALL_ITEM{"METACALL_ITEM", 209};  // `metacall <call_expr>;` at module-item position; VALUE = inner call AST. Driver runs the JIT'd callee returning QuoteItemBlob and splices its emitted items via `logos_emit_item_blob_subst`; node is marked consumed after splice.
inline constexpr Code METACALL_ITEM_DONE{"METACALL_ITEM_DONE", 210};  // Set by the driver after a METACALL_ITEM has been invoked; sema item-dispatch silently skips. Never parsed.
inline constexpr Code WRIT_TYPE_LIT{"WRIT_TYPE_LIT", 211};  // Component-metaprog slice 1: `<type:T>` inside @-literal. NAME = bare type identifier (slice 1: IDENT only). Sema embeds it as a first-class Writ Type value.
inline constexpr Code LIT_WSTATIC{"LIT_WSTATIC", 212};  // WritStatic literal at type-arg position: Foo::<@{...}>. VALUE = nested writ_lit AST. Sema lowers to ConstVar(WritStatic, hash) with byte-hash identity.
inline constexpr Code CFG_SLOT_TYPE{"CFG_SLOT_TYPE", 213};  // Type-position `<type:CFG.SLOT>`: extract the type stored at top-level slot SLOT of WritStatic CFG (a const-generic param or type alias). NAME = CFG ident, KEY = slot ident. Mono resolves to the slot's `<type:T>` value when CFG becomes concrete.
inline constexpr Code GENERIC_REF{"GENERIC_REF", 214};  // `IDENT::<TARGS>` at expression position; CALLEE = ident, TYPE_PARAMS = type_arg_list.
inline constexpr Code PAT_FLOAT{"PAT_FLOAT", 215};  // float-literal pattern (Sprint 4.2 — B-pt-06; rejected at sema, but parses cleanly).
inline constexpr Code PAT_BYTES{"PAT_BYTES", 216};  // byte-string-literal pattern (B-pt-03; reserved, lexer support pending).
inline constexpr Code LET_PAT{"LET_PAT", 217};  // `let <pattern> = expr;` — irrefutable destructure beyond simple ident/tuple. Sema checks refutability and lowers via match.
inline constexpr Code DOUBLE_REF_TYPE{"DOUBLE_REF_TYPE", 218};  // `&&T` (Sprint 6.2 — B-ty-07; resolved by sema as nested REF_TYPE).
inline constexpr Code DOUBLE_REF_MUT_TYPE{"DOUBLE_REF_MUT_TYPE", 219};  // `&&mut T` (B-ty-07; resolved as REF_TYPE wrapping MUT_REF_TYPE).
inline constexpr Code DEREF_COMPOUND{"DEREF_COMPOUND", 220};  // `*p op= val;` — compound assign through bare deref (B-st-04). Sema lowers to deref_write of *p = *p OP val.
inline constexpr Code CHAINED_CMP{"CHAINED_CMP", 221};  // `a < b < c` (2+ comparators in a row). Sema rejects with "chained comparisons not supported; use `a < b && b < c`" (B-ex-08).
inline constexpr Code PAREN_TYPE{"PAREN_TYPE", 222};  // `(T)` — paren-wrapped type expression (B-ty-09). Sema unwraps to inner; structurally same as T.
inline constexpr Code TAIL_EXPR{"TAIL_EXPR", 223};  // `expr` (no SEMI) at stmt position; sema synthesizes implicit `return expr` for non-void fns (B-fn-06).
inline constexpr Code LIT_CHAR{"LIT_CHAR", 224};  // `'X'` Unicode scalar literal. VALUE = original char-lit text including quotes; sema decodes.
inline constexpr Code FN_MACRO_CALL{"FN_MACRO_CALL", 225};  // `name!(args)` / `name![args]` — function-style macro. CALLEE = ident, ARGS = expr-list. Sema resolves CALLEE against #[fn_macro] fns; arg ASTs become ExprBlobs.
inline constexpr Code FN_MACRO_CALL_ITEM{"FN_MACRO_CALL_ITEM", 226};  // `name!{...}` at module item position. Same shape as FN_MACRO_CALL but routes through metacall_item-style splice (callee returns ItemList / QuoteItemBlob).
inline constexpr Code FN_MACRO_CALL_ITEM_DONE{"FN_MACRO_CALL_ITEM_DONE", 227};  // set by driver after item-macro splice; sema skips.
inline constexpr Code PAT_CHAR{"PAT_CHAR", 228};  // char-literal pattern (`'A'` in match arm). VALUE = original CHAR_LIT text; sema decodes to u32 scalar.
inline constexpr Code PAT_CHAR_RANGE{"PAT_CHAR_RANGE", 229};  // char-range pattern (`'a' ..= 'z'`). LHS / RHS = original CHAR_LIT text for each endpoint.
inline constexpr Code INVOKE_EXPR{"INVOKE_EXPR", 230};  // `(expr)(args)` — IIFE / expression-as-callee (P4-pm-16). RECEIVER = callee expression, ARGS = arg-list. Sema routes through closure-call / fn-ptr-call.
inline constexpr Code BREAK_EXPR{"BREAK_EXPR", 231};  // `break` in expression position (P3-pg-04). Rust-style `!`/Never; sema lowers as a SBreak stmt + Error-typed sentinel expression so surrounding type-checks accept.
inline constexpr Code CONTINUE_EXPR{"CONTINUE_EXPR", 232};  // `continue` in expression position (P3-pg-04). Same shape as BREAK_EXPR.
inline constexpr Code RETURN_EXPR{"RETURN_EXPR", 233};  // `return` in expression position (P3-pg-04). Same shape — bare form only (no value).
inline constexpr Code LIT_BYTES{"LIT_BYTES", 234};  // P4-pm-07: `b"..."` byte-string literal at expression position. VALUE = raw token text including the `b"…"` quotes; sema decodes escapes and lowers to an `[u8; N]` array literal.
inline constexpr Code NESTED_FN{"NESTED_FN", 235};  // `fn name(params) [-> T] { body }` at stmt position. Sema lifts the body to a top-level free fn under a gensym'd name and binds the local name as a fn-ptr let. NAME, PARAMS, RET_TYPE?, BODY.
inline constexpr Code UNSIZED_SLICE_TYPE{"UNSIZED_SLICE_TYPE", 236};  // Phase 1B: bare `[T]` — unsized slice type. TYPE = element. Sema produces Kind::UnsizedSlice; cannot appear by value, only behind `&` / `*const` / `*mut` (canonicalised back to SLICE_TYPE / Kind::Slice at resolve time) or as a `T: ?Sized` substitution.
inline constexpr Code DOC_LINE_LIT{"DOC_LINE_LIT", 237};  // `/// text` outer doc-comment line. VALUE = raw token text (still includes the leading `///`). Sema-collect strips the prefix, joins consecutive DOC_LINE_LIT siblings, and attaches the joined string to the next real item via the DOC AST slot.
inline constexpr Code INNER_DOC_LIT{"INNER_DOC_LIT", 238};  // `//! text` inner doc-comment line (module-level summary). VALUE = raw token text including the leading `//!`. Sema-collect strips the prefix and accumulates into LProgram.module_inner_doc.
inline constexpr Code DOC_BLOCK_LIT{"DOC_BLOCK_LIT", 239};  // `/** ... */` outer block doc-comment. VALUE = raw token text including the `/**` envelope and trailing `*/`. Sema strips the envelope + per-line leading `*` indent and joins with `\n` into pending_doc_, mirroring DOC_LINE_LIT accumulation.
inline constexpr Code INNER_DOC_BLOCK_LIT{"INNER_DOC_BLOCK_LIT", 240};  // `/*! ... */` inner block doc-comment (module-level summary, block form). VALUE = raw token text; sema accumulates into module_inner_doc_ like INNER_DOC_LIT.
inline constexpr Code USE_VARIANTS{"USE_VARIANTS", 241};  // CP-cm-02 + GR-gp-02: `use pkg.Path.X.{V1, V2, …};`. Same shape as USE but with extra TYPE_NAME (last dotted segment, either enum Type when uppercase or pkg sub-name when lowercase) and VARIANTS (list of bare-ident TomVs each holding a NAME). Sema disambiguates by TYPE_NAME's first-character case: uppercase → enum-variant bare-name shorthand; lowercase → grouped sub-package import (`use std.lang.{option, result};`).
inline constexpr Code INNER_ANNOTATION{"INNER_ANNOTATION", 242};  // Three-layer split Phase 3.2: `#![name]` / `#![name(args)]` / `#![name=val]` — file/module-level inner attribute. Currently used only for `#![no_implicit_prelude]`. Payload shape identical to ANNOTATION; differing CODE lets sema pick out module-level attrs from per-item attrs.
inline constexpr Code DESTRUCTURE_ASSIGN{"DESTRUCTURE_ASSIGN", 243};  // G149-7 (RFC 2909): destructuring assignment `(a,b)=e` / `[a,b]=e` / `S{a,b}=e` into EXISTING places. OP=0 tuple (NAMES=pat_binding_list), 1 array (NAMES), 2 struct (NAME=struct, FIELDS=pat_field_list); VALUE=rhs. Sema desugars to `let __da=rhs;` + per-place assigns.
inline constexpr Code PAT_STR{"PAT_STR", 245};  // G172-1: string-literal pattern `match s { "foo" => … }`. VALUE = string source. Sema lowers to a `str_eq` guard.
inline constexpr Code PLACE_ASSIGN{"PLACE_ASSIGN", 244};  // G163-2: general place write — a postfix-chain lvalue (`a[i][j]`, `(*p).0`, `m.f[i].g`, deep mixes) on the assignment LHS that the specialized write productions don't cover. RECEIVER = the place (a postfix read-expr: IndexRead/FieldRead/TupleIndex/Deref chain), VALUE = rhs. Sema lowers to `deref_write(&mut <place>, rhs)`.
inline constexpr Code AUTO_TRAIT_BOUND{"AUTO_TRAIT_BOUND", 246};  // logos-core 2.4(c): `+ Send` / `+ Sync` etc. on a trait object (`&dyn Trait + Send`). NAME = bound's identifier. Collected into the dyn_type's ITEMS array alongside type-args; resolve_type filters by CODE to bucket bounds vs args. Folded into TraitObject TypeRef via const_val bits for the dyn+Auto enforce at unsize coercion.
inline constexpr Code AUTO_LIFE_BOUND{"AUTO_LIFE_BOUND", 247};  // logos-core 2.4(c): `+ 'a` lifetime bound on a trait object (`&dyn Trait + 'a`). NAME = lifetime label. Same collection path as AUTO_TRAIT_BOUND; sema currently logs but does not enforce lifetime-bounds at unsize sites (depends on §2.1 region_infer wiring).
inline constexpr Code ANNOT_CALL{"ANNOT_CALL", 248};  // logos-core §6.8: nested combinator inside an annotation arg list, e.g. `#[cfg(all(unix, target_arch = "x86_64"))]`. NAME = head ident (`all` / `any` / `not` / generic future combinator); ARGS = nested annot_args list (each entry is another ANNOT_CALL / ANNOT_KV / bare-NAME).
inline constexpr Code EXTERN_BLOCK{"EXTERN_BLOCK", 249};  // logos-core §6.7: `extern "ABI" { extern_fn_def* }` block form. VALUE = ABI string literal (omitted ≡ default Logos-internal); ITEMS = array of EXTERN_FN nodes — each individually carries VALUE=block-ABI or its own per-fn override. sema_collect splices the block's items into the module-level item stream with the block's ABI applied as a default to children that don't have their own.
inline constexpr Code IF_LET_CHAIN{"IF_LET_CHAIN", 250};  // logos-core §6.4: `if let P1 = e1 && let P2 = e2 && cond { THEN } else { ELSE }`. ITEMS = list of LET_CHAIN_LET / LET_CHAIN_COND segs joined by `&&`. THEN/ELSE branches as in IF. Sema desugars to a flat sequence of refutable binds + cond checks; chain falls to ELSE on any failure.
inline constexpr Code LET_CHAIN_LET{"LET_CHAIN_LET", 251};  // §6.4: let-bind seg of IF_LET_CHAIN. PAT = pattern, VALUE = scrutinee. Refutable.
inline constexpr Code LET_CHAIN_COND{"LET_CHAIN_COND", 252};  // §6.4: bool-cond seg of IF_LET_CHAIN. VALUE = bool expression. Falls to ELSE on false.
inline constexpr Code UNION_DEF{"UNION_DEF", 253};  // logos-core §6.1: `union NAME { f1: T1, f2: T2, … }` item. NAME = union type name; FIELDS = field array (same shape as STRUCT). Sema treats unions as Struct-shaped types with `is_union=true`; layout = max-of-fields aligned to max-alignment; field access requires `unsafe` block.
inline constexpr Code STATIC_DEF{"STATIC_DEF", 254};  // logos-core §6.2: `static [mut] NAME: T = expr;` — true global storage (one llvm.mlir.global per item; stable address, `&STATIC` identity). NAME/TYPE/VALUE same shape as CONST_DEF; IS_MUT only on the `mut` form (reads/writes require `unsafe`, Rust `items.static.mut.safety`); no VALUE ⇒ extern-block declaration (external linkage). IS_PUB optional. Sema: module_statics_ (all) + module_static_muts_ (mut only).
inline constexpr Code OFFSET_OF{"OFFSET_OF", 255};  // `offset_of!(Type, field)` — compile-time byte offset of `field` within `Type` (Rust's `core::mem::offset_of!`). TYPE = type_ref AST, NAME = field ident. Sema resolves the type, walks the ABI layout to the field, emits an i64 const.
inline constexpr Code SCHEMA_DEF{"SCHEMA_DEF", 256};  // ADR 0011: `schema S : code(expr)? { name: type = key, … }` — typed view over a map-like Writ object (backing = WMap<Wu6,WAny> TOM). NAME = schema name; FIELDS = array of SCHEMA_FIELD_DEF; CODE_EXPR = optional `code(expr)` clause sub-node (NAME="code", VALUE=expr). Sema registers it as a Struct with one synthetic field `m: *const WMap<Wu6,WAny>` + is_schema=true; declared fields live only in the key/type table.
inline constexpr Code SCHEMA_FIELD_DEF{"SCHEMA_FIELD_DEF", 257};  // ADR 0011: one schema field binding. NAME = field name; TYPE = field type; VALUE = optional key const-expr (absent ⇒ positional index). IS_PUB optional.
inline constexpr Code SCHEMA_ENUM_DEF{"SCHEMA_ENUM_DEF", 258};  // ADR 0011: `schema enum E : category(expr)? { V(S), … }` — closed union over schemas, discriminated by the pointee's schema_type_code. NAME = enum name; FIELDS = array of VARIANT_DEF (each NAME=variant, TYPE=concrete schema); CODE_EXPR? = optional `category(expr)` clause.
inline constexpr Code MAPPING_DEF{"MAPPING_DEF", 259};  // ADR 0016: `mapping M(g: &Writ, …) { pub? rel r(col: ty, …) { <rules> } … }` — named, typed rule-module over a source shape. NAME = mapping name; PARAMS = source/scalar param list (PARAM array, same shape as fn params); FIELDS = array of REL_DEF; IS_PUB/VIS as usual. Sema registers a zero-field marker struct (is_mapping=true) + per-rel signatures; rel bodies compile through the deem pipeline.
inline constexpr Code REL_DEF{"REL_DEF", 260};  // ADR 0016: one rel member of a mapping item. REL_KW = contextual lead ident (must be "rel"); NAME = rel name; PARAMS = typed column list (PARAM array); RAW_TEXT = rule body captured token-level (balanced braces); IS_PUB optional.
inline constexpr Code CONTAINER_DEF{"CONTAINER_DEF", 266};  // ADR 0020 wave-0: `pub? container C<T…> for BackingTy { kind k; entry { col: ty, … } measure m; measure m(col); … }` — a Memoria container declaration. REL_KW = contextual lead ident (must be "container" — a keyword would break the common identifier, e.g. logos.lang.writ.container); NAME; TYPE_PARAMS? (syntactic generics incl. bounds); TYPE = backing type_ref (the wave-0 `for <Type>` pragmatic binding); FIELDS = array of CONTAINER_CLAUSE; IS_PUB/VIS as usual.
inline constexpr Code CONTAINER_CLAUSE{"CONTAINER_CLAUSE", 268};  // ADR 0020 wave-0: one clause of a container item. REL_KW = contextual lead ident ("kind"|"entry"|"measure", validated in sema); NAME = word (`vector`, `count`, `max`); PARAMS = entry column list (PARAM array, reused param_list); VALUE = measure arg ident (`key` in `max(key)`).
inline constexpr Code WRIT_BLOB{"WRIT_BLOB", 261};  // pre-serialised Writ static blob (driver splice from a metacall WritStatic return); VALUE = raw blob bytes (Varchar)
inline constexpr Code MAPPING_DEF_DONE{"MAPPING_DEF_DONE", 265};  // a CONSUMED mapping item (its thunk ran; per-rel fns emitted). Distinct from FN_MACRO_CALL_ITEM_DONE so a consumer compiling against the ARCHIVE can still recognize the node and register the mapping (name/params/rels/bodies all survive the flip — only CODE changes) for cross-module fusion.
inline constexpr Code REL_SIG{"REL_SIG", 262};  // ADR 0016 §6: a `rel` member of a TRAIT — `rel edge(parent: i64, …);`. REL_KW = contextual lead ident (must be "rel"); NAME = rel name; PARAMS = typed column list (PARAM array). Declares the relational vocabulary a source-trait carries.
inline constexpr Code REL_BIND{"REL_BIND", 263};  // ADR 0016 §6: a `rel` member of an IMPL — `rel edge = writ_graph_edges;`. REL_KW = lead ident; NAME = rel name; VALUE = the materializer fn ident (fn(&T) -> Vec<RowTuple>). Binds one trait rel to its native materializer for the impl'd type.
inline constexpr Code DEEM_DEF{"DEEM_DEF", 264};  // ADR 0016: `pub? deem q(g: &Writ, …) { <query> }` — a deem QUERY as a language item (the item form of `resource q = deem!(…){…}`; same handler, same seam). DEEM_KW = contextual lead ident (must be "deem" — a keyword would break `use logos.std.deem`); NAME; PARAMS = real param list; RAW_TEXT = the query body (balanced braces); IS_PUB/VIS as usual.
inline constexpr Code CONTAINER_DEF_DONE{"CONTAINER_DEF_DONE", 267};  // ADR 0020 wave-0: a CONSUMED container item. Same convention as MAPPING_DEF_DONE — only CODE flips (driver); NAME/TYPE_PARAMS/TYPE/FIELDS survive so a consumer compiling against the ARCHIVE re-registers the declaration (cross-module Canon reasoning).

namespace mod {
    inline constexpr Key PATH_PARTS{"PATH_PARTS", 16};  // array of sub-nodes (one per component after NAME)
    inline constexpr Key FROM_MODULE{"FROM_MODULE", 5};  // reuses BODY — USE/MODULE never carry a body
    inline constexpr Key FROM_KW{"FROM_KW", 9};  // reuses THEN — USE/MODULE never carry a then-branch
} // namespace mod

namespace variant {
    inline constexpr Key IS_STRUCT_SHAPE{"IS_STRUCT_SHAPE", 47};  // P4-pm-01: struct-shape variant marker
} // namespace variant

} // namespace logos::compiler::ast
