#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from i07_generic_arr_then_tuple.logos
fn f<T>(x: T) -> (T, i64) {
    let a: [T; 1] = [x];
    return (x, 1i64);
}
fn real_main() -> i32 {
    let q: (i64, i64) = f(7i64);
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
