#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from k06_ifexpr_arr_arms_else.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct W { x: D, y: D, z: i64 }
impl Add for D {
    type Output = D;  // TWIN: Logos operator traits carry no Output type
    fn add(self, o: D) -> D {
        return D { v: 100i64, c: self.c };
    }
}
impl Neg for D {
    type Output = D;  // TWIN: Logos operator traits carry no Output type
    fn neg(self) -> D {
        return D { v: 1000i64, c: self.c };
    }
}
impl AddAssign for D {
    fn add_assign(&mut self, o: D) {
        self.v = self.v + 0i64;
    }
}
fn eat(d: D) -> i64 { return d.v; }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64) -> i64 {
    let a: D = D { v: 1i64, c: p };
    let b: D = D { v: 10i64, c: p };
    let c: bool = rd(p) != 0i64;
    let arr: [D; 1] = if c { [a] } else { [b] };
    return arr[0].v;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    if got != 11i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
