#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from t06_for_over_arrlit_rvalues.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct W { x: D, y: D, z: i64 }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64) -> i64 {
    let mut s: i64 = 0i64;
    for d in [D { v: 1i64, c: p }, D { v: 10i64, c: p }] {
        s = s + d.v;
    }
    return s;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
