#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from v02_generic_struct_concrete_add.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
struct S<X> { d: D, x: X }
impl Add for S<i64> {
    type Output = i64;  // TWIN: Logos operator traits carry no Output type
    fn add(self, o: S<i64>) -> i64 {  // TWIN: receiver spelling fixed by hand (l2rs regex ate the type args)
        return self.x + o.x;
    }
}
fn g(p: *mut i64) -> i64 {
    let a: S<i64> = S { d: D { v: 1i64, c: p }, x: 2i64 };
    let b: S<i64> = S { d: D { v: 10i64, c: p }, x: 3i64 };
    let s: i64 = a + b;
    return s;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
