#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from v04_self_add_in_method.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
impl Sub for D {
    type Output = D;  // TWIN: Logos operator traits carry no Output type
    fn sub(self, o: D) -> D {
        return D { v: 100i64, c: self.c };
    }
}
impl D {
    fn twice(self, o: D) -> i64 {
        let m: D = self - o;
        return m.v;
    }
}
fn g(p: *mut i64) -> i64 {
    let a: D = D { v: 1i64, c: p };
    let b: D = D { v: 10i64, c: p };
    return a.twice(b);
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
