#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from v07_op_in_guard.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
impl Add for D {
    type Output = i64;  // TWIN: Logos operator traits carry no Output type
    fn add(self, o: D) -> i64 {
        return self.v + o.v;
    }
}
fn g(p: *mut i64) -> i64 {
    let a: D = D { v: 1i64, c: p };
    let b: D = D { v: 10i64, c: p };
    let k: i64 = rd(p);
    let s: i64 = match k {
        0 if a + b > 5i64 => 1i64,
        _ => 2i64,
    };
    return s;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
