#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from w04_match_arrlit_locals_full.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64) -> i64 {
    let a: D = D { v: 1i64, c: p };
    let b: D = D { v: 10i64, c: p };
    let k: i64 = match [a, b] {
        [x, y] => x.v + y.v,
    };
    return k;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
