#!/usr/bin/env bash
# `lforge build --dump-metacall` end-to-end. Builds a fixture using
# #[derive_clone] and asserts that .lforge/<profile>/dump/<target>/
# contains a per-metacall directory whose post_quote.logos has the
# expected `impl Clone for ...` shape.
#
# Args: $1 = lforge, $2 = logosc, $3 = LOGOS_LIB_DIR.

set -euo pipefail

LFORGE="${1:?lforge path}"
LOGOSC="${2:?logosc path}"
LIB="${3:?LOGOS_LIB_DIR}"

PROJ=$(mktemp -d)
trap 'rm -rf "$PROJ"' EXIT

mkdir -p "$PROJ/src"
cat > "$PROJ/lforge.hermes" <<'EOF'
{
    name:    "dump_smoke",
    version: "0.1.0",
    src:     "src",
    entry:   "main"
}
EOF
cat > "$PROJ/src/main.logos" <<'EOF'
package main;
use logos.std.compiler.metaprog;
use logos.lang.clone;
#[derive_clone]
struct Pair { a: i32, b: i32 }
#[derive_clone]
struct Trio { x: i32, y: i32, z: i32 }
unsafe fn main() -> i32 {
    let p: Pair = Pair { a: 11, b: 22 };
    let t: Trio = Trio { x: 1, y: 2, z: 3 };
    let q: Pair = p.clone();
    let u: Trio = t.clone();
    return q.a + u.z;
}
EOF
# Source layout (line-number-sensitive, do not reformat):
#   line 5 = struct Pair (derive_clone fires here)
#   line 7 = struct Trio (second derive_clone)

cd "$PROJ"

LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build "--dump-metacall=*" \
    > "$PROJ/build.log" 2>&1

DUMP_DIR=".lforge/debug/dump/dump_smoke"
if [ ! -d "$DUMP_DIR" ]; then
    echo "FAIL: dump dir $DUMP_DIR not created"
    cat "$PROJ/build.log"
    exit 1
fi

# Find the per-metacall subdir produced by the derive_clone hook.
matches=$(find "$DUMP_DIR" -mindepth 2 -name post_quote.logos)
if [ -z "$matches" ]; then
    echo "FAIL: no post_quote.logos under $DUMP_DIR"
    find "$DUMP_DIR" -type f
    exit 1
fi

# Pick the dir for Pair (line 5) — order from `find` isn't stable.
sample=$(grep -lE 'impl Clone for Pair' $matches | head -1)
if [ -z "$sample" ]; then
    echo "FAIL: no dump file matched 'impl Clone for Pair'"
    for m in $matches; do echo "--- $m ---"; cat "$m"; done
    exit 1
fi
if ! grep -q "Auto-generated by logosc --dump-metaprog" "$sample"; then
    echo "FAIL: dump missing header comment"
    cat "$sample"
    exit 1
fi
if ! grep -q "fn clone" "$sample"; then
    echo "FAIL: dump missing 'fn clone'"
    cat "$sample"
    exit 1
fi

# Per-metacall index lists the bare fn names defined here (Pair__clone).
idx_dir=$(dirname "$sample")
if [ ! -f "$idx_dir/post_mono_index.txt" ]; then
    echo "FAIL: post_mono_index.txt missing"
    ls "$idx_dir"
    exit 1
fi
if ! grep -q "^Pair$" "$idx_dir/post_mono_index.txt"; then
    echo "FAIL: post_mono_index.txt missing 'Pair' (impl receiver)"
    cat "$idx_dir/post_mono_index.txt"
    exit 1
fi
if ! grep -q "^clone$" "$idx_dir/post_mono_index.txt"; then
    echo "FAIL: post_mono_index.txt missing 'clone' (method)"
    cat "$idx_dir/post_mono_index.txt"
    exit 1
fi

# Global post-mono MLIR + post-mlirgen LLVM IR snapshots written once per
# logosc invocation; they should mention the post-mono mangled form of the
# Pair clone fn (mono inserts $G1$T markers between type and method).
if [ ! -f "$DUMP_DIR/_global_post_mono.mlir" ]; then
    echo "FAIL: _global_post_mono.mlir missing"
    exit 1
fi
if ! grep -q "main\.Pair.*clone" "$DUMP_DIR/_global_post_mono.mlir"; then
    echo "FAIL: _global_post_mono.mlir doesn't mention main.Pair…clone"
    exit 1
fi
if [ ! -f "$DUMP_DIR/_global_post_mlirgen.ll" ]; then
    echo "FAIL: _global_post_mlirgen.ll missing"
    exit 1
fi
if ! grep -q "main\.Pair.*clone" "$DUMP_DIR/_global_post_mlirgen.ll"; then
    echo "FAIL: _global_post_mlirgen.ll doesn't mention main.Pair…clone"
    exit 1
fi

# Selector filter: file:line picks one metacall site.
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" clean > /dev/null
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build "--dump-metacall=main.logos:5" > /dev/null 2>&1
sites=$(find "$DUMP_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
if [ "$sites" != "1" ]; then
    echo "FAIL: file:line filter expected 1 site, got $sites"
    find "$DUMP_DIR" -maxdepth 1 -type d
    exit 1
fi
if ! find "$DUMP_DIR" -mindepth 1 -maxdepth 1 -type d -name '*main_5' -print -quit | grep -q .; then
    echo "FAIL: file:line filter didn't pick the main:5 dir"
    find "$DUMP_DIR" -maxdepth 1 -type d
    exit 1
fi

# Selector that matches nothing → no per-metacall dirs (and no global
# IR dumps either, since per_metacall_dirs is empty).
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" clean > /dev/null
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build "--dump-metacall=no_such_callee" > /dev/null 2>&1
sites=$(find "$DUMP_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
if [ "$sites" != "0" ]; then
    echo "FAIL: no-match filter still produced sites: $sites"
    exit 1
fi

# Without the flag, no dump dir at all.
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" clean > /dev/null
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build > /dev/null 2>&1
if [ -d "$DUMP_DIR" ]; then
    echo "FAIL: dump dir created even without --dump-metacall"
    exit 1
fi

echo "OK"
