#!/usr/bin/env bash
# `lforge build --dump-metacall` end-to-end. Builds a fixture using
# #[derive_clone] and asserts that .lforge/<profile>/dump/<target>/
# contains a per-metacall directory whose post_quote.logos has the
# expected `impl Clone for ...` shape.
#
# Args: $1 = lforge, $2 = logosc, $3 = LOGOS_LIB_DIR.

set -euo pipefail

LFORGE="${1:?lforge path}"
LOGOSC="${2:?logosc path}"
LIB="${3:?LOGOS_LIB_DIR}"

PROJ=$(mktemp -d)
trap 'rm -rf "$PROJ"' EXIT

mkdir -p "$PROJ/src"
cat > "$PROJ/lforge.hermes" <<'EOF'
{
    name:    "dump_smoke",
    version: "0.1.0",
    src:     "src",
    entry:   "main"
}
EOF
cat > "$PROJ/src/main.logos" <<'EOF'
package main;

use std.compiler.metaprog;
use std.lang.clone;

#[derive_clone]
struct Pair { a: i32, b: i32 }

unsafe fn main() -> i32 {
    let p: Pair = Pair { a: 11, b: 22 };
    let q: Pair = p.clone();
    return q.a + q.b;
}
EOF

cd "$PROJ"

LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build "--dump-metacall=*" \
    > "$PROJ/build.log" 2>&1

DUMP_DIR=".lforge/debug/dump/dump_smoke"
if [ ! -d "$DUMP_DIR" ]; then
    echo "FAIL: dump dir $DUMP_DIR not created"
    cat "$PROJ/build.log"
    exit 1
fi

# Find the per-metacall subdir produced by the derive_clone hook.
matches=$(find "$DUMP_DIR" -mindepth 2 -name post_quote.logos)
if [ -z "$matches" ]; then
    echo "FAIL: no post_quote.logos under $DUMP_DIR"
    find "$DUMP_DIR" -type f
    exit 1
fi

# Pick any one and assert the expected shape: header comment, package
# decl, and an `impl Clone for Pair` block.
sample=$(echo "$matches" | head -1)
if ! grep -q "Auto-generated by logosc --dump-metaprog" "$sample"; then
    echo "FAIL: dump missing header comment"
    cat "$sample"
    exit 1
fi
if ! grep -q "impl Clone for Pair" "$sample"; then
    echo "FAIL: dump missing 'impl Clone for Pair'"
    cat "$sample"
    exit 1
fi
if ! grep -q "fn clone" "$sample"; then
    echo "FAIL: dump missing 'fn clone'"
    cat "$sample"
    exit 1
fi

# Without the flag, no dump dir.
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" clean > /dev/null
LOGOSC="$LOGOSC" LOGOS_LIB_DIR="$LIB" "$LFORGE" build > /dev/null 2>&1
if [ -d "$DUMP_DIR" ]; then
    echo "FAIL: dump dir created even without --dump-metacall"
    exit 1
fi

echo "OK"
