#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from box_field_move.logos
// SOUNDNESS QUEUE row box_field_move (tier 1). A partial move of a drop-carrying
// field out of a Box: legal Rust (Box is the one type with DerefMove). TODAY the
// moved String is freed twice — rc 134, valgrind 'Invalid free'. Repair = DerefMove
// lowering for a FIELD; the cheap refusal was declined (2026-09-04, 6ae8bf7bc).
struct Inner { s: String, n: i64 }
fn real_main() -> i32 {
    let bx: Box<Inner> = Box::new(Inner { s: String::from("abcdefghijklmnop"), n: 3i64 });
    let v: String = bx.s;
    if v.len() != 16 /* TWIN-CHANGE: String::len is usize in Rust (Logos i64); literal suffix dropped */ { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
