#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from closure_owned_dyn_capture.logos
// SOUNDNESS QUEUE row closure_owned_dyn_capture (tier 1). A move closure that OWNS
// a Box<dyn Tr>, returned as Box<dyn Fn() -> i64> and called after its defining fn
// returned. Rust: 59. TODAY the owned capture is dropped with f's scope, the call
// reads freed memory (valgrind 'Invalid read') and main returns 1. The half-mechanism
// clowndyn measured 1 -> 134 and was declined (2026-09-04, 6ae8bf7bc).
// `Box<dyn Fn() -> i64>` and CALLED AFTER the defining fn returned.
trait Tr { fn m(&self) -> i64; }
#[derive(Clone, Copy)] /* A16 variant */ struct S { v: i64 }
impl Tr for S {
    fn m(&self) -> i64 { return self.v; }
}
fn f(b: Box<dyn Tr>) -> Box<dyn Fn() -> i64> {
    return Box::new(move || { return b.m(); });
}
fn real_main() -> i32 {
    let g: Box<dyn Fn() -> i64> = f(Box::new(S { v: 59i64 }));
    let got: i64 = g();
    if got != 59i64 {
        return 1i32;
    }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
