#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from field_base_temp_built_before_sibling_run.logos
// SOUNDNESS QUEUE row field_base_temp_built_before_sibling_run (tier 1). A DROPPABLE TEMPORARY FIELD BASE IS BUILT BEFORE THE
// OPERANDS THAT PRECEDE IT.
//
// `side(s) + mk(2, s).v`: Rust runs side (1), builds the temporary (2), drops it at the end of the statement (6): 126, exit 0.
// TODAY 216, exit 1 — lower_field_read's SemaChecker::hoist_stmt_temp PREPENDS `let __rtmp = mk(2, s)` before the statement.
// NEIGHBOUR of the 2026-09-14o-autoreffund landing (the same prepend decision its order-preserving owner replaced at the
// operator sites), ROWED WITH REASON 3 (its own cost is measured non-zero): the strict extension `fieldinplace` (the base
// owned in place by autoref_operand and read through the reference) moves this program 216 -> 126 and REFUSES the legal
// `let s: String = mkp(p).name;` (a field moved out of a temporary) with E0507 — the base is now behind a reference.
// Found 2026-09-14o-autoreffund by hand program n01; condemning program n04. Legality by reading; no rustc binary.
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, s: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.s = *self.s * 10i64 + self.v + 4i64; } } }
impl D { fn get(&self) -> i64 { return self.v; } }
fn mk(v: i64, s: *mut i64) -> D {
    unsafe { *s = *s * 10i64 + v; }
    return D { v: v, s: s };
}
fn side(s: *mut i64) -> i64 {
    unsafe { *s = *s * 10i64 + 1i64; }
    return 1i64;
}
fn rd(s: *mut i64) -> i64 { return unsafe { *s }; }

fn real_main() -> i32 {
    let mut q: i64 = 0i64;
    let s: *mut i64 = &mut q;
    let k: i64 = side(s) + mk(2i64, s).v;
    let got: i64 = rd(s);
    unsafe { printf(c"k=%ld seq=%ld\n".as_ptr(), k, got); }
    if k != 3i64 { return 2i32; }
    if got != 126i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
