#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from generic_struct_impl_ref_eq_compares_addresses_run.logos
// SOUNDNESS QUEUE row generic_struct_impl_ref_eq_compares_addresses_run (tier 1). WRONG ANSWER AT RUN TIME. `ra == rb` over
// two `&W<i64>` where the only impl is generic (`impl<T: PartialEq> PartialEq for W<T>`) compares the ADDRESSES: exit 1. Rust: exit 0.
// The by-value control `a == b` is right: sema's struct lookup misses the generic impl and falls through, and mono_clone
// subst_expr's BinOp re-dispatch (Kind::Struct) calls `W$..__eq` after substitution. A REFERENCE pair is Kind::Ref there.
// NEIGHBOUR of ref_struct_eq_compares_addresses_run, ROWED WITH REASON 1 FOR THE SEMA ARM (the fact has no carrier there): sema's
// `refstruct` routes the pair, finds no impl (census refeq.sema.spair.noimpl 1) and falls through — the generic impl is only named
// after substitution. The mono-site arm `refmono` of round 2026-09-15a-refeq closes it (exit 0) AND closes
// ref_struct_eq_compares_addresses_run by itself — AND REASON 3 FOR THAT ARM (its own cost is measured non-zero): it REFUSES the
// legal pass fixture tests/imported/pass/where-clauses/where-clauses.logos ('func.call' op 'logos.lang.str.Splitter__eq' does not
// reference a valid function), because mono clones `impl<X> Equal for X where X: Eq` for a struct with no Eq impl — a door
// upstream (the unchecked `where` bound at instantiation) that a mono-site repair must open first.
// Battery e41. Measured on builds 854d99ae9a2e2fbd 43, b1a0431a68699a9c 43, build-land0913d sha256 8850a5acc469809f.
// 2026-09-15b-refeqland: ref_struct_eq_compares_addresses_run is CLOSED (pass/bc_refeqland_struct_ref_pair_calls_eq_admit) by the
// sema arm alone; this row still reads exit 1 on the landed binary (build-land0913d sha256 7251cacc8e20ec02), reason 1 unchanged.
// Legality by reading; no rustc binary.
#[derive(Clone, Copy)] /* A16 variant */ struct W<T> { x: T }
impl<T: PartialEq> PartialEq for W<T> {
    fn eq(&self, other: &W<T>) -> bool {
        return self.x == other.x;
    }
}
fn real_main() -> i32 {
    let a: W<i64> = W::<i64> { x: 5i64 };
    let b: W<i64> = W::<i64> { x: 5i64 };
    let ra: &W<i64> = &a;
    let rb: &W<i64> = &b;
    if ra == rb {
        return 0i32;
    }
    return 1i32;
}
fn main() { std::process::exit(real_main()); }
