#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from ref_pair_nonprim_tuple_eq_compares_addresses_run.logos
// SOUNDNESS QUEUE row ref_pair_nonprim_tuple_eq_compares_addresses_run (tier 1). WRONG ANSWER AT RUN TIME. `==` over two
// references to a tuple with a NON-PRIMITIVE element compares the ADDRESSES: PART 1 `&(S, i64)` (S: Eq) -> exit 1; PART 2
// `&(String, i64)` -> exit 2. Rust compares through the reference (`impl PartialEq<&B> for &A`): exit 0.
// The one part of ref_pair_aggregate_eq_compares_addresses_run that 2026-09-15b-refeqland did NOT close (PARTs 1-3 closed; see
// pass/bc_refeqland_aggregate_ref_pair_compares_values_admit). ROWED, REASON 3 — the arm that closes it has its own cost MEASURED
// NON-ZERO: passing the reference pair to the stdlib variadic `impl<A...> PartialEq for (A...)` (the priced refagg tuple half) makes the
// reference spelling behave exactly as the BY-VALUE spelling, and the by-value spelling is REFUSED on base for three element kinds
// that Rust accepts, so programs base compiled become refusals of legal programs:
//   enum element `&(Option<S>, i64)` / `&(Option<i64>, String)` / `&(Option<i64>, i64)` (battery g01 g05 g07; by value g01v g07v:
//     mlir_gen internal "`return` value lowered to no value" — row tuple_enum_elem_eq_variadic_impl_return_lost_refused)
//   array element `&(String, [i64; 2])` (g10; by value g10v: "'variadic__ne': type '[i64; 2]' does not implement trait 'Eq'")
//   Box element `&(Box<D>, i64)` (g15; by value g15v: "type 'Box<D>' does not implement trait 'Eq'")
// A guard excluding enum elements was built and REFUTED by g10 / g15 (an enumerated denylist of element kinds). Members that the
// routing moved to Rust's answer and that stay wrong here: battery e37 f26 g06 g09 g12 g13. Measured on build/ 854d99ae9a2e2fbd 43
// (base) and build-land0913d sha256 3e4a73c81b9cc7b6 (routing with the enum guard). Legality by reading; no rustc binary.
#[derive(Clone, Copy)] /* A16 variant */ struct S { v: i64 }
impl PartialEq for S {
    fn eq(&self, other: &S) -> bool {
        return self.v == other.v;
    }
}
fn real_main() -> i32 {
    let u1: (S, i64) = (S { v: 5i64 }, 6i64);
    let u2: (S, i64) = (S { v: 5i64 }, 6i64);
    let ru1: &(S, i64) = &u1;
    let ru2: &(S, i64) = &u2;
    if !(ru1 == ru2) { return 1i32; }
    let s1: (String, i64) = (String::from("ab"), 1i64);
    let s2: (String, i64) = (String::from("ab"), 1i64);
    let rs1: &(String, i64) = &s1;
    let rs2: &(String, i64) = &s2;
    if !(rs1 == rs2) { return 2i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
