#![allow(unused, dead_code, unused_mut, unused_variables, unused_assignments, unreachable_code, unused_unsafe)]
// TWIN: generated by l2rs.py from static_array_whole_borrow_reads_garbage.logos
// SOUNDNESS QUEUE row static_array_whole_borrow_reads_garbage (tier 1).
// `&ARR` of a `static ARR: [i64; 3]` indexes garbage: the whole-array borrow
// of a static does not address the global's elements (`ARR[2]` and `&ARR[2]`
// are right, `let s = &ARR; s[2]` and `g(&ARR)` read other memory, and the
// value differs run to run). Legal Rust; rustc exits 0.
static ARR: [i64; 3] = [5i64, 2i64, 7i64];
fn third(s: &[i64; 3]) -> i64 {
    return s[2];
}
fn real_main() -> i32 {
    let s = &ARR;
    if s[0] != 5i64 { return 1i32; }
    if third(&ARR) != 7i64 { return 2i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
