#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from array_len_builtin_discards_receiver_run.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn mkarr(p: *mut i64) -> [D; 2] {
    unsafe { *p = *p + 100i64; }
    return [D { v: 1i64, c: p }, D { v: 10i64, c: p }];
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    {
        let k: i64 = mkarr(p).len() as i64;  // TWIN: usize -> i64 (Logos .len() is i64, docs/DIVERGENCES.md)
        if k != 2i64 { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"n=%ld\n".as_ptr(), got); }
    if got != 111i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
