#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from extended_field_base_temp_dropped_at_let_end_run.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct W { x: D, y: D, z: i64 }
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let mut seen: i64 = -1i64;
    {
        let k: &D = &W { x: D { v: 1i64, c: p }, y: D { v: 10i64, c: p }, z: 3i64 }.y;
        seen = unsafe { *p };
        if k.v != 10i64 { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"seen=%ld n=%ld\n".as_ptr(), seen, got); }
    if got != 11i64 { return 2i32; }
    if seen != 0i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
