#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from fnptr_field_call_on_temporary_never_dropped_run.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct Q { f: fn(*mut i64) -> i64, d: D }
fn seven(p: *mut i64) -> i64 { return 7i64; }
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    {
        let k: i64 = (Q { f: seven, d: D { v: 1i64, c: p } }.f)(p);  // TWIN: a fn-pointer field call needs parens in Rust
        if k != 7i64 { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"n=%ld\n".as_ptr(), got); }
    if got != 1i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
