#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from nested_array_literal_index_initializer_lost_refused.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    {
        let k: i64 = [[D { v: 1i64, c: p }], [D { v: 10i64, c: p }]][1][0].v;
        if k != 10i64 { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(c"n=%ld\n".as_ptr(), got); }
    if got != 11i64 { return 1i32; }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
