// Generated by peg_gen — DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <string_view>
#include <logos/core/named_code.hpp>
#include <logos/hermes/view.hpp>

namespace logos::compiler {

// ── AST field keys (%fields) and node codes (%nodes) ─────────────────────
namespace logos_ast {
    using Key  = logos::NamedCode<uint8_t>;
    using Code = logos::NamedCode<int32_t>;

    // Field keys (TinyObjectMap slot indices)
    inline constexpr Key  CODE                 {"CODE", 0};
    inline constexpr Key  NAME                 {"NAME", 1};
    inline constexpr Key  ITEMS                {"ITEMS", 2};
    inline constexpr Key  TYPE                 {"TYPE", 3};
    inline constexpr Key  PARAMS               {"PARAMS", 4};
    inline constexpr Key  BODY                 {"BODY", 5};
    inline constexpr Key  RET_TYPE             {"RET_TYPE", 6};
    inline constexpr Key  VALUE                {"VALUE", 7};
    inline constexpr Key  COND                 {"COND", 8};
    inline constexpr Key  THEN                 {"THEN", 9};
    inline constexpr Key  ELSE                 {"ELSE", 10};
    inline constexpr Key  OP                   {"OP", 11};
    inline constexpr Key  LHS                  {"LHS", 12};
    inline constexpr Key  RHS                  {"RHS", 13};
    inline constexpr Key  CALLEE               {"CALLEE", 14};
    inline constexpr Key  ARGS                 {"ARGS", 15};
    inline constexpr Key  PATH                 {"PATH", 16};
    inline constexpr Key  USES                 {"USES", 17};
    inline constexpr Key  POINTEE              {"POINTEE", 18};
    inline constexpr Key  MUTPTR               {"MUTPTR", 19};
    inline constexpr Key  RECEIVER             {"RECEIVER", 20};
    inline constexpr Key  FIELD                {"FIELD", 21};
    inline constexpr Key  FIELDS               {"FIELDS", 22};
    inline constexpr Key  SIZE                 {"SIZE", 23};
    inline constexpr Key  SRC_LINE             {"SRC_LINE", 24};
    inline constexpr Key  IS_MUT               {"IS_MUT", 25};
    inline constexpr Key  INCLUSIVE            {"INCLUSIVE", 26};
    inline constexpr Key  TYPE_PARAMS          {"TYPE_PARAMS", 27};
    inline constexpr Key  PARENT               {"PARENT", 28};
    inline constexpr Key  IS_ABSTRACT          {"IS_ABSTRACT", 29};
    inline constexpr Key  IS_VARARG            {"IS_VARARG", 30};
    inline constexpr Key  ITER                 {"ITER", 31};
    inline constexpr Key  IS_VARIADIC          {"IS_VARIADIC", 32};
    inline constexpr Key  IS_PUB               {"IS_PUB", 33};
    inline constexpr Key  PAT                  {"PAT",    34};
    inline constexpr Key  GUARD                {"GUARD",  35};
    inline constexpr Key  EXPR                 {"EXPR",   36};
    inline constexpr Key  NAMES                {"NAMES",  37};

    // Node type discriminants
    inline constexpr Code MODULE               {"MODULE", 1};
    inline constexpr Code PACKAGE              {"PACKAGE", 2};
    inline constexpr Code USE                  {"USE", 3};
    inline constexpr Code FN                   {"FN", 10};
    inline constexpr Code EXTERN_FN            {"EXTERN_FN", 11};
    inline constexpr Code PARAM                {"PARAM", 12};
    inline constexpr Code BLOCK                {"BLOCK", 20};
    inline constexpr Code LET                  {"LET", 21};
    inline constexpr Code RETURN               {"RETURN", 22};
    inline constexpr Code IF                   {"IF", 23};
    inline constexpr Code EXPR_STMT            {"EXPR_STMT", 24};
    inline constexpr Code CALL                 {"CALL", 30};
    inline constexpr Code BINOP                {"BINOP", 31};
    inline constexpr Code VAR_REF              {"VAR_REF", 32};
    inline constexpr Code LIT_INT              {"LIT_INT", 33};
    inline constexpr Code LIT_BOOL             {"LIT_BOOL", 34};
    inline constexpr Code LIT_STR              {"LIT_STR", 35};
    inline constexpr Code TYPE_REF             {"TYPE_REF", 40};
    inline constexpr Code PTR_TYPE             {"PTR_TYPE", 41};
    inline constexpr Code STRUCT               {"STRUCT", 50};
    inline constexpr Code FIELD_DEF            {"FIELD_DEF", 51};
    inline constexpr Code FIELD_INIT           {"FIELD_INIT", 52};
    inline constexpr Code STRUCT_LIT           {"STRUCT_LIT", 53};
    inline constexpr Code FIELD_READ           {"FIELD_READ", 54};
    inline constexpr Code FIELD_WRITE          {"FIELD_WRITE", 55};
    inline constexpr Code METHOD_CALL          {"METHOD_CALL", 56};
    inline constexpr Code ASSIGN               {"ASSIGN", 57};
    inline constexpr Code WHILE                {"WHILE", 58};
    inline constexpr Code DEREF                {"DEREF", 59};
    inline constexpr Code PAREN_EXPR           {"PAREN_EXPR", 60};
    inline constexpr Code UNARY                {"UNARY", 61};
    inline constexpr Code INDEX_READ           {"INDEX_READ", 62};
    inline constexpr Code INDEX_WRITE          {"INDEX_WRITE", 63};
    inline constexpr Code ARR_TYPE             {"ARR_TYPE", 64};
    inline constexpr Code ARR_LIT              {"ARR_LIT", 65};
    inline constexpr Code BREAK                {"BREAK", 66};
    inline constexpr Code CONTINUE             {"CONTINUE", 67};
    inline constexpr Code LOOP                 {"LOOP", 68};
    inline constexpr Code CAST                 {"CAST", 69};
    inline constexpr Code FOR                  {"FOR", 70};
    inline constexpr Code CONST_DEF            {"CONST_DEF", 71};
    inline constexpr Code TYPE_ALIAS           {"TYPE_ALIAS", 72};
    inline constexpr Code ENUM                 {"ENUM", 80};
    inline constexpr Code VARIANT_DEF          {"VARIANT_DEF", 81};
    inline constexpr Code MATCH                {"MATCH", 82};
    inline constexpr Code MATCH_ARM            {"MATCH_ARM", 83};
    inline constexpr Code PAT_VARIANT          {"PAT_VARIANT", 84};
    inline constexpr Code PAT_WILD             {"PAT_WILD", 85};
    inline constexpr Code ENUM_LIT             {"ENUM_LIT", 86};
    inline constexpr Code PAT_INT              {"PAT_INT", 87};
    inline constexpr Code PAT_BOOL             {"PAT_BOOL", 88};
    inline constexpr Code TRAIT_BOUND          {"TRAIT_BOUND", 89};
    inline constexpr Code TYPE_PARAM           {"TYPE_PARAM", 90};
    inline constexpr Code GENERIC_CALL         {"GENERIC_CALL", 91};
    inline constexpr Code GENERIC_INST         {"GENERIC_INST", 92};
    inline constexpr Code CLASS                {"CLASS", 93};
    inline constexpr Code NEW_EXPR             {"NEW_EXPR", 94};
    inline constexpr Code DELETE_STMT          {"DELETE_STMT", 95};
    inline constexpr Code ABSTRACT_FN          {"ABSTRACT_FN", 96};
    inline constexpr Code STATIC_FN            {"STATIC_FN", 97};
    inline constexpr Code STATIC_CALL          {"STATIC_CALL", 98};
    inline constexpr Code FOR_EACH             {"FOR_EACH", 99};
    inline constexpr Code TUPLE_TYPE           {"TUPLE_TYPE", 100};
    inline constexpr Code TUPLE_LIT            {"TUPLE_LIT", 101};
    inline constexpr Code TUPLE_INDEX          {"TUPLE_INDEX", 102};
    inline constexpr Code ENUM_LIT_DATA        {"ENUM_LIT_DATA", 104};
    inline constexpr Code PAT_VARIANT_DATA     {"PAT_VARIANT_DATA", 105};
    inline constexpr Code TRAIT_DEF            {"TRAIT_DEF", 106};
    inline constexpr Code IMPL_BLOCK           {"IMPL_BLOCK", 107};
    inline constexpr Code CLOSURE_EXPR         {"CLOSURE_EXPR", 109};
    inline constexpr Code SLICE_TYPE           {"SLICE_TYPE", 111};
    inline constexpr Code RANGE_EXPR           {"RANGE_EXPR", 112};
    inline constexpr Code FIELD_INDEX_WRITE    {"FIELD_INDEX_WRITE", 113};
    inline constexpr Code ADDR_OF_MUT          {"ADDR_OF_MUT", 114};
    inline constexpr Code DEREF_WRITE          {"DEREF_WRITE", 115};
    inline constexpr Code IMPL_TYPE            {"IMPL_TYPE", 116};
    inline constexpr Code PACK_EXPAND          {"PACK_EXPAND", 117};
    inline constexpr Code DYN_TYPE             {"DYN_TYPE", 118};
    inline constexpr Code ASSOC_TYPE_DEF       {"ASSOC_TYPE_DEF", 119};
    inline constexpr Code ASSOC_TYPE_IMPL      {"ASSOC_TYPE_IMPL", 120};
    inline constexpr Code ASSOC_TYPE_REF       {"ASSOC_TYPE_REF", 121};
    inline constexpr Code TRY_EXPR             {"TRY_EXPR", 122};
    inline constexpr Code LET_DESTRUCT         {"LET_DESTRUCT", 123};

} // namespace logos_ast

// ── Token kinds (generated from %tokens) ────────────────────────────────
enum class TK_LOGOS : int {
    Eof = 0,
    KW_CONTINUE,   // "continue"
    KW_ABSTRACT,   // "abstract"
    KW_PACKAGE,   // "package"
    KW_EXTENDS,   // "extends"
    KW_STATIC,   // "static"
    KW_DELETE,   // "delete"
    KW_RETURN,   // "return"
    KW_EXTERN,   // "extern"
    KW_STRUCT,   // "struct"
    KW_MATCH,   // "match"
    KW_WHILE,   // "while"
    KW_BREAK,   // "break"
    KW_FALSE,   // "false"
    KW_TRAIT,   // "trait"
    KW_CONST,   // "const"
    KW_CLASS,   // "class"
    KW_TYPE,   // "type"
    KW_IMPL,   // "impl"
    KW_ENUM,   // "enum"
    KW_LOOP,   // "loop"
    KW_ELSE,   // "else"
    KW_TRUE,   // "true"
    KW_FOR,   // "for"
    KW_USE,   // "use"
    KW_MUT,   // "mut"
    KW_LET,   // "let"
    KW_DYN,   // "dyn"
    KW_PUB,   // "pub"
    KW_NEW,   // "new"
    KW_FN,   // "fn"
    KW_IF,   // "if"
    KW_IN,   // "in"
    KW_AS,   // "as"
    KW_WHERE,   // "where"
    LBRACE,   // "{"
    RBRACE,   // "}"
    LBRACKET,   // "["
    RBRACKET,   // "]"
    LPAREN,   // "("
    RPAREN,   // ")"
    COLON,   // ":"
    COMMA,   // ","
    SEMI,   // ";"
    ARROW,   // "->"
    DOT,   // "."
    STAR,   // "*"
    AMP,   // "&"
    AND,   // "&&"
    OR,   // "||"
    PIPE,   // "|"
    EQ,   // "=="
    NE,   // "!="
    LE,   // "<="
    GE,   // ">="
    DOTDOTDOT,   // "..."
    DOTDOTEQ,   // "..="
    DOTDOT,   // ".."
    LT,   // "<"
    GT,   // ">"
    PLUS,   // "+"
    MINUS,   // "-"
    SLASH,   // "/"
    PERCENT,   // "%"
    BANG,   // "!"
    QUESTION,   // "?"
    ASSIGN,   // "="
    FATARROW,   // "=>"
    COLONCOLON,   // "::"
    STRING,   // /"([^"\\]|\\.)*"/
    INTEGER,   // /[-]?[0-9]+/
    IDENT,   // /[a-zA-Z_][a-zA-Z0-9_]*/
};

// ── Parser ───────────────────────────────────────────────────────────────
class LogosParser {
public:
    explicit LogosParser(std::string_view source);

    // Entry points for exported rules.
    logos::hermes::HermesCtr parse_module();

    // Returns true when all input tokens have been consumed.
    bool at_eof() { return peek_token().kind == TK::Eof; }
    // Line number of the next unconsumed token (1-based).
    uint32_t next_line() { return peek_token().line; }
    // Text of the next unconsumed token.
    std::string_view next_text() { return peek_token().text; }

private:
    logos::hermes::AnyVal rule_module();
    logos::hermes::AnyVal rule_use_decl();
    logos::hermes::AnyVal rule_item();
    logos::hermes::AnyVal rule_const_def();
    logos::hermes::AnyVal rule_type_alias();
    logos::hermes::AnyVal rule_pub_enum_def();
    logos::hermes::AnyVal rule_enum_def();
    logos::hermes::AnyVal rule_variant_list();
    logos::hermes::AnyVal rule_variant_def();
    logos::hermes::AnyVal rule_pub_trait_def();
    logos::hermes::AnyVal rule_trait_def();
    logos::hermes::AnyVal rule_trait_method();
    logos::hermes::AnyVal rule_impl_block();
    logos::hermes::AnyVal rule_impl_item();
    logos::hermes::AnyVal rule_class_def();
    logos::hermes::AnyVal rule_class_member();
    logos::hermes::AnyVal rule_static_fn_def();
    logos::hermes::AnyVal rule_abstract_method_def();
    logos::hermes::AnyVal rule_pub_struct_def();
    logos::hermes::AnyVal rule_struct_def();
    logos::hermes::AnyVal rule_field_def();
    logos::hermes::AnyVal rule_method_def();
    logos::hermes::AnyVal rule_extern_fn_def();
    logos::hermes::AnyVal rule_pub_fn_def();
    logos::hermes::AnyVal rule_fn_def();
    logos::hermes::AnyVal rule_param_list();
    logos::hermes::AnyVal rule_param();
    logos::hermes::AnyVal rule_type_ref();
    logos::hermes::AnyVal rule_assoc_type_ref();
    logos::hermes::AnyVal rule_dyn_type();
    logos::hermes::AnyVal rule_slice_type();
    logos::hermes::AnyVal rule_ref_type();
    logos::hermes::AnyVal rule_tuple_type();
    logos::hermes::AnyVal rule_ptr_type();
    logos::hermes::AnyVal rule_arr_type();
    logos::hermes::AnyVal rule_simple_type();
    logos::hermes::AnyVal rule_block();
    logos::hermes::AnyVal rule_stmt();
    logos::hermes::AnyVal rule_for_stmt();
    logos::hermes::AnyVal rule_loop_stmt();
    logos::hermes::AnyVal rule_break_stmt();
    logos::hermes::AnyVal rule_continue_stmt();
    logos::hermes::AnyVal rule_match_stmt();
    logos::hermes::AnyVal rule_match_arm();
    logos::hermes::AnyVal rule_pat_binding();
    logos::hermes::AnyVal rule_pat_binding_list();
    logos::hermes::AnyVal rule_pattern();
    logos::hermes::AnyVal rule_index_write_stmt();
    logos::hermes::AnyVal rule_let_stmt();
    logos::hermes::AnyVal rule_while_stmt();
    logos::hermes::AnyVal rule_return_stmt();
    logos::hermes::AnyVal rule_assign_stmt();
    logos::hermes::AnyVal rule_delete_stmt();
    logos::hermes::AnyVal rule_field_write_stmt();
    logos::hermes::AnyVal rule_field_index_write_stmt();
    logos::hermes::AnyVal rule_deref_write_stmt();
    logos::hermes::AnyVal rule_if_expr();
    logos::hermes::AnyVal rule_expr();
    logos::hermes::AnyVal rule_log_expr();
    logos::hermes::AnyVal rule_cmp_expr();
    logos::hermes::AnyVal rule_add_expr();
    logos::hermes::AnyVal rule_mul_expr();
    logos::hermes::AnyVal rule_unary_expr();
    logos::hermes::AnyVal rule_cast_expr();
    logos::hermes::AnyVal rule_atom();
    logos::hermes::AnyVal rule_primary_expr();
    logos::hermes::AnyVal rule_new_expr();
    logos::hermes::AnyVal rule_enum_lit();
    logos::hermes::AnyVal rule_struct_lit();
    logos::hermes::AnyVal rule_field_init();
    logos::hermes::AnyVal rule_arr_lit();
    logos::hermes::AnyVal rule_tuple_lit();
    logos::hermes::AnyVal rule_closure_expr();
    logos::hermes::AnyVal rule_paren_expr();
    logos::hermes::AnyVal rule_type_param_list();
    logos::hermes::AnyVal rule_trait_bound();
    logos::hermes::AnyVal rule_type_param();
    logos::hermes::AnyVal rule_type_arg_list();
    logos::hermes::AnyVal rule_call_arg_list();
    logos::hermes::AnyVal rule_call_expr();

    // Lexer state.
    using TK = TK_LOGOS;
    struct Token { TK kind; std::string_view text; uint32_t line = 0; };
    Token lex_one();
    Token next_token();
    Token peek_token();
    bool  try_token(TK kind);
    Token expect_token(TK kind, std::string_view what);

    logos::hermes::HermesCtr doc_;
    std::string_view         source_;
    size_t                   pos_ = 0;
    uint32_t                 line_ = 1;  // current source line (1-based)
    Token                    la_{};
    bool                     have_la_ = false;
}; // class LogosParser

} // namespace logos::compiler

