#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from a19_for_arrlit_iter.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct W { x: D, y: D, z: i64 }
impl D { fn get(&self) -> i64 { return self.v; } }
fn mk(v: i64, p: *mut i64) -> D { return D { v: v, c: p }; }
fn mkarr(p: *mut i64) -> [D; 2] { return [D { v: 1i64, c: p }, D { v: 10i64, c: p }]; }
fn mktup(p: *mut i64) -> (D, D) { return (D { v: 1i64, c: p }, D { v: 10i64, c: p }); }
fn sumref(a: &[D; 2]) -> i64 { return a[0].v + a[1].v; }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64) -> i64 {
    let mut s: i64 = 0i64;
    for d in [D { v: 1i64, c: p }, D { v: 10i64, c: p }].iter() {
        s = s + d.v;
    }
    return s;
}
fn real_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = g(p);
    let got: i64 = rd(p);
    unsafe { printf(c"r=%ld n=%ld\n".as_ptr(), r, got); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
