#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from h01_heap_arrlit_string_index_len.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
fn real_main() -> i32 {
    let k: i64 = [String::from("ab"), String::from("xyz")][1].len() as i64;  // TWIN: usize -> i64
    unsafe { printf(c"k=%ld\n".as_ptr(), k); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
