#![allow(unused, dead_code, unused_mut)]
use std::ops::*;
// TWIN: generated by l2rs.py from h03_heap_let_ref_structlit_string_field.logos
unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal
struct P { a: String, b: String }
fn noise() -> i64 {
    let t: String = String::from("zzzzzzzzzzzz");
    return t.len() as i64;
}
fn real_main() -> i32 {
    let k: &String = &P { a: String::from("ab"), b: String::from("xyz") }.b;
    let z: i64 = noise();
    let n: i64 = k.len() as i64;  // TWIN: usize -> i64
    unsafe { printf(c"n=%ld z=%ld\n".as_ptr(), n, z); }
    return 0i32;
}
fn main() { std::process::exit(real_main()); }
