#!/usr/bin/env python3
"""l2rs.py SRC.logos OUT.rs — mechanical Logos->Rust twin for this round's hand battery (spelling only; any other rewrite is marked // TWIN:)."""
import re, sys
src = open(sys.argv[1]).read()
out = ["#![allow(unused, dead_code, unused_mut)]", "use std::ops::*;", "// TWIN: generated by l2rs.py from " + sys.argv[1].split('/')[-1]]
for line in src.splitlines():
    if line.startswith("package "): continue
    if line.startswith("extern fn printf"):
        out.append('unsafe extern "C" { fn printf(fmt: *const std::ffi::c_char, ...) -> i32; }  // TWIN: C char pointer for a c"" literal'); continue
    l = line
    l = re.sub(r"self: &mut \w+", "&mut self", l)
    l = re.sub(r"self: &\w+", "&self", l)
    l = re.sub(r"self: \w+", "self", l)
    m = re.match(r"(\s*)fn (add|neg|sub|mul)\((self)(.*)\) -> (\w+) \{", l)
    if m:
        out.append(m.group(1) + "type Output = " + m.group(5) + ";  // TWIN: Logos operator traits carry no Output type")
    l = re.sub(r'"([^"]*)"\.as_ptr\(\)', r'c"\1".as_ptr()', l)
    l = l.replace("fn main() -> i32", "fn real_main() -> i32")
    out.append(l)
out.append("fn main() { std::process::exit(real_main()); }")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
