// TWIN of tests/logos/pass/bc_0914b_ptrcoerceland_hb_m10_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14b-ptrcoerceland, program M10 — caught: refuted an arm — PROBES.md "build 3 ... M5 M10 M11 E02 E09"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land14a_twins4.YY4f/M10_let_elided_mutptr_decay_static_elems.logos
static G: i64 = 7i64;
fn __logos_main() -> i32 {
    let mut a: [&'static i64; 2] = [&G, &G];
    let q: *mut &i64 = &mut a;
    return unsafe { **q } as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

