// TWIN of tests/logos/pass/bc_0909d_atland_hb_g13_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: Option::Some/None -> prelude Some/None
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-09d-atland, program g13 — caught: refuted an arm, verdict moved base -> landed — PROBES.md "(a) g13/g22 SEGFAULTED under the first At case" | (b) tables/hand_head.txt vs hand_final.txt: run=1 or cc=1 on HEAD -> cc=0 run=0 landed...
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-09d-atland/hand/g13.logos
// An at-binding on a struct field whose sub is a VARIANT with a BINDING inside.
struct Q { o: Option<i64>, y: i64 }
fn __logos_main() -> i32 {
    let q: Q = Q { o: Some(4i64), y: 2i64 };
    let mut out: i64 = 0i64;
    match q {
        Q { o: a @ Some(k), y } => { out = k + y; if let Some(v) = a { out = out + v; } }
        Q { o: _, y: _ } => { out = -1i64; }
    }
    if out != 10i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

