// TWIN of tests/logos/pass/bc_0914p_shadowslot_hb_s12_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 0914p_shadowslot, program s12 — caught: verdict moved base -> shadowslot landing
// legality: by reading, no rustc binary
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c * 10i64 + self.v; } } }
fn eatd(x: D) -> i64 { return x.v; }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn g(p: *mut i64, c: bool) {
    let x: D = D { v: 1i64, c: p };
    if c { let _k: i64 = eatd(x); }
    let x: D = D { v: 2i64, c: p };
    let _j: i64 = x.v;
}
fn __logos_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    g(p, false);
    if rd(p) != 21i64 { return 1i32; }
    unsafe { *p = 0i64; }
    g(p, true);
    if rd(p) != 12i64 { return 2i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

