// TWIN of tests/logos/pass/bc_0914f_thrurefland_hb_d06_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14f-thrurefland, program d06 — caught: verdict moved base -> landed — PROBES.md "ref-typed LOCAL root (`&r.a`, `r = &s2`), let / match-default / written walk CLOSED (queue row; d01 d06 d09 d12 d24 d29 d30 d31, t1-t3)"...
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/land14f_d2.978t/d06_mutref_assign_in_branch_legal.logos
struct P { a: i64, b: i64 }
fn __logos_main() -> i32 {
    let mut s1: P = P { a: 1i64, b: 2i64 };
    let mut s2: P = P { a: 3i64, b: 4i64 };
    let c: bool = s2.b > 0i64;
    let mut r: &mut P = &mut s1;
    let a: &mut i64 = &mut r.a;
    if c {
        r = &mut s2;
    }
    *a = 5i64;
    r.b = 9i64;
    return (s1.a + s2.b) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

