// TWIN of tests/logos/pass/bc_0914f_thrurefland_hb_q16_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14f-thrurefland, program q16 — caught: refuted an arm, predicted wrong — PROBES.md "Build 1 refused q16 (`*const W<'a>` vs `*const W<'b>`, W covariant)" | "q16 needed the per-parameter variance read (build 2)"
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/land14f_r2.sFtP/q16_struct_under_constptr_legal.logos
struct W<'x> { r: &'x i64 }
fn f<'a, 'b>(x: *const W<'a>, y: *const W<'b>) -> bool {
    return x == y;
}
fn __logos_main() -> i32 {
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

