// TWIN of tests/logos/pass/bc_0906e_scalarcore_hb_h34_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06e-scalarcore, program h34 — caught: refuted an arm — PROBES.md "h33 / h34 / h35 put a LITERAL or RANGE arm and a WHOLE-SCRUTINEE BINDER ... legal Rust — and under `scall` they are still refused"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06e-scalarcore/hand/h34.logos
// the same two-arm shape, taking the BINDER arm (v is out of the literal)
fn __logos_main() -> i32 {
    let v: i64 = 9i64;
    let mut out: i64 = 0i64;
    match &v { 4i64 => { out = 1i64; } x => { out = *x; } }
    if out != 9i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

