// TWIN of tests/logos/pass/bc_0911d_liferegb_hb_l5b_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-11d-liferegb, program L5b — caught: refuted an arm — PROBES.md "Legal and REFUSED (3) — none of them in any corpus column: L1 ... L7 ... L5b"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/lb/hand/L5b.logos
struct U2 { h: &i64 }
fn f<'a>(x: &'a i64, y: &i64) -> &'a i64 {
  let mut u: U2 = U2 { h: x };
  u.h = y;
  u.h = x;
  return u.h;
}
fn __logos_main() -> i32 { return 0i32; }

fn main() { std::process::exit(__logos_main() as i32); }

