// TWIN of tests/logos/pass/bc_0911b_e0207_land_hb_n11_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: receiver self: T -> self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-11b-e0207-land, program n11 — caught: refuted an arm — PROBES.md "THREE LEGAL PROGRAMS WERE REFUSED: n1 ... n10 ... n11" (the first landing form)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/e0207/n11.logos
// LEGAL: 'a constrained through the SELF TYPE's generic argument (`W<'a>`),
// a LIFETIME_PARAM nested one level down, not a bare `&'a S`.
struct W<'a> { r: &'a i64 }
trait Tr { type Item; fn go(self) -> i64; }
impl<'a> Tr for W<'a> {
    type Item = &'a i64;
    fn go(self) -> i64 { return 11i64; }
}
fn __logos_main() -> i32 { return 0i32; }

fn main() { std::process::exit(__logos_main() as i32); }

