// TWIN of tests/logos/pass/bc_0914k_fnptrbinderland_hb_c30_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14k-fnptrbinderland, program c30 — caught: legal, refused with the item-binder rename control-reverted (fnptrnoitembind): a MATCH-join of fn items
// legality: by reading, no rustc binary
fn ida<'a>(x: &'a i64) -> i64 { return *x; }
fn idb<'b>(x: &'b i64) -> i64 { return *x + 1i64; }
fn __logos_main() -> i32 {
    let n: i32 = 1i32;
    let f: fn(&i64) -> i64 = match n { 0i32 => ida, _ => idb };
    let v: i64 = 29i64;
    return f(&v) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

