// TWIN of tests/logos/pass/bc_0906_patmut_hb_c13_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.std.fmt;` dropped: stdlib path, prelude in Rust
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06-patmut, program c13 — caught: verdict moved base -> landed — PROBES.md "LEGAL, base REFUSED -> now RUN rc 0 (13): c01 ... c19"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06-patmut/hand2/c13_match_mut_drop_count.logos
struct S { v: i64 }
impl Drop for S { fn drop(&mut self) { println!("DROP v={}", self.v); } }
impl S { fn get(&mut self) -> &mut i64 { return &mut self.v; } }
enum E { A(S), B }
fn __logos_main() -> i32 {
    let e: E = E::A(S { v: 1i64 });
    match e {
        E::A(mut s) => { let r: &mut i64 = s.get(); *r = 8i64; },
        E::B => {}
    }
    println!("-- end");
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

