// TWIN of tests/logos/pass/bc_0914b_ptrcoerceland_hb_e02_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14b-ptrcoerceland, program E02 — caught: refuted an arm — PROBES.md "build 3 ... M5 M10 M11 E02 E09"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land14a_twins5.F7Ma/E02_struct_lit_mutptr_field_from_mutref_static.logos
static G: i64 = 7i64;
struct H<'a> { p: *mut &'a i64 }
fn __logos_main() -> i32 {
    let mut r: &'static i64 = &G;
    let h: H = H { p: &mut r };
    return unsafe { **h.p } as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

