// TWIN of tests/logos/pass/bc_0912r_escroot_hb_v8_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-12r-escroot, program v8 — caught: refuted an arm — PROBES.md "lrvar / lrx refuse LEGAL v8"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/r0912r/ctl5/v8_legal_escape_holder_of_ref_local_field.logos
struct H<'x> { r: &'x i64 }
fn store<'a>(p: &'a i64, out: &mut &'a i64) {
    let h: H<'a> = H { r: p };
    let hr: &H<'a> = &h;
    let e: &'a i64 = hr.r;
    *out = e;
}
fn __logos_main() -> i32 {
    let w: i64 = 78i64;
    let z: i64 = 0i64;
    let mut r: &i64 = &z;
    store(&w, &mut r);
    return *r as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

