// TWIN of tests/logos/pass/bc_0914o_autoreffund_hb_h14_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.lang.cmp;` dropped: stdlib path, prelude in Rust
// TWIN: extern fn printf -> unsafe extern "C" block (edition 2024)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: printf format literal -> b"..\0".as_ptr() (Rust has no implicit C string)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
unsafe extern "C" { fn printf(fmt: *const u8, ...) -> i32; }
// hand battery: round 2026-09-14o-autoreffund, program h14 — caught: (round 2026-09-14n) a temporary operand beside a field place operand never dropped on base; 1001 under the landing
// legality: by reading, no rustc binary
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
impl Eq for D { fn eq(&self, other: &D) -> bool { return self.v > 0i64 && other.v > 0i64; } }
fn mk(v: i64, c: *mut i64) -> D { return D { v: v, c: c }; }
struct S { d: D, k: i64 }
fn body(p: *mut i64) -> i64 {
    let s: S = S { d: D { v: 1i64, c: p }, k: 2i64 };
    if !(s.d == D { v: 1000i64, c: p }) { return 3i64; }
    return s.k - 2i64;
}

fn __logos_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let r: i64 = body(p);
    let got: i64 = unsafe { n };
    unsafe { printf(b"n=%ld r=%ld\n\0".as_ptr(), got, r); }
    if r != 0i64 { return 2i32; }
    if got != 1001i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

