// TWIN of tests/logos/pass/bc_0906g_refmode_hb_h18_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06g-refmode, program h18 — caught: refuted an arm — PROBES.md "h18 — `(ref s, b)` over a MOVE-ONLY element, read only — compiles under `tupboth` and EXITS 1"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06g-refmode/hand/h18.logos
// LEGAL. A move-only payload bound `ref` in a tuple: no move out, no double free.
struct S { v: i64 }
fn __logos_main() -> i32 {
    let t: (S, i64) = (S { v: 3i64 }, 4i64);
    match t {
        (ref s, b) => { if s.v + b != 7i64 { return 1i32; } }
    }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

