// TWIN of tests/logos/pass/bc_0912i_door1point_hb_c10_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-12i-door1point, program C10 — caught: verdict moved base -> landed — PROBES.md "C10 ... base REFUSES twice, the arm **ADMITS**. An over-refusal this change REPAIRS. Landed as pass/bc_backedge_two_holders_admit"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-12i-door1point/legal/C10.logos
// C10 — TWO INDEPENDENT REFERENTS, two holders, both raised below their own
// uses. Legal; a predicate that keys on "some loan is live in this loop"
// rather than on the record would refuse the second.
fn __logos_main() -> i32 {
    let mut a: i64 = 0i64;
    let mut b: i64 = 0i64;
    let mut ax: &mut i64 = &mut a;
    let mut bx: &mut i64 = &mut b;
    let mut i: i64 = 0i64;
    while i < 3i64 {
        *ax = *ax + 1i64;
        *bx = *bx + 2i64;
        ax = &mut a;
        bx = &mut b;
        i = i + 1i64;
    }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

