// TWIN of tests/logos/pass/bc_0913d_staticdemand_hb_r08_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: receiver self: &mut T -> &mut self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-13d-staticdemand, program r08 — caught: refuted an arm — PROBES.md "stmutdeclx illegal closed y02 y03 y04 y05 y06 · REFUSES LEGAL r04 ... r08 ... r17 ... CONDEMNED 3"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land0913d.kjFy/hand1/r08_struct_set_method.logos
static V: i64 = 5i64;
static SR: &i64 = &V;
struct W<'a> { r: &'a i64 }
impl<'a> W<'a> {
    fn set(&mut self, x: &'a i64) { self.r = x; }
}
fn __logos_main() -> i32 {
    let n: i64 = 7i64;
    let mut w = W { r: SR };
    w.set(&n);
    return *w.r as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

