// TWIN of tests/logos/pass/bc_0906p_ergodoors_hb_n11_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.std.fmt;` dropped: stdlib path, prelude in Rust
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: Option::Some/None -> prelude Some/None
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06p-ergodoors, program n11 — caught: refuted an arm — PROBES.md "ergonest CHANGES ... NOT changed: n10 (struct door) and n11 (slice door)" (destructor count 2, Rust 1)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06p-ergodoors/hand/n11.logos
// same program (modulo package/comments) in round 2026-09-07q-dbmcarry as c07
struct S { pub n: i64 }
impl Drop for S { fn drop(&mut self) { println!("D{}", self.n); } }
fn __logos_main() -> i32 {
    let arr: [Option<S>; 1] = [Some(S { n: 5i64 })];
    let mut out: i64 = 0i64;
    match &arr {
        [Some(a)] => { out = a.n; },
        [None] => {}
    }
    if out != 5i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

