// TWIN of tests/logos/pass/bc_0914b_ptrcoerceland_hb_q15_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14b-ptrcoerceland, program Q15 — caught: refuted an arm — PROBES.md "build 1 crosskindxd + aorecvty as priced ... LEGAL REFUSED BY HAND Q01 Q11 Q15 V02 V02B V02I V20 V21 V25 V26 V27"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land14a_twins2.okas/Q15_ref_box_static_to_constptr_box_shorter.logos
static G: i64 = 7i64;
fn look<'a>(b: &'a Box<&'static i64>) -> *const Box<&'a i64> {
    return b;
}
fn __logos_main() -> i32 {
    let b: Box<&'static i64> = Box::new(&G);
    let p: *const Box<&i64> = look(&b);
    return 1i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

