// TWIN of tests/logos/pass/bc_0914f_thrurefland_hb_p02_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14f-thrurefland, program p02 — caught: verdict moved base -> landed — PROBES.md "place RETARGET `h.r = &s2` under `&h.r.0` ... CLOSED (queue row; p02)"; measured base REFUSED -> today RUN
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/land14f_d2.978t/p02_place_assign_ref_field_legal.logos
struct H<'x> { r: &'x (i64, i64) }
fn __logos_main() -> i32 {
    let s1: (i64, i64) = (1i64, 2i64);
    let s2: (i64, i64) = (3i64, 4i64);
    let mut h: H = H { r: &s1 };
    let a: &i64 = &h.r.0;
    h.r = &s2;
    return (*a + h.r.0) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

