// TWIN of tests/logos/pass/bc_0906_patmut_hb_c07_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06-patmut, program c07 — caught: predicted wrong — predictions-2026-09-06b.txt:9 "c05 c06 c07 c12 ... refused -> run 0"; PROBES.md "c05 c06 c07 ... RAN on base too"; c12 "refused" (PROBES.md)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06-patmut/hand2/c07_slice_pat_mut_reassign.logos
fn __logos_main() -> i32 {
    let arr: [i64; 2] = [1i64, 2i64];
    let mut out: i64 = 0i64;
    match arr {
        [mut a, b] => { a = a + 10i64; out = a + b; }
    }
    if out != 13i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

