// TWIN of tests/logos/pass/bc_0914k_fnptrbinderland_hb_c15_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14k-fnptrbinderland, program c15 — caught: legal, refused on base (for<'p> into for<'q>, alpha-renamed) and with fnptrnohrtb; admitted by the landing
// legality: by reading, no rustc binary
fn id<'k>(x: &'k i64) -> &'k i64 { return x; }
fn __logos_main() -> i32 {
    let f: for<'p> fn(&'p i64) -> &'p i64 = id;
    let g: for<'q> fn(&'q i64) -> &'q i64 = f;
    let v: i64 = 15i64;
    return *g(&v) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

