// TWIN of tests/logos/pass/bc_0914p_shadowslot_hb_s34_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 0914p_shadowslot, program s34 — caught: verdict moved base -> shadowslot landing
// legality: by reading, no rustc binary
struct D { v: i64, c: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.c = *self.c * 10i64 + self.v; } } }
fn eatd(x: D) -> i64 { return x.v; }
fn rd(p: *mut i64) -> i64 { return unsafe { *p }; }
fn __logos_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    {
        let x: D = D { v: 1i64, c: p };
        let k: i64 = eatd(x);
        let f = |x: D| -> i64 { return x.v; };
        if f(D { v: 2i64, c: p }) + k != 3i64 { return 9i32; }
    }
    if rd(p) != 12i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

