// TWIN of tests/logos/pass/bc_0914b_ptrcoerceland_hb_v26_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14b-ptrcoerceland, program V26 — caught: refuted an arm — PROBES.md "build 1 crosskindxd + aorecvty as priced ... LEGAL REFUSED BY HAND Q01 Q11 Q15 V02 V02B V02I V20 V21 V25 V26 V27"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land14a_twins3.L1yE/V26_match_arm_store_value_last_use.logos
fn __logos_main() -> i32 {
    let mut v: Vec<i64> = Vec::new();
    v.push(1i64); v.push(2i64);
    let c: bool = v.len() > 1i64;
    let e: &i64 = &v[1u64];
    match c {
        true => { v[0u64] = *e + 2i64; }
        false => {}
    }
    return v[0u64] as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

