// TWIN of tests/logos/pass/bc_0912q_letregion_hb_a6_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-12q-letregion, program a6 — caught: verdict moved base -> landed — PROBES.md "Newly COMPILING, all legal, all run to their exit code: y1 y2 y3 (deref stop) · a6 a10 e3 m1 m3 m4 m5 o3"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/r0912q/ctl/a6_legal_named_param.logos
struct Bar { v: i64 }
struct Foo<'s> { bar: &'s mut Bar }
impl<'s> Foo<'s> {
    fn newf(bar: &'s mut Bar) -> Self {
        return Foo { bar: bar };
    }
}
fn __logos_main() -> i32 {
    let mut b: Bar = Bar { v: 4i64 };
    let f: Foo<'_> = Foo::newf(&mut b);
    return f.bar.v as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

