// TWIN of tests/logos/pass/bc_0914o_autoreffund_hb_c07_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.lang.cmp;` dropped: stdlib path, prelude in Rust
// TWIN: `use logos.mem.string;` dropped: stdlib path, prelude in Rust
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14o-autoreffund, program c07 — caught: four `String` operator temporaries (`==`, `!=`, both sides, `str == String`): 216 bytes definitely lost in 4 blocks on base (valgrind), 0 errors under the landing
// legality: by reading, no rustc binary
fn __logos_main() -> i32 {
    let a: String = String::from("abcdefghijklmnopqrstuvwxyz");
    if !(a == String::from("abcdefghijklmnopqrstuvwxyz")) { return 3i32; }
    if a != String::from("abcdefghijklmnopqrstuvwxyz") { return 4i32; }
    if !(String::from("abcdefghijklmnopqrstuvwxyz") == a) { return 5i32; }
    if !("abcdefghijklmnopqrstuvwxyz" == String::from("abcdefghijklmnopqrstuvwxyz")) { return 6i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

