// TWIN of tests/logos/pass/bc_0914o_autoreffund_hb_n04_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.mem.string;` dropped: stdlib path, prelude in Rust
// TWIN: extern fn printf -> unsafe extern "C" block (edition 2024)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: printf format literal -> b"..\0".as_ptr() (Rust has no implicit C string)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
unsafe extern "C" { fn printf(fmt: *const u8, ...) -> i32; }
// hand battery: round 2026-09-14o-autoreffund, program n04 — caught: legal, correct on base and under the landing; REFUSED with E0507 under the priced neighbour arm fieldinplace (a field base borrowed in place), which it condemns
// legality: by reading, no rustc binary
struct C { v: i64, c: *mut i64 }
impl Drop for C { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
struct P { name: String, tag: C }
fn mkp(c: *mut i64) -> P {
    return P { name: String::from("abcdefghijklmnopqrstuvwxyz"), tag: C { v: 1000i64, c: c } };
}
fn __logos_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let mut len: i64 = 0i64;
    {
        let s: String = mkp(p).name;
        len = s.len() as i64;
    }
    let got: i64 = unsafe { n };
    unsafe { printf(b"len=%ld n=%ld\n\0".as_ptr(), len, got); }
    if len != 26i64 { return 2i32; }
    if got != 1000i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

