// TWIN of tests/logos/pass/bc_0913d_staticdemand_hb_e02_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-13d-staticdemand, program e02 — caught: refuted an arm — PROBES.md "cooutsitese + x08 · REFUSES LEGAL e01 ... e02 ... e05 ... e08 ... CONDEMNED 4"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land0913d.kjFy/hand/e02_vec_push_static.logos
static V: i64 = 5i64;
fn keepv<'a>(v: Vec<&'a i64>) -> i64 where 'a: 'static {
    return v.len() as i64;
}
fn __logos_main() -> i32 {
    let mut v: Vec<&i64> = Vec::new();
    v.push(&V);
    let k = keepv(v);
    return k as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

