// TWIN of tests/logos/pass/bc_0912q_letregion_hb_s1_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-12q-letregion, program s1 — caught: refuted an arm — PROBES.md "DO NOT FUND door L as priced (`letnamed` / `letnamedc`). FOUR legal refusals in four shapes — p24 ..."
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/r0912q/ctl2/s1_legal_box_field_deref.logos
struct W { b: Box<i64> }
fn foo<'a>(w: &'a W) -> i64 {
    let r: &'a i64 = &*w.b;
    return *r;
}
fn __logos_main() -> i32 {
    let w: W = W { b: Box::new(21i64) };
    return foo(&w) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

