// TWIN of tests/logos/pass/bc_0914j_fnptrbinder_hb_h03_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14j-fnptrbinder, program h03 — caught: refuted fnptrelidesup: REFUSED this legal program — the item's 'a spelled like the enclosing fn's 'a
// legality: by reading, no rustc binary
fn idr<'a>(x: &'a i64) -> i64 { return *x; }
fn test<'a>(q: &'a i64) -> i32 {
    let f: fn(&i64) -> i64 = idr;
    return f(q) as i32;
}
fn __logos_main() -> i32 {
    let v: i64 = 13i64;
    return test(&v);
}

fn main() { std::process::exit(__logos_main() as i32); }

