// TWIN of tests/logos/pass/bc_0906f_scalarland_hb_g17_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06f-scalarland, program g17 — caught: verdict moved base -> landed — PROBES.md "20 of 20 g-programs refused at base; NINETEEN now compile and run 0" (g08 -> run 139, PROBES.md)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06f-scalarland/hand/g17.logos
fn pick(p: &i64) -> i64 {
    match p {
        3i64 => { return 30i64; }
        4i64 => { return 40i64; }
        _ => { return 0i64; }
    }
}
fn __logos_main() -> i32 {
    let v: i64 = 4i64;
    if pick(&v) != 40i64 { return 1i32; }
    let w: i64 = 3i64;
    if pick(&w) != 30i64 { return 2i32; }
    let z: i64 = 9i64;
    if pick(&z) != 0i64 { return 3i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

