// TWIN of tests/logos/pass/bc_0914k_fnptrbinderland_hb_c01_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14k-fnptrbinderland, program c01 — caught: legal, refused with the item-binder rename control-reverted (fnptrnoitembind): a turbofish ref carries the item's named region
// legality: by reading, no rustc binary
fn idg<'q, T>(x: &'q T) -> &'q T { return x; }
fn __logos_main() -> i32 {
    let f: fn(&i64) -> &i64 = idg::<i64>;
    let v: i64 = 41i64;
    return *f(&v) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

