// TWIN of tests/logos/pass/bc_0914e_thruref_hb_m5_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14e-thruref, program m5 — caught: verdict moved base -> landed — PROBES.md "asgref (7 moved, all LEGAL, all RUN): m1 m2 m5 t1 t2 t3"; landed 2026-09-14f, measured base REFUSED -> today RUN
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/letk.7cSu/m5_let_tuple_field_reassign_legal.logos
fn __logos_main() -> i32 {
    let s1: (i64, i64) = (1i64, 2i64);
    let s2: (i64, i64) = (3i64, 4i64);
    let mut r: &(i64, i64) = &s1;
    let a: &i64 = &r.1;
    r = &s2;
    return (*a + r.0 - 5i64) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

