// TWIN of tests/logos/pass/bc_0906c_patclass_hb_a14_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: Option::Some/None -> prelude Some/None
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06c-patclass, program a14 — caught: refuted an arm — PROBES.md "The (a) set under ifletown / ifletown2: IDENTICAL to HEAD except a14 ... armed REFUSES \"use of moved variable 'o'\". A LEGAL program re...
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06c-patclass/hand/a14_ifletchain_ref.logos
struct S { v: i64, i: *mut i64 }
impl Drop for S { fn drop(&mut self) { unsafe { *self.i = *self.i + self.v; } } }
fn __logos_main() -> i32 {
    let mut c: i64 = 0i64;
    let p: *mut i64 = &mut c;
    {
        let o: Option<S> = Some(S { v: 1i64, i: p });
        let mut out: i64 = 0i64;
        if let Some(ref s) = o && s.v > 0i64 {
            out = s.v;
        }
        if out != 1i64 { return 9i32; }
        if let Some(ref s2) = o { out = s2.v + 1i64; }
        if out != 2i64 { return 8i32; }
    }
    return c as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

