// TWIN of tests/logos/pass/bc_0914e_thruref_hb_k05_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: Option::Some/None -> prelude Some/None
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14e-thruref, program k05 — caught: refuted an arm, predicted wrong — PROBES.md "pbdbm (15 moved): ... REFUSED LEGAL b10 k01 k05 k08 (a use of the scrutinee after the binding's LAST use) and t4 t5 t6 m14 m15 (an assig...
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/ctlb2.kQ72/k05_reborrow_in_arm_after.logos
fn bump(o: &mut Option<i64>) { *o = Some(7i64); }
fn __logos_main() -> i32 {
    let mut foo: Option<i64> = Some(3i64);
    let bar: &mut Option<i64> = &mut foo;
    match bar {
        Some(baz) => {
            *baz = 4i64;
            bump(bar);
        }
        None => { }
    }
    match foo { Some(v) => { return (v - 7i64) as i32; } None => { return 9i32; } }
}

fn main() { std::process::exit(__logos_main() as i32); }

