// TWIN of tests/logos/pass/bc_0914o_autoreffund_hb_l04_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: extern fn printf -> unsafe extern "C" block (edition 2024)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: printf format literal -> b"..\0".as_ptr() (Rust has no implicit C string)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
unsafe extern "C" { fn printf(fmt: *const u8, ...) -> i32; }
// hand battery: round 2026-09-14o-autoreffund, program l04 — caught: `side(s) + mk(3, s).tryget()?`: base built the receiver before side (317); source order and the drop on the `?` path under the landing (137)
// legality: by reading, no rustc binary
struct D { v: i64, s: *mut i64 }
impl Drop for D { fn drop(&mut self) { unsafe { *self.s = *self.s * 10i64 + self.v + 4i64; } } }
impl D {
    fn get(&self) -> i64 { return self.v; }
    fn view(&self) -> &i64 { return &self.v; }
    fn me(&self) -> &D { return self; }
    fn opt(&self) -> Option<&i64> { return Some(&self.v); }
    fn tryget(&self) -> Option<i64> { if self.v > 2i64 { return None; } return Some(self.v); }
}
fn mk(v: i64, s: *mut i64) -> D {
    unsafe { *s = *s * 10i64 + v; }
    return D { v: v, s: s };
}
fn side(s: *mut i64) -> i64 {
    unsafe { *s = *s * 10i64 + 1i64; }
    return 1i64;
}
fn rd(s: *mut i64) -> i64 { return unsafe { *s }; }

fn body(s: *mut i64) -> Option<i64> {
    let k: i64 = side(s) + mk(3i64, s).tryget()?;
    return Some(k);
}
fn __logos_main() -> i32 {
    let mut q: i64 = 0i64;
    let s: *mut i64 = &mut q;
    let r: Option<i64> = body(s);
    let got: i64 = rd(s);
    unsafe { printf(b"seq=%ld\n\0".as_ptr(), got); }
    if r.is_some() { return 2i32; }
    if got != 137i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

