// TWIN of tests/logos/pass/bc_0913d_staticdemand_hb_e08_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-13d-staticdemand, program e08 — caught: refuted an arm — PROBES.md "cooutsitese + x08 · REFUSES LEGAL e01 ... e02 ... e05 ... e08 ... CONDEMNED 4"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/land0913d.kjFy/hand/e08_array_elem_static.logos
static V: i64 = 3i64;
static V2: i64 = 4i64;
fn static_id<'a>(t: &'a i64) -> &'static i64 where 'a: 'static { return t; }
fn __logos_main() -> i32 {
    let arr: [&i64; 2] = [&V, &V2];
    let s = static_id(arr[1]);
    return *s as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

