// TWIN of tests/logos/pass/bc_0914f_thrurefland_hb_d03_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14f-thrurefland, program d03 — caught: verdict moved base -> landed — PROBES.md "tuple / struct LOCAL holding a reference (`&t.0.a`, `&h.r.b`, nested `h.m.p.a`) CLOSED, same reader, the path-type walk (d02 d03 d16 d18...
// legality: by reading, no rustc binary
// harvested 2026-09-14i from snapshot hand-harvest-2026-09-14b/land14f_d2.978t/d03_struct_local_ref_field_legal.logos
struct P { a: i64, b: i64 }
struct H<'x> { r: &'x P, k: i64 }
fn __logos_main() -> i32 {
    let s1: P = P { a: 1i64, b: 2i64 };
    let s2: P = P { a: 3i64, b: 4i64 };
    let mut h: H = H { r: &s1, k: 5i64 };
    let a: &i64 = &h.r.b;
    h = H { r: &s2, k: 6i64 };
    return (*a + h.r.a + h.k) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

