// TWIN of tests/logos/pass/bc_0913a_selfregion_hb_l3_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: receiver self: &T -> &self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-13a-selfregion, program L3 — caught: refuted an arm — PROBES.md "selfbody (D1 alone) REFUSES LEGAL L3 ... selfpair (batch 1) REFUSES LEGAL s13 L3"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/ctl2/L3_anon_let_self_annot.logos
struct Foo<'s> { r: &'s i64 }
impl Foo<'_> {
    fn dup(&self) -> Self {
        let g: Self = Foo { r: self.r };
        return g;
    }
}
fn __logos_main() -> i32 {
    let v: i64 = 63i64;
    let f = Foo { r: &v };
    let g = f.dup();
    return *g.r as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

