// TWIN of tests/logos/pass/bc_0914k_fnptrbinderland_hb_c36_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14k-fnptrbinderland, program c36 — caught: legal, refused with the item-binder rename control-reverted (fnptrnoitembind): a turbofish item's 'a spelled like the scope's 'a
// legality: by reading, no rustc binary
fn idg<'a, T>(x: &'a T) -> &'a T { return x; }
fn t<'a>(q: &'a i64) -> i64 {
    let f: fn(&i64) -> &i64 = idg::<i64>;
    return *f(q);
}
fn __logos_main() -> i32 {
    let v: i64 = 36i64;
    return t(&v) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

