// TWIN of tests/logos/pass/bc_0910dropord_hb_c9_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: extern fn printf -> unsafe extern "C" block (edition 2024)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: printf format literal -> b"..\0".as_ptr() (Rust has no implicit C string)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
unsafe extern "C" { fn printf(fmt: *const u8, ...) -> i32; }
// hand battery: round 2026-09-10dropord, program c9 — caught: verdict moved base -> landed — PROBES.md "c1 struct, 3 fields 321 -> 123 ... c17 nested struct + user Drop 3n921 -> n9123" (drop order, landed 1fad68657)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/dropord/cex/c9.logos
fn p(fmt: str, v: i32) { unsafe { printf(fmt.as_ptr(), v); } }
struct O { id: i32 }
impl Drop for O { fn drop(&mut self) { p("%d", self.id); } }
struct S3 { a: O, b: O, c: O }
fn eat(x: O) { p("e%d", x.id); }
fn __logos_main() -> i32 {
    {
        let s: S3 = S3 { a: O { id: 1 }, b: O { id: 2 }, c: O { id: 3 } };
        eat(s.b);
        p("[%d]", 0);
    }
    unsafe { printf(b"\n\0".as_ptr()); }
    return 0;
}

fn main() { std::process::exit(__logos_main() as i32); }

