// TWIN of tests/logos/pass/bc_0909elide_hb_e6_mut_recv_ret_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: receiver self: &mut T -> &mut self
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-09elide, program e6_mut_recv_ret — caught: verdict moved base -> landed — PROBES.md "e1_param_only ... rc 1 -> rc 0, links, RUNS 0" (e2 e3 e6 same)
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/ce/e6_mut_recv_ret.logos
// &mut receiver, elided output. Trait names, impl elides.
struct R { v: i64 }
trait T {
    fn get<'a>(self: &'a mut Self, k: i64) -> &'a mut i64;
}
impl T for R {
    fn get(&mut self, k: i64) -> &mut i64 {
        return &mut self.v;
    }
}
fn __logos_main() -> i32 {
    let mut r: R = R { v: 1i64 };
    let p: &mut i64 = r.get(2i64);
    *p = 42i64;
    if r.v != 42i64 { return 1; }
    return 0;
}

fn main() { std::process::exit(__logos_main() as i32); }

