// TWIN of tests/logos/pass/bc_0914o_autoreffund_hb_c21_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: `use logos.lang.cmp;` dropped: stdlib path, prelude in Rust
// TWIN: extern fn printf -> unsafe extern "C" block (edition 2024)
// TWIN: drop receiver spelling self: &mut T -> &mut self
// TWIN: printf format literal -> b"..\0".as_ptr() (Rust has no implicit C string)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
unsafe extern "C" { fn printf(fmt: *const u8, ...) -> i32; }
// hand battery: round 2026-09-14o-autoreffund, program c21 — caught: operator temporaries in a while body with `continue` between two statements: base dropped none (n=0); 4334 under the landing
// legality: by reading, no rustc binary
struct C { v: i64, c: *mut i64 }
impl Drop for C { fn drop(&mut self) { unsafe { *self.c = *self.c + self.v; } } }
impl Eq for C { fn eq(&self, other: &C) -> bool { return self.v > 0i64 && other.v > 0i64; } }
fn mkc(v: i64, c: *mut i64) -> C { return C { v: v, c: c }; }
fn __logos_main() -> i32 {
    let mut n: i64 = 0i64;
    let p: *mut i64 = &mut n;
    let mut i: i64 = 0i64;
    let mut hits: i64 = 0i64;
    while i < 4i64 {
        i = i + 1i64;
        if mkc(1i64, p) == mkc(1000i64, p) { hits = hits + 1i64; }
        if i == 2i64 { continue; }
        if mkc(10i64, p) != mkc(100i64, p) { return 3i32; }
    }
    let got: i64 = unsafe { n };
    unsafe { printf(b"hits=%ld n=%ld\n\0".as_ptr(), hits, got); }
    if hits != 4i64 { return 2i32; }
    if got != 4334i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

