// TWIN of tests/logos/pass/bc_0914j_fnptrbinder_hb_h21_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-14j-fnptrbinder, program h21 — caught: refuted fnptrelidesup: REFUSED this legal program — two item binders inside a tuple parameter
// legality: by reading, no rustc binary
fn sumt<'a, 'b>(t: (&'a i64, &'b i64)) -> i64 { return *t.0 + *t.1; }
fn __logos_main() -> i32 {
    let f: fn((&i64, &i64)) -> i64 = sumt;
    let x: i64 = 30i64;
    let y: i64 = 1i64;
    return f((&x, &y)) as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

