// TWIN of tests/logos/pass/bc_0909d_atland_hb_g08_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-09d-atland, program g08 — caught: verdict moved base -> landed — tables/hand_head.txt vs hand_final.txt: run=1 or cc=1 on HEAD -> cc=0 run=0 landed; PROBES.md "ELEVEN of fifteen were already wrong before a line w...
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-09d-atland/hand/g08.logos
// `mut` at-binding in STRUCT FIELD position, then assigned through.
struct P { x: i64, y: i64 }
fn __logos_main() -> i32 {
    let p: P = P { x: 1i64, y: 2i64 };
    let mut out: i64 = 0i64;
    match p {
        P { x: mut a @ _, y } => { a = a + 10i64; out = a + y; }
    }
    if out != 13i64 { return 1i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

