// TWIN of tests/logos/pass/bc_0912q_letregion_hb_m1_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-12q-letregion, program m1 — caught: verdict moved base -> landed — PROBES.md "Newly COMPILING, all legal, all run to their exit code: y1 y2 y3 (deref stop) · a6 a10 e3 m1 m3 m4 m5 o3"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from snapshot hand-harvest-2026-09-14/25aa8421-fce1-4a11-8a89-5d2ba5981c88/r0912q/ctl/m1_legal_method_own_binder.logos
struct A<'a> { x: &'a i64 }
struct S { k: i64 }
impl S {
    fn pick<'q>(&self, x: &'q i64) -> A<'q> {
        return A { x: x };
    }
}
fn __logos_main() -> i32 {
    let s: S = S { k: 1i64 };
    let v: i64 = 20i64;
    let a: A<'_> = s.pick(&v);
    return *a.x as i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

