// TWIN of tests/logos/pass/bc_0906g_refmode_hb_h20_admit.logos
// Generated by mktwin.py: envelope translated, BODY VERBATIM.
// TWIN: package decl dropped (no Rust equivalent)
// TWIN: fn main() -> i32 is illegal in Rust; body moved to __logos_main() and main() exits with its value. Exit code preserved.
// hand battery: round 2026-09-06g-refmode, program h20 — caught: refuted an arm — PROBES.md "Under `tupboth` ... FOUR do not — h01 h05 h19 h20 — ... use of moved field 't.0'"
// legality: by reading, no rustc binary
// harvested 2026-09-14h from src/compiler/probes/2026-09-06g-refmode/hand/h20.logos
// LEGAL. THREE-element tuple, `ref mut` in the MIDDLE (index is not 0).
fn __logos_main() -> i32 {
    let mut t: (i64, i64, i64) = (1i64, 3i64, 4i64);
    match t {
        (a, ref mut b, c) => { *b = *b + 1i64; if a + *b + c != 9i64 { return 1i32; } }
    }
    if t.1 != 4i64 { return 2i32; }
    return 0i32;
}

fn main() { std::process::exit(__logos_main() as i32); }

