#!/usr/bin/env bash
# AST-equality oracle for peg_gen_logos.
#
# Builds two stringify harnesses — one linking the C++-generated logos_parser
# (peg_gen_cpp, embedded in logosc) and one linking the Logos-generated
# logos_parser (peg_gen_logos) — then parses every file in a corpus with both,
# serialises each AST via the canonical writ::stringify, and diffs the output.
# Byte-identical on every file ⇒ the Logos-native parser matches the C++ one.
#
# This is a narrow tool for working on the parser itself; it is NOT a ctest test.
# Run it on demand:  tools/peg_gen_logos/oracle/run.sh [build_dir] [corpus_dir]
# or:                cmake --build build --target peg_gen_logos_oracle
#
# Requires logosc + peg_gen_logos already built.
set -u

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../../.." && pwd)"
build="${1:-$repo/build}"
corpus="${2:-$repo/tests/logos}"

logosc="$build/bin/logosc"
peg_logos="$build/bin/peg_gen_logos"
libd="$build/lib/logos"
grammar="$repo/tools/peg_gen_cpp/grammars/logos.peg"
cpp_parser="$build/src/compiler/logos_parser.cpp"   # generated by peg_gen_cpp

for f in "$logosc" "$peg_logos" "$cpp_parser"; do
    [ -e "$f" ] || { echo "missing $f — build logosc + peg_gen_logos first (cmake --build $build)"; exit 1; }
done

cxx="$(sed -n 's/^CMAKE_CXX_COMPILER:[^=]*=//p' "$build/CMakeCache.txt" 2>/dev/null)"
[ -n "$cxx" ] || cxx=clang++
# Build the Logos harness at the same -O level as the shipped stdlib/parser so
# the oracle gates the OPTIMIZED codegen path (override with OPT=, e.g. OPT="").
OPT="${OPT:--O2}"
flt() { grep -vE 'version-mismatch|no ABI guarantee|may be unstable'; }

work="$build/peg_gen_logos_oracle"
rm -rf "$work"; mkdir -p "$work/pkg"

echo "== building C++ harness =="
core="$(find "$build" -name 'liblogos_core*.a' | head -1)"
"$cxx" -std=c++23 -I "$repo/include" -I "$build/src/compiler" \
    "$here/cpp_stringify.cpp" "$cpp_parser" \
    -Wl,--start-group \
      "$build/src/writ/liblogos_writ.a" \
      "$build/src/verification/liblogos_verification.a" \
      "$core" \
    -Wl,--end-group -lpthread \
    -o "$work/cpp_los" || { echo "C++ harness build failed"; exit 1; }

echo "== building Logos harness =="
cp "$here/sdump.logos" "$work/pkg/sdump.logos"
"$peg_logos" "$grammar" --out-dir "$work/pkg" 2>&1 | flt | grep -v '^peg_gen_logos: wrote$' | grep -v "$work" || true
cat > "$work/pkg/oracle.module" <<EOF
module logos_parser
version 0.1
root $work/pkg/
EOF
"$logosc" $OPT --emit-module "$work/pkg/oracle.module" -o "$work/pkg.a" 2>&1 | flt | grep -iE 'error' && exit 1
"$logosc" $OPT -l "$work/pkg.a" "$here/oracle_main.logos" -o "$work/main.o" 2>&1 | flt | grep -iE 'error' && exit 1
"$cxx" -Wl,--gc-sections "$work/main.o" -Wl,--start-group "$work/pkg.a" \
    "$libd/liblogos-lang.a" "$libd/liblogos-mem.a" "$libd/liblogos-lcm.a" "$libd/liblstdlib_rt.a" "$libd/liblstdlib_fibers.a" \
    -Wl,--end-group -Wl,--allow-multiple-definition -lpthread -lm -o "$work/los" \
    2>&1 | grep -iE 'undefined|error' && exit 1

echo "== diffing $(find "$corpus" -name '*.logos' | wc -l) files in $corpus =="
total=0; match=0; mism=0; fails="$work/mismatches.txt"; : > "$fails"
while IFS= read -r f; do
    total=$((total+1))
    c="$(timeout 20 "$work/cpp_los" "$f" 2>/dev/null)"
    l="$(timeout 20 "$work/los" "$f" 2>/dev/null)"
    if [ "$c" == "$l" ]; then match=$((match+1)); else mism=$((mism+1)); echo "$f" >> "$fails"; fi
done < <(find "$corpus" -name '*.logos' -type f | sort)

echo "----------------------------------------"
echo "MATCH=$match  MISMATCH=$mism  /  $total"
if [ "$mism" -ne 0 ]; then echo "mismatches (also in $fails):"; sed 's/^/  /' "$fails" | head -40; exit 1; fi
echo "✓ all $total files: Logos parser AST == C++ parser AST"
