# Embeds Datalog rule files into a C++ source (ADR 0028). Run as a script:
#
#   cmake -DOUT=<file.cpp> -DFILES=<a.dl|b.dl> -P DlEmbed.cmake
#
# FILES is '|'-separated: a ';' list would be split by the build tool's shell.
# The generated source defines logos::dl::embedded_rule_file(name), keyed by
# file basename, so `#include "x.dl"` inside a rule file resolves the same way
# it does under Souffle's -I.
set(body "")
string(REPLACE "|" ";" FILES "${FILES}")
foreach(f IN LISTS FILES)
    get_filename_component(name "${f}" NAME)
    file(READ "${f}" text)
    string(FIND "${text}" ")DLRULES\"" clash)
    if(NOT clash EQUAL -1)
        message(FATAL_ERROR "${f} contains the raw-string delimiter )DLRULES\"")
    endif()
    string(APPEND body "    {\"${name}\", R\"DLRULES(${text})DLRULES\"},\n")
endforeach()
file(WRITE "${OUT}.tmp"
"// Generated by cmake/DlEmbed.cmake from src/compiler/dl/rules. Do not edit.
#include <optional>
#include <string_view>

namespace logos::dl {

struct EmbeddedRuleFile { std::string_view name, text; };

static const EmbeddedRuleFile kFiles[] = {
${body}};

std::optional<std::string_view> embedded_rule_file(std::string_view name) {
    for (const auto& f : kFiles)
        if (f.name == name) return f.text;
    return std::nullopt;
}

} // namespace logos::dl
")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
